### ISSUE TITLE
call_user_func product 139 error

### ISSUE THREAD

**Issue by kse300489** [zephir-lang/zephir#1036]
I can't use `call_user_func`, it crash the script with 139 error

My OS: Linux nettop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1 (2015-05-24) x86_64 GNU/Linux
PHP: 5.6.9-0+deb8u1 (cli) (built: Jun  5 2015 11:03:27)

On 32bit version `call_user_func` not crash the script.

`call_user_func_array` works grate on 32bit and on 64bit.
##

**Comment by fezfez** [comment]
see : https://github.com/phalcon/zephir/blob/master/CONTRIBUTING.md

**Comment by coollider** [comment]
And? I muts add stupid example with `call_user_func`?

**Comment by steffengy** [comment]
Why would you call it stupid?
It means less work for us trying to reproduce that issue and therefore is 
a very valid guideline.

Thanks for providing an example, but I just cannot appreciate your ignorance.
I think it would be beneficial for everyone if you would refrain from such comments,
without clarifying why you think it's stupid - which you could express less negative.

**Comment by coollider** [comment]
I asked a very simple but at the same time a very detailed question about `call_user_func`. But in response, I received a link to a list of rules. It looks like neglect. Everyone knows how to use `call_user_func`, an example in this case is superfluous.

**Comment by ovr** [comment]
@steffengy +1 :beer: 

@coollider 
https://github.com/phalcon/zephir/blob/master/CONTRIBUTING.md#bugs

When submitting bugs to the issue tracker make sure your issue includes:
 - Code to reproduce the bug
 - Your environment: OS, compiler
 - Zephir version, if your version is outdated - try updating the latest version

**Comment by coollider** [comment]
@ovr 

I add iformation about environment at the firt post.
Compiler: gcc version 4.9.2 (Debian 4.9.2-10) 
Zephir version: 0.7.1b
