### ISSUE TITLE
undefined symbol: zephir_pow_function in Unknown on line 0

### ISSUE THREAD

**Issue by MarkBaker** [zephir-lang/zephir#1079]
I've built an extension using zephir based on ircmaxell's math evaluator (https://gist.github.com/ircmaxell/1232629) including a Power.zep operator using the standard PHP `pow()` function (not the new PHP `**` operator, because zephir doesn't yet seem to recognise that, and gives a syntax error in the compile).

``` zephir
namespace Evaluator\Operators;

use Evaluator\Stack;
class Power extends Operator
{
    protected precedence = 6;
    public function operate(<Stack> stack)
    {
        var left, right;

        let left  = stack->pop()->operate(stack);
        let right = stack->pop()->operate(stack);

        return pow(right, left);
    }

}
```

I'm compiling against PHP 5.6.12: `zephir compile` and `zephir install` both ran cleanly with zephir 0.7.1b, reporting no errors.

However, when I added the extension to my php.ini and tried to do a basic `php -m`, I got an error:

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/usr/lib/php5/20131226/evaluator.so' - /usr/lib/php5/20131226/evaluator.so: undefined symbol: zephir_pow_function in Unknown on line 0
```

---

I've removed the evaluator entry from php.ini, and have removed that one class and related calls (eliminating the power functionality) from the codebase. `zephir compile` still runs without error, but `zephir install` now fails. The compile-errors log shows:

```
cp: cannot stat `modules/*': No such file or directory
make: *** [install-modules] Error 1
```

Not sure if this is a related problem. I've even blasted the folder and started again from `zephir init evaluator` but without success

**Comment by steffengy** [comment]
That seems strance since zephir_pow_function is actually a macro.
Could you provide the generated code (ext/evaluator/operators/power.zep.c)?

**Comment by MarkBaker** [comment]
There's a whole lot more code, that was just one class that comprised part of the evaluator package, I was just guessing that it might be the problem because it was the only class that used the PHP pow() function. However, power.zep.c is

``` c
#ifdef HAVE_CONFIG_H
#include "../../ext_config.h"
#endif

#include <php.h>
#include "../../php_ext.h"
#include "../../ext.h"

#include <Zend/zend_operators.h>
#include <Zend/zend_exceptions.h>
#include <Zend/zend_interfaces.h>

#include "kernel/main.h"
#include "kernel/memory.h"
#include "kernel/fcall.h"
#include "kernel/math.h"


ZEPHIR_INIT_CLASS(Evaluator_Operators_Power) {

        ZEPHIR_REGISTER_CLASS_EX(Evaluator\\Operators, Power, evaluator, operators_power, evaluator_operators_operator_ce, evaluator_operators_power_method_entry, 0);

        zend_declare_property_long(evaluator_operators_power_ce, SL("precedence"), 6, ZEND_ACC_PROTECTED TSRMLS_CC);

        return SUCCESS;

}

PHP_METHOD(Evaluator_Operators_Power, operate) {

        int ZEPHIR_LAST_CALL_STATUS;
        zval *stack, *left = NULL, *right = NULL, *_0 = NULL, *_1 = NULL;

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 1, 0, &stack);



        ZEPHIR_CALL_METHOD(&_0, stack, "pop", NULL, 0);
        zephir_check_call_status();
        ZEPHIR_CALL_METHOD(&left, _0, "operate", NULL, 0, stack);
        zephir_check_call_status();
        ZEPHIR_CALL_METHOD(&_1, stack, "pop", NULL, 4);
        zephir_check_call_status();
        ZEPHIR_CALL_METHOD(&right, _1, "operate", NULL, 0, stack);
        zephir_check_call_status();
        zephir_pow_function(return_value, right, left);
        RETURN_MM();

}
```

and does indeed contain the call to `zephir_pow_function()`

**Comment by steffengy** [comment]
I might have an idea what causes this:

can you replace 
`$context->headersManager->add('kernel/math');`
with 
`$context->headersManager->add('kernel/operators');`
 in _Zephir\Library\Optimizers\PowOptimizer.php_
and report if that fixes it?

**Comment by MarkBaker** [comment]
The `power.zep.c` file now has

```
#include "kernel/operators.h"
```

instead of

```
#include "kernel/math.h"
```

Just need to figure out why the `zephir install` is failing on me

**Comment by MarkBaker** [comment]
I've moved the evaluator.so manually from `ext/modules` to `/usr/lib/php5/20131226/evaluator.so` and added `evaluator.so` back into my php.ini.

A `php -m` now runs correctly, and reports that evaluator is installed as a module.

Running my tests now fails with a runtime exception, but I guess that's an error in my conversion from native PHP and implementation of the classes in the Zephir language.

**Comment by MarkBaker** [comment]
Confirming that the change to `kernel/operators` from `kernel/math` worked. I'm guessing that it's related to the fact that `**` is now an operator in PHP > 5.6.0, and I'm using 5.6

**Comment by steffengy** [comment]
It's just a typo in the regarding source code, the macros were defined as operators for a long time.
It just wasn't noticed because people mostly use other operators in any form, so it would be automatically included.

Edit. Fixed in development.
