### ISSUE TITLE
Undefined property: Zephir\Operators\Comparison\GreaterOperator::$_zvalStringOperator

### ISSUE THREAD

**Issue by MarkBaker** [zephir-lang/zephir#1080]
Running Zephir 0.7.1b, I'm getting a notice from Zephir itself

```
PHP Notice:  Undefined property: Zephir\Operators\Comparison\GreaterOperator::$_zvalStringOperator in /home/vagrant/zephir/Library/Operators/Comparison/ComparisonBaseOperator.php on line 720
```

Unsure exactly what might be triggering this. I'm using comparisons in other scripts without this appearing
##

**Comment by fezfez** [comment]
Can you add a sample code ?

**Comment by MarkBaker** [comment]
Not easily, because it's a fairly large script, and I can't easily identify what part of my code is triggering that call to `Zephir\Operators\Comparison\GreaterOperator` to generate the notice; but I'll try to track it down based on the assumption that it's being triggered by a `>`

The most likely (guessing) is a block of code:

```
    public function add(key, value = null)
    {
        var trieNodeEntry;

        if key > "" {
            let trieNodeEntry = this->getTrieNodeByKey(key, true);

            if trieNodeEntry->value === null {
                let trieNodeEntry->value = [value];
            } else {
                array_push(trieNodeEntry->value, value);
            }
        } else {
            throw new \InvalidArgumentException("Key value must not be empty");
        }
    }
```

and the

```
if key > "" {
```

check inside that

Changing that line of code to

```
if !empty(key) {
```

eliminates the compiler notice

**Comment by steffengy** [comment]
I think to compare strings using `>` is not really a good practice.
Is there any advantage of using that insteadof `!empty` that I'm not seeing there?

**Comment by MarkBaker** [comment]
It may not be good practise, but it's common practise; and should perhaps at the very least be documented suggesting to use `!empty` as an alternative for those who are used to using `> ''` in PHP.... but I wouldn't expect the compiler to give a notice either, but perhaps flag it as an error when compiling so that it's more obvious that the comparison should be changed

**Comment by steffengy** [comment]
I didn't say it wasn't a bug, it very likely is 
(or to be exact, greater/lower comparisons not being implemented for strings properly),
I just personally wondered if there's any advantage of using it.

**Comment by Andrew-Shook** [comment]
I don't think this should be marked as a bug. If you tried to compare a string using that syntax in C or C++ you would receive an compiler error as well. While Zephir looks like PHP, I've alway thought of it as C in a nice PHPish wrapper. I could be wrong it that assumption.

**Comment by steffengy** [comment]
You should never get an warning of the runtime that's running the compiler.
That's why it's marked as bug.

**Comment by Jeckerson** [comment]
Already fixed. Closing.
