### ISSUE TITLE
length doesn't work ?

### ISSUE THREAD

**Issue by Izopi4a** [zephir-lang/zephir#1084]
the following  code 

```
var lala = "asdasdasda";
var_dump(lala->length());

```

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Trying to call method length on a non-object'

I check the docs but it doesn't seems to have some hidden declarations ?

**Comment by fezfez** [comment]
try

``` zephir
var lala = "asdasdasda";
var_dump(length(lala));
```

**Comment by Izopi4a** [comment]
```
Warning: Function "length" does not exist at compile time ....

```

```

PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Call to undefined function length()'

```

**Comment by fezfez** [comment]
Sorry, i made a typo... try :

``` zephir
var lala = "asdasdasda";
var_dump(strlen(lala));
```

**Comment by Izopi4a** [comment]
yes this works, it's what i am using, but according to this : http://docs.zephir-lang.com/en/latest/builtin-methods.html#string, its better to use build in methods

**Comment by steffengy** [comment]
It doesn't work because you call it on a variable, and not a string.
It also isn't better but just another way of calling strlen.

```
string lala = "asdasdasda";
var_dump(lala->length());
```

should work.

**Comment by Izopi4a** [comment]
aha... so that's the secret.
Ok thanks :D
