### ISSUE TITLE
BUG function params array!

### ISSUE THREAD

**Issue by nekulin** [zephir-lang/zephir#1086]
This code does not work

```zep
public static function test1(array! params)
{
    let params["test2"] = 1234;
}

public static function test()
{
    array params;

    let params = [];
    let params["test"] = 123;

    self::test1(params);

    var_dump(params);
    die();
}
```

When you call the test I get "NULL" instead of array(1) { ["test"]=> int(123) } but if you remove "array!" and put the "array" I get array(1) { ["test"]=> int(123) }

This code works

```zep
public static function test1(array params)
{
    let params["test2"] = 1234;
}

public static function test()
{
    array params;

    let params = [];
    let params["test"] = 123;

    self::test1(params);

    var_dump(params);
    die();
}
```

**Comment by Izopi4a** [comment]
it doesnt work like that, as far as I know. If you want this to work, you have to use references. 
however if you try using references you get this message:

```
Zephir\CompilerException: Zephir not support reference parameters for now. Stay tuned for https://github.com/phalcon/zephir/issues/203
```

Now you can always try this:

```
public static function test1(array params)
    {
        let params["test2"] = 1234;
        return params;
    }

public static function test()
{
    array params;

        let params = [];
        let params["test"] = 123;

        let params = self::test1(params);

        var_dump(params);
        die();
}
```

**Comment by nekulin** [comment]
I don't want to use the links and I don't want array! changed params

**Comment by nekulin** [comment]
I shouldn't get NULL I had to get array(1) { ["test"]=> int(123) }

**Comment by Izopi4a** [comment]
pfff sorry didnt see that detail :D

but yea... same behavior for me aswell

**Comment by steffengy** [comment]
Can you check if this works for you, using the latest master (seems to work for me)?
