### ISSUE TITLE
BUG str_replace array

### ISSUE THREAD

**Issue by nekulin** [zephir-lang/zephir#1087]
```
let filtered = "test_test";
let sanitize = ["/", "'", "\"", "?", "!", "%", "$", "&"]; 
    let filtered = str_replace(sanitize, "", filtered);

    var_dump(filtered);
```

Result Zephir: string(0) ""
Result PHP: string(9) "test_test"

**Comment by steffengy** [comment]
Are you using the development branch?

**Comment by nekulin** [comment]
I use the stable version Powered by Zephir  Version 0.7.1b

**Comment by steffengy** [comment]
This doesn't happen when using development.

**Comment by andresgutierrez** [comment]
@steffengy Let's merge development into master

**Comment by nekulin** [comment]
You have not managed to reproduce the bug ? Or is it fixed in the development branch ?

**Comment by andresgutierrez** [comment]
@nekulin Please change your branch to development

```
cd zephir
git checkout development
git pull -u
```

**Comment by steffengy** [comment]
@andresgutierrez
I literally thought the same thing :)
It also maybe makes sense to exchange some kind of private contact information (Instant Messaging or IRC or similar), to discuss
some future steps.
Generally I think the next step after merging development into master would be to push the version and then getting cphalcon to compile. 
(which I haven't done yet, since I'm mainly using windows and that's a bit tricky to set up)

**Comment by andresgutierrez** [comment]
Sure, please send me your gtalk to andres@phalconphp.com

**Comment by nekulin** [comment]
I compiled a version with development, the problem remained and the version has not changed, also 0.7.1 b

**Comment by steffengy** [comment]
That is indeed strange, since it works for me on 5.6,
which PHP version are you using?

**Comment by nekulin** [comment]
PHP 5.5.28

**Comment by steffengy** [comment]
I just added the code from your issue to the tests and they all pass for PHP5.X - PHP 7.
How did you declare `filtered` and `sanitize` ?

**Comment by nekulin** [comment]
```
string filtered;
array sanitize;
```

**Comment by nekulin** [comment]
zephir version - Sie welche Version ?

**Comment by steffengy** [comment]
I cannot reproduce this.

```
string filtered;
array sanitize;
let filtered = "test_test";
let sanitize = ["/", "'", "\"", "?", "!", "%", "$", "&"];
let filtered = str_replace(sanitize, "", filtered);

var_dump(filtered);
exit();
```

results in `string(9) "test_test"` for me.
Maybe retry using master, after the merge now (and possibly a zephir clean / zephir fullclean)

**Comment by Izopi4a** [comment]
i can confirm str_replace array works now

**Comment by sergeyklay** [comment]
Possible refs #732
