### ISSUE TITLE
Problem using variables named `resource`

### ISSUE THREAD

**Issue by mateusdemboski** [zephir-lang/zephir#1088]
Hello!
i'm writing a class and need a public variable with name `resource`, but when i try compile my code the zephir throw the exception: `Zephir\ParseException: Syntax error in [...]/Permissions.zep on line 24`
the line 24: `public resource;`

This is a possible bug or `resource` is a reserved variable in zephir?
What i  can make?

tks for all help. =)

**Comment by andresgutierrez** [comment]
It's a reserved word, you have to escape it: public $resource;

**Comment by mateusdemboski** [comment]
ok, tnks!
Exists a list of reserved variables in zephir? I didn't find on documentation... =/

**Comment by steffengy** [comment]
Generally you can consider any part of the syntax an reserved keyword.
If you need a list, you could extract it from the lexer definition.

**Comment by fezfez** [comment]
This is my actual reserved word list, is it ok ?
- inline
- Inline
- array
- class
- var
- bool
- namespace
- const
- enum
- interface
- loop
- for
- foreach
- if
- elseif
- else
- function
- private
- protected
- public
- boolean
- return
- abstract
- resource
- callable
- string
- float
- int

**Comment by Green-Cat** [comment]
There is also internal and deprecated.

**Comment by fezfez** [comment]
@Green-Cat Thanks :+1:
