### ISSUE TITLE
Nested Closures

### ISSUE THREAD

**Issue by skmail** [zephir-lang/zephir#1091]
Hey,

I'm trying to use nested closures but seem it not supported yet?, the compiler firing the following error, 

 "Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information"

> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c: In function 'zim_bs_0__closure___invoke':
> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c:40:36: error: 'bs_1__closure_ce' undeclared (first use in this function)
> zephir_create_closure_ex(v, NULL, bs_1__closure_ce, SS("__invoke") TSRMLS_CC);
> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c:40:36: note: each undeclared identifier is reported only once for each function it appears in
> make: **\* [bs/0__closure.lo] Error 1
> make: **\* Waiting for unfinished jobs....
> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c: In function 'zim_bs_0__closure___invoke':
> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c:40:36: error: 'bs_1__closure_ce' undeclared (first use in this function)
> zephir_create_closure_ex(v, NULL, bs_1__closure_ce, SS("__invoke") TSRMLS_CC);
> /home/vagrant/projects/zephir-projects/bs/ext/bs/0__closure.zep.c:40:36: note: each undeclared identifier is reported only once for each function it appears in
> make: **\* [bs/0__closure.lo] Error 1

And here is my code sample.

```
this->_di->set("service",  function(){
    let service = new Service();
    service->setOptions([
        function(){

        }
    ]);
});
```

Zephir version
![screen shot 2015-09-21 at 7 15 58 pm](https://cloud.githubusercontent.com/assets/3670810/9997515/3cfb32a4-6095-11e5-88a0-11af934f14be.png)

Regards
##

**Comment by fezfez** [comment]
``` zephir
this->_di->set("service",  = function(){
```

Why there is an equal ?

**Comment by skmail** [comment]
syntax error .. , it's just  a sample !

**Comment by sergeyklay** [comment]
Could you please explain the benefits of nested closures?

**Comment by skmail** [comment]
The following example from Phalcon docs to activate Volt template engine , written in PHP 

```
use Phalcon\Mvc\View;

// Register Volt as template engine with an anonymous function
$di->set('view', function () {

    $view = new View();

    $view->setViewsDir('../app/views/');

    $view->registerEngines(array(
        ".volt" => function ($view, $di) {
            $volt = new Volt($view, $di);

            // Set some options here

            return $volt;
        }
    ));

    return $view;
});
```

I'm trying to do something similar  in Zephir  instead of PHP. Can I?

I know that i can  register another service  for Volt engine and then assign the service as string, but what about the nested closures? i think it's a basics.

Regards
