### ISSUE TITLE
Zephir failing basic float comparison

### ISSUE THREAD

**Issue by MarkBaker** [zephir-lang/zephir#1092]
I have the following code (with basic diagnostics added) trying to test if a simple float value (`pointX`) falls between two other float values (accessed via the calls to `this->startX()` and `this->endX()`):

``` zephir
protected function isXinRange(float pointX) -> boolean
{
    echo "Testing "; var_dump(pointX); echo " is between ";
    var_dump(this->startX()); echo " and ";
    var_dump(this->endX()); echo PHP_EOL;

    if pointX >= this->startX() {
        echo pointX, " >= ", this->startX(), PHP_EOL;
    } else {
        echo "WTF #1", PHP_EOL;
    }

    if pointX <= this->endX() {
        echo pointX, " <= ", this->endX(), PHP_EOL;
    } else {
        echo "WTF #2", PHP_EOL;
    }

    return pointX >= this->startX() && pointX <= this->endX();
}
```

The output that this generates is:

```
Testing float(0)
 is between float(-180)
 and float(180)

WTF #1
WTF #2
```

So 0 isn't between -180 and 180?

With my diagnostics removed, this is a simple:

```
    protected function isXinRange(float pointX) -> boolean
    {
        return pointX >= this->startX() && pointX <= this->endX();
    }
```

and generates the following code in the zep.c file:

```
PHP_METHOD(QuadTrees_QuadTreeBoundingBox, isXinRange) {

        zend_bool _1;
        int ZEPHIR_LAST_CALL_STATUS;
        zval *pointX_param = NULL, *_0 = NULL, *_2 = NULL;
        double pointX;

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 1, 0, &pointX_param);

        pointX = zephir_get_doubleval(pointX_param);


        ZEPHIR_CALL_METHOD(&_0, this_ptr, "startx", NULL, 0);
        zephir_check_call_status();
        _1 = ZEPHIR_IS_DOUBLE(_0, pointX);
        if (_1) {
                ZEPHIR_CALL_METHOD(&_2, this_ptr, "endx", NULL, 0);
                zephir_check_call_status();
                _1 = ZEPHIR_IS_DOUBLE(_2, pointX);
        }
        RETURN_MM_BOOL(_1);

}
```

The calls to `startx` and `endx` respectively:

```
PHP_METHOD(QuadTrees_QuadTreeBoundingBox, startX) {

        int ZEPHIR_LAST_CALL_STATUS;
        zval *_0, *_1 = NULL, *_2;

        ZEPHIR_MM_GROW();

        _0 = zephir_fetch_nproperty_this(this_ptr, SL("centrePoint"), PH_NOISY_CC);
        ZEPHIR_CALL_METHOD(&_1, _0, "getx", NULL, 0);
        zephir_check_call_status();
        _2 = zephir_fetch_nproperty_this(this_ptr, SL("width"), PH_NOISY_CC);
        RETURN_MM_DOUBLE((zephir_get_numberval(_1) - zephir_safe_div_zval_long(_2, 2 TSRMLS_CC)));

}

PHP_METHOD(QuadTrees_QuadTreeBoundingBox, startY) {

        int ZEPHIR_LAST_CALL_STATUS;
        zval *_0, *_1 = NULL, *_2;

        ZEPHIR_MM_GROW();

        _0 = zephir_fetch_nproperty_this(this_ptr, SL("centrePoint"), PH_NOISY_CC);
        ZEPHIR_CALL_METHOD(&_1, _0, "gety", NULL, 0);
        zephir_check_call_status();
        _2 = zephir_fetch_nproperty_this(this_ptr, SL("height"), PH_NOISY_CC);
        RETURN_MM_DOUBLE((zephir_get_numberval(_1) - zephir_safe_div_zval_long(_2, 2 TSRMLS_CC)));

}
```

Zephir version 0.7.1b

It seems to me that the generated code is retrieving the values for the comparisons, but failing to generate the code to execute the actual comparisons themselves.

**Comment by steffengy** [comment]
Yeah that seems broken. Working on a fix

**Comment by steffengy** [comment]
It might be fixed in master now. @MarkBaker Can you confirm?

**Comment by MarkBaker** [comment]
From a `git pull` of the master branch:

When I run `zephir compile` I'm seeing

```
PHP Notice:  Undefined property: Zephir\Operators\Comparison\GreaterEqualOperator::$_zvalDoubleNegOperator in /home/vagrant/zephir/Library/Operators/Comparison/ComparisonBaseOperator.php on line 459
PHP Notice:  Undefined property: Zephir\Operators\Comparison\LessEqualOperator::$_zvalDoubleNegOperator in /home/vagrant/zephir/Library/Operators/Comparison/ComparisonBaseOperator.php on line 459
PHP Notice:  Undefined property: Zephir\Operators\Comparison\GreaterEqualOperator::$_zvalDoubleNegOperator in /home/vagrant/zephir/Library/Operators/Comparison/ComparisonBaseOperator.php on line 459
PHP Notice:  Undefined property: Zephir\Operators\Comparison\LessEqualOperator::$_zvalDoubleNegOperator in /home/vagrant/zephir/Library/Operators/Comparison/ComparisonBaseOperator.php on line 459
```

Generates code in the `zep.c` file now reads:

```
PHP_METHOD(QuadTrees_QuadTreeBoundingBox, isXinRange) {

        zend_bool _6;
        zephir_fcall_cache_entry *_1 = NULL, *_3 = NULL;
        int ZEPHIR_LAST_CALL_STATUS;
        zval *pointX_param = NULL, *_0 = NULL, *_2 = NULL, *_4, *_5 = NULL, *_7 = NULL;
        double pointX;

        ZEPHIR_MM_GROW();
        zephir_fetch_params(1, 1, 0, &pointX_param);

        pointX = zephir_get_doubleval(pointX_param);


        php_printf("%s", "Testing ");
        php_printf("%f", pointX);
        php_printf("%s", " is between ");
        ZEPHIR_CALL_METHOD(&_0, this_ptr, "startx", &_1, 0);
        zephir_check_call_status();
        zend_print_zval(_0, 0);
        php_printf("%s", " and ");
        ZEPHIR_CALL_METHOD(&_2, this_ptr, "endx", &_3, 0);
        zephir_check_call_status();
        zend_print_zval(_2, 0);
        ZEPHIR_INIT_VAR(_4);
        ZEPHIR_GET_CONSTANT(_4, "PHP_EOL");
        zend_print_zval(_4, 0);
        ZEPHIR_CALL_METHOD(&_5, this_ptr, "startx", &_1, 0);
        zephir_check_call_status();
        _6 = (_5, pointX);
        if (_6) {
                ZEPHIR_CALL_METHOD(&_7, this_ptr, "endx", &_3, 0);
                zephir_check_call_status();
                _6 = (_7, pointX);
        }
        RETURN_MM_BOOL(_6);

}
```

**Comment by MarkBaker** [comment]
Patching the `Library/Operators/Comparison/ComparisonBaseOperator.php` code with `_zvalLongNegOperator` instead of `_zvalDoubleNegOperator` works for me; though I don't know if that's the correct solution for all situations.

Now I just need to figure out why my original PHP implementation is missing the first matching record for the search whereas the zephir version (correctly) retrieves it.

**Comment by steffengy** [comment]
That would convert the OP2-Double into a Long, so it might work for some cases but not for all.

**Comment by MarkBaker** [comment]
That's what concerned me: for the simple comparison to return a Boolean in my case, it isn't an issue, and allows me to test the rest of my library, but I don't believe that it's a solution for all cases

**Comment by steffengy** [comment]
It actually probably is a codegeneration bug since the functionality behind that should
be implemented:
`ZEPHIR_LE_DOUBLE` can be realised as `!ZEPHIR_GT_DOUBLE`
`ZEPHIR_GE_DOUBLE` -> `!ZEPHIR_LT_DOUBLE`
which just is missing for GreaterEquals and LowerEquals, in combination
with some in consistent code (see my reverted commit from today and the code in that area)

Will try to find some time to look at this properly

**Comment by steffengy** [comment]
I just implemented the approach mentioned above, @MarkBaker  
could you please test again, if that fixes your issue?

**Comment by MarkBaker** [comment]
That's working well now thanks. The library builds cleanly, and all tests run successfully, returning exactly the expected result.

Thank you for your quick response, and all your hard work on Zephir: it is much appreciated

**Comment by steffengy** [comment]
Thanks aswell for reporting that and in general for testing it for me.
We really need more tests in that area :)

**Comment by MarkBaker** [comment]
I'll certainly provide more feedback/issues/bugs

I'm running a workshop on using Zephir to build PHP extensions (converting from basic PHP Classes) at the PHPNW2015 conference in Manchester next weekend, so I needed to ensure that all my examples worked before putting them to the delegates.... for posterity, I'm posting them on github as well (https://github.com/MarkBaker?tab=repositories) and this completes the QuadTree implementation that I'll be pushing up there later this evening

**Comment by sergeyklay** [comment]
@MarkBaker :+1:
