### ISSUE TITLE
Zephir 0.9.a-dev doesn't work ?

### ISSUE THREAD

**Issue by Izopi4a** [zephir-lang/zephir#1115]
Hey, i just pulled master, and i compiled my extension but it doesnt work.

it ran zephir full clean.

The compiling is completing ok, No errors etc... but then inside phpinfo() my extension is missing.

I got back to the git hut folder, i checkout to 0.8 version, run full clean and then install again, everything is working fine.

Cheers

**Comment by steffengy** [comment]
Cannot reproduce.
