### ISSUE TITLE
error with the regular pattern,am i wrong?

### ISSUE THREAD

**Issue by hellobbq** [zephir-lang/zephir#1118]
``` zephir
string regex,str;
let regex = "/[\x{1F600}-\x{1F64F}]/u",
str = "......";
preg_replace_callback(regex,"sthFunction", str);
```

compile-errors.log

.....missing/utils/file.zep.c ... error: \x used with no following hex digits
  ZVAL_STRING(regex,"/[\x{1F600}-\x{1F64F}]/u");
....Zend/Zend_API.h:578:20 note:expanded from macro 'ZVAL_STRING'
 const char *__s=(s);

**Comment by andresgutierrez** [comment]
Try escaping it:

```
let regex = "/[\\x{1F600}-\\x{1F64F}]/u",
```

**Comment by yahveh** [comment]
@andresgutierrez thx,working ok.
what about even "\\\u" change to "\\\\u"?

**Comment by hellobbq** [comment]
@andresgutierrez  thanks,working ok
