### ISSUE TITLE
preg_replace_callback  Requires argument 2, 'self::_myMap', to be a valid callback

### ISSUE THREAD

**Issue by hellobbq** [zephir-lang/zephir#1119]
```
Warning: preg_replace_callback(): Requires argument 2, 'self::_myMap', to be a valid callback ....
```

zephir version 0.9a-dev php-5.6.13
##

**Comment by sergeyklay** [comment]
Could you please provide the code that produces the issue?

**Comment by hellobbq** [comment]
code example like:

``` zephir
class Test
{
    static protected function _myMap(array matches){
        return matches[0];
    }

    static public function  run(string str){
        string regex;
        let regex = "/[a-z0-9]/";
        return preg_replace_callback(regex, "self::_myMap", str);
    }
}
```

**Comment by fezfez** [comment]
Description from php doc : 

``` php
mixed preg_replace_callback (mixed $pattern, callable $callback, mixed $subject [, int $limit = -1 [, int &$count]])
```

The second argument must a callable not a string

**Comment by hellobbq** [comment]
@fezfez mac os  the pattern can be string or var. the problem happened on my virtual linux centos 6.5.
i'll test more when back home

**Comment by hellobbq** [comment]
@fezfez change "string" to "var",the problem still running php scripts

**Comment by steffengy** [comment]
The self scope isn't valid in this context.
You'll have to rely on a LSB, use `static::_myMap`, which seems to require `public` as visibility, which is related to the same scope limitation here.

Generally using an closure

```
return preg_replace_callback(regex, function (array matches) {
            return matches[0];
        }, str);
```

might be favorable, if that's possible for your case.

**Comment by hellobbq** [comment]
@steffengy 
my case needs:

```
return preg_replace_callback(regex, function (array matches) use (something) {
            return sprintf(something,matches[0]);
        }, str);
```

but not support the "use".
so, i do as your said, changing "static::..." and set "public",working well.
thank you very much

**Comment by hellobbq** [comment]
@steffengy sorry, @ wrong name,thanks a lot

**Comment by sergeyklay** [comment]
@steffengy Can be closed?
