### ISSUE TITLE
Can Zephir use C library?

### ISSUE THREAD

**Issue by WalterShe** [zephir-lang/zephir#1125]
Zephir is more great if it can use c libray.Can you implement the function??? 
I bealive you can !!!!
hahahhahaha.................

**Comment by racklin** [comment]
Yes. Zephir-Lang supports using c libraries. 
Please reffer http://docs.zephir-lang.com/en/latest/config.html#extra-cflags

**Comment by hylent** [comment]
See optimizers http://docs.zephir-lang.com/en/latest/optimizers.html
Connect PHP variables to C data types.

**Comment by WalterShe** [comment]
I must praise you in Chinese. 
帅呆了，酷毙了!果然很屌！
It mean that "Awesome, really good Kubi!"

**Comment by fezfez** [comment]
close ?
