### ISSUE TITLE
How to solve errors like "Double pointer of local zval requested"

### ISSUE THREAD

**Issue by kse300489** [zephir-lang/zephir#1135]
This error not show line or any information, how it must be solved?

**Comment by steffengy** [comment]
Do you have more information?
Helpful would be:
- sample code to trigger it (short, if possible)
  (you maybe lucky that it happens only recently, to track down the change with triggers it and narrow it down to this bug)
- php stack trace (output when using zephir with verbose=true)

**Comment by fezfez** [comment]
Same error here https://travis-ci.org/fezfez/php-to-zephir-samples/jobs/101381866#L362

**Comment by steffengy** [comment]
Since here aren't enough informaton to fix this, I'll close this.
If a similar error pops up, it can be diagnosed as described above and
should be filed as a separate issue.
