### ISSUE TITLE
PHP7, undefined symbol: ZEPHIR_CALL_USER_FUNC

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1138]
``` zep
if service instanceof \Closure {
    let service = call_user_func(service);
}
```

> undefined symbol: ZEPHIR_CALL_USER_FUNC

If I disable this (I'm not using it at all and it's not very important for me) I'm getting:

> Error: Call to undefined method Closure::handle()

But maybe this is related to phpunit.

**Comment by steffengy** [comment]
`undefined symbol: ZEPHIR_CALL_USER_FUNC` should be fixed.
Let me know if the second part also works now

**Comment by mruz** [comment]
It seems that it works. Thanks!
