### ISSUE TITLE
Getting segfault at runtime

### ISSUE THREAD

**Issue by imuneer** [zephir-lang/zephir#1145]
I have compiled a module. When I am trying to use it, it get segfault and the web page shows 'Bad Gateway 502'

My configuration:
- nginx
- php 5.6 using php-fm module
- Centos 6.6

Error:
`php-fpm[2182]: segfault at 15 ip 00007fe783d1ca29 sp 00007ffdd4ac9190 error 6 in xxxxxxxx.so`

**Comment by steffengy** [comment]
Could you provide any of the following:
- a detailed stack trace (debug build)
- a small code sample which triggers the segfault

I unfortunately can't really do much without knowing where to search.

**Comment by steffengy** [comment]
Closed due to missing information.
