### ISSUE TITLE
Glibc 2.14 Required!

### ISSUE THREAD

**Issue by mahmoud-eskandari** [zephir-lang/zephir#1146]
Move .so Extension to other machines 
1.
When I Wrote extension And Compile it In [UBUNTU 14.0 in php 5.5 dev] and i move my extension [*.so] File into CentOs 6.6 and Include This , php show [`GLIBC_2.14' not found] Error!

2.
 i can't install re2c in CentOs For Install zephir in this new machine to re compile it into this new machine,

How to i create zephir extension for CentOs 6.6 ?

**Comment by mahmoud-eskandari** [comment]
GLIBC_2.14 not published for CentOs 6.6!!!
And Exported zephir extension required it!
zephir not have active Forum , I have many Problems by it.

**Comment by steffengy** [comment]
## 1.

If you expect it to work that way you seem to have a fundamentally wrong understanding of what should work. If you want it to work on any linux, you need to ensure to either only use components of libc which are provided by the older libc versions (and therefore no linking against newer versions happens) or compile against an older libc version. This is a general issue of compiling portable binaries and not at all specific to zephir.

## 2. 

You can simply compile re2c for your linux distribution, or take the binary from an linux, where it was compiled using equal or lower libc features regarding versioning.

**Comment by mahmoud-eskandari** [comment]
OK!
So I compile zephir extension in Older Linux distribution, glibc<2.14 for older  Linux distribution,And compile it in new  Linux distribution For new machines!
I am able to install re2c but zephir Show many Errors:
install zephir. Install? And When i Send Y or y
...
**parser.c:8462: error: YYMINORTYPE has no member named yy383 parser.c:8462: error: YYMINORTYPE has no member named yy383 parser.c:8679: error: xxparserstatus has no member named scanner_state parser.c:8870: error: YYMINORTYPE has no member named yy383 parser.c:8870: error: YYMINORTYPE has no member named yy383 parser.c:8870: error: xx_parser_status has no 
...
