### ISSUE TITLE
output & exit are Undefined!

### ISSUE THREAD

**Issue by fanybook** [zephir-lang/zephir#1147]
my php version is php 7.0

[root@vultr license]# zephir build
zephir_parser extension not loaded, compiling it
Parser statistics: 127 terminals, 99 nonterminals, 459 rules
                   947 states, 0 parser table entries, 0 conflicts
PHP Notice:  Undefined variable: output in /zephir/Library/Compiler.php on line 237
PHP Notice:  Undefined variable: exit in /zephir/Library/Compiler.php on line 237
PHP Warning:  exec() has been disabled for security reasons in /zephir/Library/Compiler.php on line 237
Preparing for parser compilation...
PHP Notice:  Undefined variable: output in /zephir/Library/Compiler.php on line 239
PHP Notice:  Undefined variable: exit in /zephir/Library/Compiler.php on line 239
PHP Warning:  exec() has been disabled for security reasons in /zephir/Library/Compiler.php on line 239
PHP Warning:  exec() has been disabled for security reasons in /zephir/Library/Compiler.php on line 241
Compiling the parser...
PHP Notice:  Undefined variable: output in /zephir/Library/Compiler.php on line 246
PHP Notice:  Undefined variable: exit in /zephir/Library/Compiler.php on line 248
PHP Warning:  exec() has been disabled for security reasons in /zephir/Library/Compiler.php on line 248
PHP Warning:  file_get_contents(compile-errors.log): failed to open stream: No such file or directory in /zephir/Library/Compiler.php on line 249

PHP Warning:  file_get_contents(compile.log): failed to open stream: No such file or directory in /zephir/Library/Compiler.php on line 250

PHP Warning:  copy(modules/zephir_parser.so): failed to open stream: No such file or directory in /zephir/Library/Compiler.php on line 251
Zephir\Exception: The zephir parser extension could not be found or compiled!

**Comment by steffengy** [comment]
Not a zephir bug.
Zephir tries to execute shell commands,
which results in the output variables not being
set due to your php security settings.
Adjust them and it will work. (If you dont know how, google the warning about exec being disabled)
