### ISSUE TITLE
Definition of php function

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1149]
Just maybe here i will get some help faster(dont know if this is place for some questions too):

http://forum.zephir-lang.com/discussion/3468/check-a-definitionhow-many-arguments-of-what-type-etc-of-php-fun

**Comment by steffengy** [comment]
I do not quite totally understand your question.
Generally most stuff works like in PHP.

**Comment by Jurigag** [comment]
Yea i just figure it out i can just use ReflectionFunction
