### ISSUE TITLE
Can not find the json-c installer

### ISSUE THREAD

**Issue by zinovyev** [zephir-lang/zephir#1151]
I'm currently trying to install zephir compiler using the official guide (http://docs.zephir-lang.com/en/latest/install.html).
But I was a bit stuck at the step where the json-c module should be installed. The installer described in the manual is not at it's right place: `zsh: no such file or directory: ./install-json` (I'm currently in the zephir root directory).
So, maybe there's an error in the installation guide. Maybe the only way to get json-c lib installed is to install it manyally?)

**Comment by sergeyklay** [comment]
@zinovyev Hello

Zephir no longer depends on json-c.
- https://github.com/phalcon/zephir/pull/1144
- https://github.com/phalcon/zephir/pull/1141

**Comment by Green-Cat** [comment]
phalcon/zephir-docs#39

**Comment by zinovyev** [comment]
Thanks!
