### ISSUE TITLE
reference to the array

### ISSUE THREAD

**Issue by hah-a** [zephir-lang/zephir#1156]
Let's look at a simple example.

```
namespace ExtABC;

class ClassA
{
    public $abc;

    public function __construct()
    {
        let $this->abc = [1, 2, 3];
    }
}
```

```
namespace ExtABC;
use ExtABC\ClassA;

class ClassB
{
    protected $objectA;

    public function __construct()
    {
        let $this->objectA = new \ExtABC\ClassA();
        let $this->objectA->abc[0] = 4;
    }
}
```

I am just creating in the class ClassB an object of the class ClassA and I am reading from created object $objectA element of array $abc[0].

During compilation I get an error

```
Syntax error in extabc/classb on line 11

        let $this->objectA->abc[0] = 4;
--------------------------^
```

That is, before I read the element of array $abc I need to get a reference to the $objectA. But how to do that? Zephir has no references...

**Comment by steffengy** [comment]
duplicate #573
