### ISSUE TITLE
Use of undefined constant PHP_BINARY

### ISSUE THREAD

**Issue by ghost** [zephir-lang/zephir#1158]
$ cd /opt/zephir
$ git fetch
$ git merge origin/master
$ zephir version
0.9.1a-dev

$ cd /path/to/my/project
$ zephir generate

PHP Notice:  Use of undefined constant PHP_BINARY - assumed 'PHP_BINARY' in /opt/zephir/Library/Compiler.php on line 272
PHP_BINARY -dextension="/opt/zephir/Library/../parser/zephir_parser.so" /opt/zephir/compiler.php generate --parser-compiledsh: 1: PHP_BINARY: not found

**Comment by fezfez** [comment]
PHP_BINARY seem available since php 5.4, which version do you use ?

**Comment by ghost** [comment]
php 5.3 :'(

Btw, what last zephir version still compatible with php 5.3 ?

**Comment by Green-Cat** [comment]
php 5.3 has been EOL'd since august 2014 (over a year ago!).
It contains numerous bugs and security flaws, I would recommend upgrading regardless.
Even php 5.4 has been EOL'd as of this September, so it is really time to upgrade to 5.5 at least.
See http://php.net/supported-versions.php

**Comment by sergeyklay** [comment]
IMHO, best choice at this time it is 5.6

**Comment by ghost** [comment]
Well, I just try php 5.5. And generate my zephir code with version 0.8.0a.

But, my code can't compile for php 7.0.1. 

Zephir still not ready for php 7?

**Comment by steffengy** [comment]
PHP7 support is not complete yet, for best PHP7 support also it would be good to use the most recent development version(0.9.1a-dev which is essentially the master branch since it's not ready yet)
