### ISSUE TITLE
Optimisation

### ISSUE THREAD

**Issue by fezfez** [zephir-lang/zephir#1163]
Hi,
I made a little benchmark for comparing zephir/c/php by the following code.
## Zephir

``` zephir

namespace Toto;

class Aclass
{
    public function write() -> void
    {
        int time, i;
        var fp;
        string header;

        let time = 3000000;

        let fp = fopen("header.csv", "w+");
        let header = "fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez";

        for i in range(1, time) {
            fwrite(fp, header);
        }

    }
}
```

``` bash
time php -d extension=/usr/lib/php5/20131226/toto.so testzep.php 

real    0m5.788s
user    0m0.200s
sys 0m3.036s

```
## PHP

``` php
$time = 3000000;
$fp = fopen('header.csv', 'w+');
$header = 'fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez';

for ($i = 0; $i < $time; $i++) {
    fwrite($fp, $header);
}
```

``` bash
time php test.php

real    0m4.675s
user    0m0.468s
sys 0m3.288s

```
## C

``` c
#include <stdio.h>

main() {
   FILE *fp;
   int a;

   fp = fopen("test.txt", "w+");
   for( a = 1; a < 3000000; a = a + 1 ){
       fputs("fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez", fp);
   }
   fclose(fp);
}
```

``` bash
time ./test 

real    0m2.516s
user    0m0.008s
sys 0m0.316s
```

Zephir pretty bad ! But let's see the c code generated for the write method.

``` c
PHP_METHOD(Toto_Aclass, write) {

    zend_bool _2;
    zval *header;
    zval *fp = NULL, _0, _1;
    int time, i, ZEPHIR_LAST_CALL_STATUS, _3, _4;

    ZEPHIR_MM_GROW();

    time = 3000000;
    ZEPHIR_SINIT_VAR(_0);
    ZVAL_STRING(&_0, "header.csv", 0);
    ZEPHIR_SINIT_VAR(_1);
    ZVAL_STRING(&_1, "w+", 0);
    ZEPHIR_CALL_FUNCTION(&fp, "fopen", NULL, 1, &_0, &_1);
    zephir_check_call_status();
    ZEPHIR_INIT_VAR(header);
    ZVAL_STRING(header, "fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez,fzefze,fezfze,fzefze,fzefze,fezfez", 1);
    _4 = time;
    _3 = 1;
    _2 = 0;
    if (_3 <= _4) {
        while (1) {
            if (_2) {
                _3++;
                if (!(_3 <= _4)) {
                    break;
                }
            } else {
                _2 = 1;
            }
            i = _3;
            zephir_fwrite(NULL, fp, header TSRMLS_CC);
        }
    }
    ZEPHIR_MM_RESTORE();

}
```

Wtf is this loops ??? After replace the loops by 

``` c
    for( i = 1; i < 3000000; i = i + 1 ){
            zephir_fwrite(NULL, fp, header TSRMLS_CC);
    }
```

Recompile by hand and rebenchmark

``` bash
time php -d extension=/usr/lib/php5/20131226/toto.so testzep.php 

real    0m3.212s
user    0m0.208s
sys 0m2.968s

```

Is the zephir code optimized ? Or the generating code is very not optimized ?

PHP 5.6.4-4ubuntu6.2 (cli) (built: Jul  2 2015 15:29:28) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2014, by Zend Technologies
Zephir version 0.8.0a
##

**Comment by steffengy** [comment]
Zephir itself doesn't really optimize generated code.

The for loops there should be optimized by GCC though 
(except in debug builds where -O3 is not specified).
The code generation there could still be subject to optimizations
in the future, if somebody gets to implement it.

**Comment by fezfez** [comment]
So how to optimize with gcc ? (i'm not a c programmer...)

**Comment by steffengy** [comment]
you could just edit Compiler.php and replace `-O2` with `-O3` at https://github.com/phalcon/zephir/blob/b335770d414aaee3a7b8a214d2b0c9041e731399/Library/Compiler.php#L736
and see if that helps. (Also make sure to use `zephir build` so that these flags are used)
If not, then zephir produces code GCC cannot optimize...

**Comment by fezfez** [comment]
With 03 option

``` bash
time php -d extension=/usr/lib/php5/20131226/toto.so testzep.php 

real    0m5.549s
user    0m0.140s
sys 0m3.040s
```

With 0s option

``` bash
time php -d extension=/usr/lib/php5/20131226/toto.so testzep.php 

real    0m4.199s
user    0m0.136s
sys 0m3.064s
```

Apparently, even with flag optimisation, it's better to write optimized code.

**Comment by fezfez** [comment]
It will be great if we can unit test this method https://github.com/phalcon/zephir/blob/b335770d414aaee3a7b8a214d2b0c9041e731399/Library/Statements/ForStatement.php

Can we translate a piece of zephir code into $statement ?

**Comment by flip111** [comment]
@fezfez it's tough to figure out why the ForStatement class was written in this way. I mean why not use `for` like you suggested instead of [`while`](https://github.com/phalcon/zephir/blob/b335770d414aaee3a7b8a214d2b0c9041e731399/Library/Statements/ForStatement.php#L196). So i think any optimization of this code needs first understanding of why it was written in such a way.

It would also be nice to compare assembly output of both solutions that way we can know what is the computational load on the cpu after gcc has done it's optimizations.

**Comment by steffengy** [comment]
it's not really tough to figure out, it is  just easier in terms of code generation.

The performance problem also does not really require looking at assembly,
as you can see additional temp variables are used which results in a higher
amount of assignment operations, which GCC for some reason doesn't optimize.

**Comment by sergeyklay** [comment]
So we have Phalcon Beanstalk component that usually slower than native  PHP
