### ISSUE TITLE
custom optimizers

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1169]
The documentation on http://docs.zephir-lang.com/en/latest/optimizers.html doesn't explain how to call the created zephir function. I assumed taking the hello world and modifying it a bit

```
namespace Test;

/**
 * This is a sample class
 */
class Hello
{
    /**
     * This is a sample method
     */
    public function test()
    {
        echo calculate_pi(10);
    }
}
```

would be sufficient. But this gives an error:

```
Zephir\CompilerException: Calculated PI values only can be stored in double variables in /home/flip101/zep/test/test/hello.zep on line 13

            echo calculate_pi(1);
    ----------------------------^
```

**Comment by steffengy** [comment]
> The documentation on http://docs.zephir-lang.com/en/latest/optimizers.html doesn't explain how to call the created zephir function.

It actually does `An ‘optimizer’ works like an interceptor for function calls.`.

In your case it just doesn't work because you're using an echo, which creates a temporary
ZVAL, while `calculate_pi` expects a double variable as a return value.

Also:
even the error message `Calculated PI values only can be stored...` can be
found on the documentation page.

Still, this is an area which requires a bit more than basic knowledge of zephirs internals,
and is subject to changes in the future.

**Comment by flip111** [comment]
> It actually does An ‘optimizer’ works like an interceptor for function calls..

Yes it's an interceptor, but the documentation doesn't show the actual function call which is then intercepted.

Looking at your answer i would guess you have to store it in a double. Then looking at the documentation for doubles, i see i should use `var number = 5.0;` so i tried this, but then i couldn't assign the result of `calculate_pi` to `number`

**Comment by steffengy** [comment]
Of course it does:

> Implementation of optimizers highly depends on the kind of code you want to generate. In our example, we’re going to replace the call to this function by a call to a c-function. In Zephir, the code used to call this function is:
> let pi = calculate_pi(1000);

`double pi = calculate_pi(1000);` might work

**Comment by flip111** [comment]
ah yes you're right, i missed that piece

**Comment by flip111** [comment]
I tried

```
var pi;
let pi = calculate_pi(1000);
echo pi;
```

which outputs `1`

and

```
double pi = calculate_pi(1000);
echo pi;
```

which output `2063507712.000000`

and

```
double pi;
let pi = calculate_pi(1000);
echo pi;
```

which output `-1348910848.000000`

and my c code is:

```
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#include "php.h"
#include "php_ext.h"

double my_calculate_pi(zval *accuracy) {
    return 0.0;
}
```

so it doesn't seem to be functioning properly

When i put this

```
echo calculate_pi(1);
```

it works. I noticed in the last case `zend_print_zval` is used and in other cases `php_printf("%f", something-here);` is used

**Comment by flip111** [comment]
I think these errors occurred because i didn't properly set the return type of the C function
