### ISSUE TITLE
PregMatchOptimizer crashes when register variable was not declared

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1171]
Given

```
if !(preg_match("some regex here", subjectString, regs)) {
```

when `regs` was not declared before. This will return false

https://github.com/phalcon/zephir/blob/master/Library/Optimizers/FunctionCall/PregMatchOptimizer.php#L60

and then it crashes on the next line when doing a method call on a boolean.

**Comment by hylent** [comment]
See #1172

**Comment by flip111** [comment]
Issue #1172 is about that preg_match is allowed (by the entire compiler) to produce code that segfaults. This issue is about the problem in the PregMatchOptimizer. If (and i don't know if this is so or not) Optimizers and responsible for the resulting code (without security by another part of the compiler) then these issues can be merged.

**Comment by flip111** [comment]
Why was this closed?
