### ISSUE TITLE
segmentation fault while lexing

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1178]
I would consider this issue low priority, but i'm reporting it just to keep a record. When i have zephir code `public®static` it segfaults.

Also i would like to notify that there is no whitespace requirement after keywords. "public" is recognized as a token if it isn't followed by `[a-zA-Z_\\]`, otherwise it's part of another token. Possibly one of these https://github.com/phalcon/zephir/blob/f78e01d3a5d4e988fd30efe269d432ef635a56c1/parser/parser/scanner.re#L486-L665 When public is matched and then immediately a new token starts (without whitespace) it likely syntax error later by the parser.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#30
