### ISSUE TITLE
Possibly out of bound risk in scanner

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1185]
I'm not sure about this issue (insufficient knowledge), however i didn't find any specific protection against a possible out of bounds bug. (which would lead to undefined behavior).

I suspect that when loading the program code into the parser here
https://github.com/phalcon/zephir/blob/c9735cc7ceb1e80908165c3eded57206f5a7319e/parser/zephir_parser.c#L34-L48

no null-byte was added (as it shouldn't by PHP strings).

But then later, how does the parser know it has reached the end of the string? Traditionally with C bytes to check for a null-byte like this https://github.com/phalcon/zephir/blob/master/parser/parser/scanner.re#L968-L971

However if this null-byte is not present then there will be memory access on other parts of the program.

The string length is being recalculated after every token https://github.com/phalcon/zephir/blob/master/parser/parser/base.c#L174 and then checked by the parser. So it can only go wrong when lexing a token like "function" and then in my program i would just take part of this token and place it at the end of the file "func". (if it was placed earlier in the file then it would still be relatively safe to access memory after this point)

**Comment by steffengy** [comment]
Actually every string in PHP is null terminated: https://github.com/php/php-src/blob/563659822de1e22d835df94e13cc66a34e7261b2/Zend/zend_string.h#L160

The scanner should be relatively safe, the parser is anything but memory safe though
(although I'm only aware of memory leaks, I wouldn't say it's safe), which fortunately
isn't a very big problem.

**Comment by flip111** [comment]
Ok worries for nothing ^^
