### ISSUE TITLE
Link with precompiled object file

### ISSUE THREAD

**Issue by flip111** [zephir-lang/zephir#1188]
At the moment there is no facility to link with an object file (i'm not talking about a library that stays somewhere else on the system). I found it was possible to add this functionality to LDFLAGS in this file https://github.com/phalcon/zephir/blob/master/templates/ZendEngine2/config.m4  Would it be ok to add a PR for this?
##

**Comment by steffengy** [comment]
Does using something like `LDFLAGS=<CONTENT> zephir build` not work?

**Comment by flip111** [comment]
Unfortunately not `php: symbol lookup error: /usr/local/lib/php/extensions/no-debug-non-zts-20131226/ext.so: undefined symbol: ParseAlloc`

**Comment by steffengy** [comment]
is ParseAlloc something from the library you want to use, I guess yes?

**Comment by flip111** [comment]
yes

**Comment by andresgutierrez** [comment]
You have to compile the file along the extension: https://github.com/phalcon/cphalcon/blob/master/config.json#L26-L37

**Comment by flip111** [comment]
@andresgutierrez i don't understand your comment. What do you mean "alongside the extension"? The source files? The objects files? The .so file?

The link you provide shows a list of source files, how is that related to linking with an object file??

This issue is still relevant to me.

**Comment by andresgutierrez** [comment]
Phalcon has plain C files that are compiled alongside regular zephir files. You can add those files as the example in the link.

**Comment by flip111** [comment]
At the moment i want a lot of control over the compiler flags i'm setting:

``` sh
gcc \
    -fPIC \
    -g3 \
    -c \
    -Wall\
    -Werror \
    -Wextra \
    -pedantic \
    -Wno-unused-but-set-variable \
    -Wno-unused-variable \
    -Wno-unused-parameter \
    -Wno-implicit-function-declaration \
    -std=c11 parser.c $(php-config --includes | sed 's/-I/-isystem /g')
```

Later i was planning to use zephir to call into some Rust code (with C ABI). So the plain C files is really not a solution.

By the way ... i've read that instead of `LDFLAGS` it's better to use `LDLIBS` but i haven't tried that yet.
