### ISSUE TITLE
[php7 + phalcon] problem

### ISSUE THREAD

**Issue by Izopi4a** [zephir-lang/zephir#1191]
Hey,

when I compile my own extension ( that extends some Phalcon components ) with php7 i have an issue, i wonder if someone can help me find what is it ... compile is fine but when i enable the extension if I type `php -v` in terminal i get

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php-7001/lib/php/extensions/no-debug-non-zts-20151012/xxxxxx.so' - /opt/php-7001/lib/php/extensions/no-debug-non-zts-20151012/xxxxx.so: undefined symbol: phalcon_exception_ce in Unknown on line 0
```

i probably have to put this issue in phalcon repo but i am not sure, sorry if this is the wrong place :P

edit: i have latest zephir and latest 2.1.x branch from phalcon

**Comment by Izopi4a** [comment]
also when i removed Phalcon\Exception from my code this poped up

```
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/php-7004/lib/php/extensions/no-debug-non-zts-20151012/xxx.so' - /opt/php-7004/lib/php/extensions/no-debug-non-zts-20151012/xxx.so: undefined symbol: phalcon_validation_validator_presenceof_ce in Unknown on line 0
PHP 7.0.4 (cli) (built: Mar  8 2016 10:14:21) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies

```

**Comment by mruz** [comment]
How about load order? https://github.com/phalcon/cphalcon/issues/2224

**Comment by Izopi4a** [comment]
;extension=/opt/php-7001/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
extension=/opt/php-7004/lib/php/extensions/no-debug-non-zts-20151012/phalcon.so
extension=/opt/php-7001/lib/php/extensions/no-debug-non-zts-20151012/apcu.so
;extension=/opt/php-7001/lib/php/extensions/no-debug-non-zts-20151012/zephir_parser.so
extension=/opt/php-7004/lib/php/extensions/no-debug-non-zts-20151012/xxx.so

`php -m`

root@server1:/home/izopi4a/phalcon/ext (2.1.x)$> php -m
[PHP Modules]
apcu
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
hash
iconv
intl
json
libxml
mbstring
mcrypt
mysqli
mysqlnd
openssl
pcre
PDO
pdo_mysql
pdo_sqlite
phalcon
Phar
posix
Reflection
session
SimpleXML
sockets
SPL
sqlite3
standard
tidy
tokenizer
xml
xmlreader
xmlwriter
zip

[Zend Modules]

xxx is not present.

As far as I understood you mean i need to load phalcon first and then my extension right ?

**Comment by mruz** [comment]
Yes, but maybe it isn't a reason.

**Comment by Izopi4a** [comment]
i will try with a blank app in 1 hour and update the issue, since its not clear at the moment

**Comment by Izopi4a** [comment]
strangely enough if i create a Test app with Hello.zep

```
namespace Test;

/**
 * This is a sample class
 */
class Hello extends \Phalcon\Mvc\Model {
    /**
     * This is a sample method
     */
    static public function say()
    {
        echo "Hello World!";

        throw new \Phalcon\Exception();
    }
}
```

without even adding anything to the config file it works perfect, i will take a close look tomorrow cuz i dont have enough time atm. and will update you.

**Comment by Izopi4a** [comment]
so yea...

if I remove this from my config everything works like a charm for me .... for whatever reason...

```
"external-dependencies": {
        "phalcon": "/home/izopi4a/phalcon",
 }

```
