### ISSUE TITLE
possibilities to decompile php extension

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1193]
I want to write simple php extension and protect the source code is it possible to sign it with some sort of key ?
how hard is get source code from compiled extension .so or .dll ?

**Comment by steffengy** [comment]
It's a little easier than trying to decompile C, where it's impossible to get the original source code.

It's still possible to determine some function or method calls, string literals, call graphs etc.
Zephir doesn't really provide anything to help you in that regards.

TLDR: Making reverse engineering or cracking impossible is always impossible with enough effort put in. Relying on security through obscurity is never a good idea. If you have to protect something, it's generally advisable to do that with licensing, wherever possible.
