### ISSUE TITLE
Hi~Guys zephir Can Can write a function?

### ISSUE THREAD

**Issue by yty9898** [zephir-lang/zephir#1195]
`function sum(int !a=0,int !b = 0) ->int
{
    return a + b;
}`

sum(1,2); //3

**Comment by sergeyklay** [comment]
Could you please explain a bit more?

**Comment by yty9898** [comment]
I'm Chinese,  I want to use function instead of use class

**Comment by sergeyklay** [comment]
Nope :) Only classes I guess

**Comment by steffengy** [comment]
actually you can write functions for quite a while: https://github.com/phalcon/zephir/pull/762

https://github.com/phalcon/zephir/blob/master/test/fcall.zep#L7

**Comment by sergeyklay** [comment]
Oh!
