### ISSUE TITLE
Compile runtime errors

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1204]
Does compiling runtime working ? I installed llvm-3.6 but if i try compiling zephir runtime then i got errors:

http://pastebin.com/PnCUrRXG

Or maybe its not working yet ?

**Comment by Jurigag** [comment]
On php7 i have errors too.

**Comment by Izopi4a** [comment]
first go to zehpir/praser dir 

```
make clean
phpize --clean
```

also make sure it is not loaded in your php.ini

**Comment by Jurigag** [comment]
Well not working :x To be sure i mean zephir/runtime. To have zephir working as JIT runtime.

**Comment by Izopi4a** [comment]
oh its a different thing, soz

**Comment by steffengy** [comment]
runtime is at a very experimental stage and nowhere near usable.

**Comment by Jurigag** [comment]
Closing for now, hope in some day we will get it working. Also are you still gonna work on it if php will release JIT ? I guess then there will be almost no point creating runtime/JIT(i don't know if they are the same) for zephir ?
