### ISSUE TITLE
[ask] Is Zephir Linux Standard Base?

### ISSUE THREAD

**Issue by oknoorap** [zephir-lang/zephir#1206]
I want to compiles zephir in centos and ubuntu, two different distros. Do I must compile twice in different distro or not?

**Comment by steffengy** [comment]
That depends on a few things.
As long as PHP's dependencies and an older or more recent version version of libc
runs on the target system, you'll be fine.

There isn't really anything specific to binary compatibility for zephir,
as it literally just "extends" some PHP code, so the same things that apply
to PHP apply to ZEPHIR in terms of binary portability.
