### ISSUE TITLE
SplObjectStorage array access

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1208]
Currently, zephir for working with SplObjectStorage returns Illegal offset type(cuz he expects string/int etc types, not object). Any plans about implementing objects ? Or maybe just offsetGet/offsetSet should work ?

**Comment by dreamsxin** [comment]
Related

https://github.com/phalcon/zephir/issues/1818
https://github.com/phalcon/zephir/issues/1400

**Comment by sergeyklay** [comment]
I'm closing this issue but if I have made an oversight, please do get back in touch. Thank you for the report @Jurigag
