### ISSUE TITLE
[NFR]String curly syntax

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1209]
Hello. I have such an error when building zephir extension:

Scanner error: -2 {type}/{line}/{file}
Segmentation fault (core dumped)

There is which instruction causing a problem from gdb:
http://pastebin.com/Qe02jY8J

And there stacktrace:
http://pastebin.com/XCJaymGH
##

**Comment by Jurigag** [comment]
Well zephir is not support string templates from php.

http://php.net/manual/en/language.types.string.php#language.types.string.parsing.complex

**Comment by steffengy** [comment]
I'm not sure if we want to support this, I personally do not think it's necessary.
The segmentation fault in the parser is something we should eventually address though.
