### ISSUE TITLE
[NFR]Constants as array key

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1210]
Currently compiler throw Syntax error if key in array is constant like self::SOMETHING.

**Comment by sergeyklay** [comment]
The Zephir language syntax is similar to PHP but it is not equal to PHP. This means for example that not all things from PHP will also work well in Zephir

**Comment by Jurigag** [comment]
@sergeyklay yea i know but:
ClassName::SOMETHING it's working as array key. Cant compiler figure out in which class is self called ?

**Comment by sergeyklay** [comment]
I think this is related to:
https://github.com/phalcon/zephir/issues/988
https://github.com/phalcon/zephir/issues/1119

And yes, you need to use `static` instead `self`
