### ISSUE TITLE
SplFileObject The parent constructor was not called

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1212]
When creating new `SplFileObject` in `Zephir` with path to some php file `LogicException` is thrown with message The parent constructor was not called.

**Comment by dreamsxin** [comment]
At PHP-5.5.38 test not happen, checks whether it has been fix?
```zep
static protected function testMethodStatic()
{
       var file;
       let file = new \SplFileObject("test.php");
       return "hello Scall";
}
```

**Comment by sergeyklay** [comment]
@Jurigag

**Comment by Jurigag** [comment]
Well. I will check when having a time. I think i checked it on php 5.6
