### ISSUE TITLE
memstr is causing seg faults on php 7

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1216]
There is more about it there:

https://github.com/phalcon/cphalcon/pull/11279#issuecomment-198158182

Also not sure about other seg faults mentioned there what causing them but let focus on this now

Exactly this line is producing a problem:

https://github.com/phalcon/cphalcon/blob/master/phalcon/logger/formatter/line.zep#L81

There is stack:

http://pastebin.com/keUR6Wtv

Well im guessing it's memstr. I commented this if and it's working fine, but maybe it's something else inside if causing a problem.

**Currently not sure there is an issue, beacause i installed everything from zero and don't have this seg fault.**

**Comment by sergeyklay** [comment]
``` zephir
    public function test1()
    {
        var format;

        let format = "some string";

        return memstr(format, "some");
    }

    public function test2()
    {
        var format;

        let format = "some string";

        return memstr(format, "another");
    }
```

``` php
var_dump($test->test1()); // true
var_dump($test->test2()); // false
```

```
$ php --version
PHP 7.0.5-3+donate.sury.org~trusty+1 (cli) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ zephir version
0.9.2a-dev
```
