### ISSUE TITLE
PHP 7 typeof in if not working for variables from php(working for zephir variables though) ?

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1217]
In phalcon code like this:

```
use Phalcon\Mvc\View;
use Phalcon\Mvc\View\Engine\Volt;

$di = new \Phalcon\Di\FactoryDefault();

$di->set('view',function(){
    $view=new \Phalcon\Mvc\View\Simple;
    $view->registerEngines([
        '.volt'=>function ($view, $di) {
            $volt = new Volt($view, $di);
            $volt->setOptions(array(
                'compiledPath' => __DIR__.'/cache/',
                'compileAlways' => true
            ));
            return $volt;
        }
    ]);
    return $view;
});
/** @var \Phalcon\Mvc\View\Simple $view */
$view = $di->get('view');
```

And in zephir this line https://github.com/phalcon/cphalcon/blob/2.1.x/phalcon/mvc/view/engine/volt/compiler.zep#L2407 is returning true and thorwing Exception.

I added var_dump before this if with:

```
var_dump(compileAlways);
var_dump(typeof compileAlways);
```

And they return:
`bool(true) string(7) "boolean"`

What's going on ?

I guess that's beacause compileAlways is defined as var, not bool ?

After changing compileAlways to bool and casting value of options["compileAlways"] to bool it works fine. So now there is question - should zephir change something or phalcon change all var variables to proper type ? @sergeyklay @andresgutierrez

Also what's imporant even after this change those var_dumps return the same:
`bool(true) string(7) "boolean"`

**Comment by kastnermario** [comment]
Same problem here. How to fix this issue? Zephir is the latest available. Phalcon is build with the 2.1.x branch.

**Comment by Jurigag** [comment]
It needs to be fixed somewhere in C i guess ? I just reported the issue. Don't know how to fix it. I would do PR if i knew.

**Comment by ulfims** [comment]
On File: phalcon/mvc/view/engine/volt/compiler.zep, line: 2407:

```
                                if typeof compileAlways != "boolean" {
                                        throw new Exception("'compileAlways' must be a bool value");
                                }
```

Should be:

```
                               if  (typeof compileAlways)  != "boolean" {
                                        throw new Exception("'compileAlways' must be a bool value");
                                }
```

**Comment by Jurigag** [comment]
@ulfims you checked it ? Is it fixing an issue ?

Still for me it's a bug, it's working fine on php 5.x

**Comment by ulfims** [comment]
I've checked and compiled on:

```
Ubuntu 15.10 64-bit
php 7 version: PHP Version 7.0.4-7+deb.sury.org~wily+2
Zephir: Zephir version 0.9.2a-dev
```

**Comment by Jurigag** [comment]
And it's not throwing exception ?

Still it's bug and issue. Better to fix this in zephir than changing it everywhere.

**Comment by ulfims** [comment]
@Jurigag Agree with you. since more syntax similar with this issue.

But  my question:
Why its work on **Phalcon branch master** on **php 5.6**  with original code (without my correction) and same zephir version:?

**Comment by Jurigag** [comment]
Beacause it just works how it should be. Zephir as i know was developed in way that you don't need to put unnecessary brackets in if conditions for example. I guess maybe php itself changed something, i don't know.

**Comment by ulfims** [comment]
maybe. Don't know  too

**Comment by ulfims** [comment]
@Jurigag  I try to make a simple code:

```

                var dataBoolean=true;
                if typeof dataBoolean != "boolean" {
                        echo "Not Boolean";
                }else{
                        echo "Boolean";
                }

```

it works perfect using PHP7
Strange

**Comment by Jurigag** [comment]
@ulfims 
I guess it's not working beacause compileAlways is passed from php.

**Comment by ulfims** [comment]
@Jurigag 
I mad a simple class on zephir:

```
namespace Coba;

class Data{
        public function setOptions(array options)
        {

                var dataBoolean;
                let dataBoolean=options["compileAlways"];
                return  typeof dataBoolean == "boolean" ;
        }
}
```

The class called from PHP:

```
<?php
$data=new Coba\Data();
if($data->setOptions(["compileAlways"=> true])){
        echo "Boolean";
}
else{
        echo "Not Boolean";
}

```

The result: "Boolean";
Any idea?

**Comment by ulfims** [comment]
@Jurigag I think its bug on Zephir.
I mad two code with expected result should same, but failed on checking like in phalcon script.
Script 1:
**Result: Ok**

```
namespace Coba;

class Data{
        public function setOptions(array options)
        {

                var dataBoolean;
                let dataBoolean=options["compileAlways"];
                echo "Coba"; 
                if  typeof dataBoolean == "boolean" {
                        return true;
                }
                else {
                        return false;
                }
        }
}
```

Script 2:
**Result: Not Ok**

```
namespace Coba;

class Data{
        public function setOptions(array options)
        {

                var dataBoolean;
                let dataBoolean=options["compileAlways"];
                echo "Coba1";
                if  typeof dataBoolean != "boolean" {
                        return false;
                }
                else {
                        return true;
                }
        }
}

```

PHP Script:

```
<?php
$data=new Coba\Data();
if($data->setOptions(["compileAlways"=> true])){
        echo "Boolean";
}
else{
        echo "Not Boolean";

```

With same PHP file, the result on Zephir class is different. 
I think Zephir has problem with checking command:

```
if typeof variable != "boolean" {
}
```

But its ok on: 

```
if typeof variable == "boolean" {
}

```

**Comment by Jurigag** [comment]
Also as i wrote if you change type of dataBoolean to bool and cast type of options["compileAlways"] to bool in zephir it's working fine.
