### ISSUE TITLE
Interface/class names conflict, can't use the same name if it exists in current class

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1221]
For example we have namespaces like:

```
Phalcon\Firwall
```

Here we have:
Adapter and AdapterInterface

```
Phalcon\Firewall\Adapter
```

Here we have Annotations which extends 

```
Phalcon\Firewall\Adapter
```

I wanted in use `Phalcon\Annotations\AdapterInterface` type in `Phalcon\Firewall\Adapter\Annotations` constructor but here is no way of doing it. I guess there are some name conflicts. Also i tried with as but it's not working, zephir is just writing:

```
Zephir\CompilerException: Unknown type AdapterInterface in /root/2.1.x-firewall/cphalcon/phalcon/firewall/adapter/annotations.zep on
 line 42 public function __construct(<AdapterInterface> annotationsAdapter)
```

**Comment by andresgutierrez** [comment]
Try adding `use Phalcon\Firewall\AdapterInterface;` to the top of the file

**Comment by Jurigag** [comment]
I already had it. `Phalcon\Firewall\AdapterInterface` is interface which `Phalcon\Firewall\Adapter` implements. And somewhere in code i want type hint `Phalcon\Annotations\AdapterInterface` but zephir don't let me do it any way.
