### ISSUE TITLE
Checking with if typeof variable != "boolean" not working properly on PHP7

### ISSUE THREAD

**Issue by ulfims** [zephir-lang/zephir#1223]
I found bug on Phalcon branch 2.1.x and I think it is related with zephir.
Environment:

```
Ubuntu 15.10 64-bit
php 7 version: PHP Version 7.0.4-7+deb.sury.org~wily+2
Zephir: Zephir version 0.9.2a-dev

```

Note: Working find on PHP 5.6

[Phalcon Issue 1217](https://github.com/phalcon/zephir/issues/1217)
I think Zephir has **problem** with checking command:

```
if typeof variable != "boolean" {
}
```

But its **ok** on:

```
if typeof variable == "boolean" {
}
```

Sample script available on phalcon issue. I copy as below:
I mad two code with expected result should same, but failed on checking like in phalcon script.
Script 1:
**Result: Ok**

```
namespace Coba;

class Data{
        public function setOptions(array options)
        {

                var dataBoolean;
                let dataBoolean=options["compileAlways"];
                echo "Coba"; 
                if  typeof dataBoolean == "boolean" {
                        return true;
                }
                else {
                        return false;
                }
        }
}
```

Script 2:
**Result: Not Ok**

```
namespace Coba;

class Data{
        public function setOptions(array options)
        {

                var dataBoolean;
                let dataBoolean=options["compileAlways"];
                echo "Coba1";
                if  typeof dataBoolean != "boolean" {
                        return false;
                }
                else {
                        return true;
                }
        }
}

```

PHP Script:

```
<?php
$data=new Coba\Data();
if($data->setOptions(["compileAlways"=> true])){
        echo "Boolean";
}
else{
        echo "Not Boolean";

```

With same PHP file, the result on Zephir class is different.

**Comment by Jurigag** [comment]
It's pretty much the same issue i reported. It's similar, i think one issue is enough, there are definitely some problems with typeof.

**Comment by steffengy** [comment]
@ulfims Thanks, good summary of the issue, was able to trace this down within minutes :)
Also thanks to everyone else reporting this.
