### ISSUE TITLE
PHP7/OS X

### ISSUE THREAD

**Issue by Fenikkusu** [zephir-lang/zephir#1226]
I seem to be having trouble getting zephir to work correctly on OS X with PHP7. I'm running into the following issues:

Zephir\ParseException: Syntax error in phalcon/cphalcon/phalcon/paginator/adapter/querybuilder.zep on line 168

```
      var groups = totalBuilder->getGroupBy();
```

I can get around this by commenting out the code. After that, I get this error:

Class 'Memcached' does not implement method: 'getServerList' in  phalcon/cphalcon/phalcon/cache/backend/libmemcached.zep on line 111

I can only presume this is due to a version issue of the stock memcached, even though it is using PHP7. Does anyone have any thoughts on this? I may end up having to create a port for memcached/7 as it doesn't appear to exist currently.

**Comment by andresgutierrez** [comment]
Make sure you have 0.9.2a installed

**Comment by Fenikkusu** [comment]
I was on the development branch, so that was part of the issue. Went back to master and the version is registering correctly. However, PHP is failing with 'unable to load library...Symbol not found: _zval_used_for_init'

**Comment by Fenikkusu** [comment]
May of figured out what is going on. I sym linked the /usr/bin/php to PHP 7. I didn't do the same for the php-config and phpize apps, so they are still 5.4 it looks like. Will fix that and then try again.

**Comment by Fenikkusu** [comment]
Resolved/Closing. I used macports to install php 7. This didn't update the phpize/php-config software, so I tried http://php-osx.liip.ch/ to upgrade php instead. This also upgraded the phpize correctly. After that, I added the new php7 install to $PATH and it ran correctly.
