### ISSUE TITLE
Closure inclusion issues with error Class does not exist at compile time

### ISSUE THREAD

**Issue by ganeshkbhat** [zephir-lang/zephir#1228]
I am trying to use callbacks but get an error when I define the callback with a invoke class.

```
Warning: Class "Arrays\blankCb" does not exist at compile time in C:\php2z\converted\Arrays\arrays\arrays.zep on 38 [nonexistent-class]

                    let checks =  new blankCb();
        ---------------------------------------^

```

```
Warning: Class "Arrays\Arrayscall_mapClosureOne" does not exist at compile time in C:\php2z\converted\Arrays\arrays\arrays.zep on 47 [nonexistent-class]

                let checks =  new Arrayscall_mapClosureOne();
        ----------------------------------------------------^
```

`blankCb` is a very simple call back. File attached. I have to get round it by manual implementation of the callbacks. I am using PHP 7.0.4, Win10, X64, Apache 2.4

Any help is welcome.

**Comment by sergeyklay** [comment]
Could you please provide script to reproduce?

**Comment by ganeshkbhat** [comment]
I have attached the .zep files and the php used to convert. I am using php-zephir but this is a simple code that should do fine. It uses invoke php method during conversion of callbacks. Please check the zip. When I do the build following is the message I get. I have attached the generated config.json as well. 

You can skip the compiling error, I am able to compile the extension. I am able to compile manually with my build environment for PHP. But it does not work with the callback (Cb specified within the file). I have to manually give the Cb reference from external by using manual paths to callbacks in extension say for example 'Arrays\arrays::anyCb' in this case.

```
C:\php2z\converted\Arrays>zephir build
Warning: Class "Arrays\Arrayscall_skipClosureOne" does not exist at compile time in C:\php2z\converted\Arrays\arrays\arrays.zep on 37 [nonexistent-class]

                    let checks =  new Arrayscall_skipClosureOne();
        ---------------------------------------------------------^


Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installation is not implemented for windows yet! Aborting!
```

[arrays.zip](https://github.com/phalcon/zephir/files/201629/arrays.zip)

[arrays-PHP.zip](https://github.com/phalcon/zephir/files/201631/arrays-PHP.zip)

**Comment by Jurigag** [comment]
Closuers in php-zephir don't work good. You better wrote themself. As you see in in arrays.zep you have:

`Arrayscall_skipClosureOne`

But php-zephir generated `Arrayscall_skipClosureZero`

Also most of the times php-zephir generate wrong `__invoke` methods with wrong body of method. In this case it looks fine.

**Comment by ganeshkbhat** [comment]
I tried. The only option was create a callback function within the Arrays class. But again, I am not able to reference it within the class in a pre-written function. I have to reference the callback or pass it manually as callable function name string in PHP and does not work in Zephir or extension. Thats the reason for the issue. Its not PHP-Zephir but Zephir compilation.

**Comment by Jurigag** [comment]
What you mean ? Just change Arrayscall_skipClosureOne to Arrayscall_skipClosureZero and it should work.

What error you have after changing it ?

**Comment by ganeshkbhat** [comment]
Same error. Arrayscall_skipClosureOne or Arrayscall_skipClosureZero does not work. The sample I uploaded has Arrayscall_skipClosureZero anyways. I stopped using an inbuilt callback definition and created a seperate functionCb within Arrays to reference. And even that does not work. Compiles the extension with the same error. Other functions not using these definitions work.

**Comment by Jurigag** [comment]
Yes you uploaded Arrayscall_skipClosureZero but in arrays.zep you have:

`let checks =  new Arrayscall_skipClosureOne();`

That's why there is error, try to changing `Arrayscall_skipClosureOne` to `Arrayscall_skipClosureZero` and do zephir fullclean and zephir build.

**Comment by ganeshkbhat** [comment]
`php-zephir generate wrong __invoke methods with wrong body of method` True. Yeeeeah...worked now. Did not notice that. Thanks for pointing out. I though I am loosing out on callbacks which I have loads to come.

**Comment by Jurigag** [comment]
Next time try to use https://forum.zephir-lang.com/

**Comment by ganeshkbhat** [comment]
Sure thanks.
