### ISSUE TITLE
API Documentation: Incorrect Namespace on type hinted return.

### ISSUE THREAD

**Issue by ottodashadow** [zephir-lang/zephir#1229]
If I define the following class in Zephir with my Json class as the return type hint the **zephir stubs** command calculates the correct namespace for the class, but the **zephir api** documentation call seems to ignore the use statement.
#### Origin /library/api/client/apiresponse.zep file:

``` zephir
namespace Library\API\Client;

use Library\Types\Json;

class APIResponse extends Json {
    ...
    public function getData() -> <Json> {
        return new Json(this->get("data"));
    }
    ...
}
```
#### PHP Stub Code "zephir stubs"

``` php
<?php
namespace Library\API\Client;

class APIResponse extends \Library\Types\Json
{
    /**
     * @return \Library\Types\Json
     */
    public function getData() {}
}
```
#### API Documentation Methods
- __construct(variable $responseJson)  :  void
- getData()  :  **Library\API\Client\Json**

**Comment by sergeyklay** [comment]
Fixed in the `docs` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
