### ISSUE TITLE
zephir can package function ?

### ISSUE THREAD

**Issue by yty9898** [zephir-lang/zephir#1242]
`<?php
function p($arr)
{

}`

**Comment by surjit** [comment]
```
ZEND_FUNCTION(p)
{
  zval* arr;

  if (zend_parse_parameters(ZEND_NUM_ARGS() TSRMLS_CC, "z", &arr) == FAILURE)
    return;

 zend_print_zval(arr, 0);
}
```

if you expecting array return then read this
http://docstore.mik.ua/orelly/webprog/php/ch14_08.htm

it nicely explain, how to do so

**Comment by steffengy** [comment]
@surjit 
your answer isn't really specific to zephir and may not answer the question entirely.
If I understand correctly, which is really difficult with that lack of details,
he simply wants to use zephir to declare a function which

It should be self-explanatory on how to define a function
[globally](https://github.com/phalcon/zephir/blob/e904aba279e139f4954def75cff2bfc5db19bcd0/test/fcall.zep#l7) or [within a namespace](https://github.com/phalcon/zephir/blob/e904aba279e139f4954def75cff2bfc5db19bcd0/test/fcall.zep#l18).
