### ISSUE TITLE
The "get_object_vars" is not returning the protected/private properties (0.9.2a-dev)

### ISSUE THREAD

**Issue by xEsk** [zephir-lang/zephir#1245]
I'm porting a private PHP library to Zephir and almost everything is working, except a small piece of code which uses the function **get_object_vars** to get all the properties of an object (is a special cloning method).

The problem is that **get_object_vars** is not returning the protected/private properties of an object.

I made a test case, using the same class logic in PHP and Zephir and the result is not the same.

**PHP - 5.4.34**

```php
namespace Foundation;

class Test
{
    public    $a = 1;
    protected $b = 2;
    private   $c = 3;

    public function run()
    {
        var_dump(get_object_vars($this));
    }
}
```

**Result:**

```
array(3) {
  'a' =>  int(1)
  'b' =>  int(2)
  'c' =>  int(3)
}
```

---

**Zephir - 0.9.2a-dev**

```zep
namespace Foundation;

class Test
{
    public    a = 1;
    protected b = 2;
    private   c = 3;

    public function run() -> void
    {
        var_dump(get_object_vars(this));
    }
}
```

**Result:**

```
array(1) {
  ["a"]=>int(1)
}
```

---

I attached the test sources: [php_zep_tests.zip](https://github.com/phalcon/zephir/files/232398/php_zep_tests.zip)

**PS: Zephir is a very cool ppiece of code, I really love it.**

**Comment by Jurigag** [comment]
`get all the properties of an object` It's returning properties of an object depends on the scope. If for example you gonna call it outside of object then it should return only public fields what it's doing in this case. But in your case, yea, it should return all fields.

**Comment by steffengy** [comment]
it seems like `EG(scope)` isn't being set correctly.
[here](https://github.com/php/php-src/blob/c72282a13b12b7e572469eba7a7ce593d900a8a2/Zend/zend_object_handlers.c#L277)

Note: This is only an assumption based on the situation.

**Comment by xEsk** [comment]
Some news about this issue?

**Comment by Jurigag** [comment]
@sjinks could you look into this? What is weird on php 7.1.0 it works correctly. Though i didn't check if for 100% correctly like call get_object_vars in other class scope for other object.

**Comment by Jurigag** [comment]
Related https://forum.phalconphp.com/discussion/16527/toarray-method#C49535
