### ISSUE TITLE
Unable to install zephir on Debian stretch/sid

### ISSUE THREAD

**Issue by stratoss** [zephir-lang/zephir#1251]
Zephir version: 0.8,
OS: Debian stretch/sid

`./install -c` returns `error: re2c is not installed`

`re2c -v` returns `re2c 0.16`

I've managed to install it by changing `if [ $? != 2 ]; then` to `if [ $? != 0 ]; then` and it works, but it should be that way...
##

**Comment by sergeyklay** [comment]
it seems to me this check need to refactor so use something like `$(which re2c)`
