### ISSUE TITLE
Change to zephir_camelize omits delimiter

### ISSUE THREAD

**Issue by mdular** [zephir-lang/zephir#1252]
[This](https://github.com/phalcon/zephir/commit/182e3137fbf243501e4264417b1dd84641635122#diff-06d533289d695a1ece14625a036899fbL594) change breaks backwards compatibility by omitting a delimiter. The change is about adding a parameter + the docbloc still mentions both delimiters, which is why I believe the change in behaviour was not intentional.

Since cphalcon already has this change tagged, and it breaks projects relying on camelize in phalcon 2.0.11 it would be great to find a speedy solution (fast-track, or alternatively pin cphalcon on a previous version of zephir)

Highlighting ZE2 counterpart for convenience: https://github.com/phalcon/zephir/commit/182e3137fbf243501e4264417b1dd84641635122#diff-2ad045f7146412da38eb613636a47f8fL277

**Comment by steffengy** [comment]
@sergeyklay
