### ISSUE TITLE
Memory leak on default property as array

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1255]
PHP is not support default array value for properties and we assign default array value in `__constructor`, but I think we don't clean the memory at the end:

``` zep
class Test
{
    protected data = [];
}
```

``` php
while (1) {
    $test = new Test();
    $test = null;
    echo memory_get_usage() . "\n";
    sleep(1);
}
```

```
php test.php 
237144
237240
237288
237336
237384
...
```

If I don't set default array and move an assign to the constructor, works fine, but keep in mind issue: "Can't overwrite the default array data if extends" #537

``` zep
protected data;

public function __construct(array data = [])
    {
        let this->data = data;
    }
```

```
php test.php 
237096
237144
237144
237144
237144
...
```

I tried to clean in the destructor, but it is not the solution.

**Comment by kse300489** [comment]
What version of OS and PHP?

**Comment by mruz** [comment]
openSUSE Tumbleweed
PHP 5.6.20

**Comment by kse300489** [comment]
OS 32 or 64? zephir version?

**Comment by mruz** [comment]
64bit, Zephir version 0.9.2a-dev
Did you try to reproduce?

**Comment by kse300489** [comment]
I try to check on my 32bit with 0.9.2 stable.

**Comment by steffengy** [comment]
PHP doesn‘t support default array values,
which we do not use.

The custom constructor assigns a property value just as any other property assignment would.
So the issue here, if valid, is likely something entirely different.

**Comment by sergeyklay** [comment]
I ran 3040 iterations.

**PHP 7.0.13**
```
php test.php
350760
350792
350792
350792
350792
350792

...

350792
350792
350792
```

**PHP 5.6.29**

```
php test.php
220288
220384
220432
220480
220528
220576

...

366160
366208
366256
```

Zephir 0.9.5a-dev

**Comment by fightingbamboo** [comment]
when will zephir support  default array values?

**Comment by steffengy** [comment]
it does support default values, if it didn't this issue couldn't be about a memory leak when using them.
