### ISSUE TITLE
Segmentation fault  on pdo statement->fetch

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1269]
It's error /usr/local/bin/zephir: line 26: 39527 Segmentation fault      (core dumped) php -d safe_mode=Off -d enable_dl=On $ZEPHIRDIR/compiler.php $*

if I remove this line return this->statement->fetch( \PDO::FETCH_OBJ );
it works

```
namespace App\ORM;

class Query {

    public query;
    public values = [ ];
    public statement;
    public connection;
    public _table;

    public function __construct( connection, table ) {
        let this->connection = connection;
        let this->_table = table;
    }

    public function _execute() {
        return this->_buildQuery( this->query, this->values );
    }

    public function _buildQuery( sql, values = [ ] ) {
        let this->statement = this->connection->prepare( sql );
        this->statement->execute( values );

        return this->statement->fetch( \PDO::FETCH_OBJ );

    }

}
```
##

**Comment by andresgutierrez** [comment]
Can you please provide a backtrace?

``` php
gdb php
gdb> run my-script.php
```

**Comment by surjit** [comment]
I'm trying to compile it with zephir

**Comment by surjit** [comment]
(gdb) run php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
Starting program: /usr/bin/php php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Could not open input file: php
[Inferior 1 (process 39989) exited with code 01]
(gdb) 

I got this

**Comment by surjit** [comment]
(gdb) run /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
Starting program: /usr/bin/php php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Could not open input file: php
Inferior 1 (process 39989) exited with code 01

any other way

(gdb) run /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
Starting program: /usr/bin/php /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Parse error: syntax error, unexpected '@' in /usr/bin/php on line 1159
[Inferior 1 (process 40007) exited with code 0377]

**Comment by andresgutierrez** [comment]
Can you run `bt`after `run` please?

``` php
gdb> run /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
gdb> bt
```

**Comment by surjit** [comment]
root@ubuntu:/home/app# gdb php
GNU gdb (Ubuntu 7.11-0ubuntu1) 7.11
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later http://gnu.org/licenses/gpl.html
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
http://www.gnu.org/software/gdb/bugs/.
Find the GDB manual and other documentation resources online at:
http://www.gnu.org/software/gdb/documentation/.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from php...done.
(gdb) run /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
Starting program: /usr/bin/php /usr/bin/php -d safe_mode=Off -d enable_dl=On /home/zephir/compiler.php $*
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Parse error: syntax error, unexpected '@' in /usr/bin/php on line 1159
[Inferior 1 (process 84769) exited with code 0377](gdb) bt
No stack.

**Comment by mruz** [comment]
Try with `$fetch`:

``` zep
return this->statement->$fetch( \PDO::FETCH_OBJ );
```

**Comment by sergeyklay** [comment]
Ya, `fetch` reserved keyword

**Comment by xuanskyer** [comment]
@sergeyklay  how to solve ?

**Comment by sergeyklay** [comment]
Use `$fetch` instead `fetch`
