### ISSUE TITLE
Centos 7 install fails with PHP 7 

### ISSUE THREAD

**Issue by mahen3d** [zephir-lang/zephir#1270]
I get error as below when i try install in php-7 centos 7 ?

Warning: Function "imagettfbbox" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 348 [nonexistent-function]

```
       let space = imagettfbbox(size, 0, fontfile, text);
    ----------------------------------------------------^
```

Warning: Function "imagettftext" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 375 [nonexistent-function]

```
       imagettftext(this->_image, size, angle, offsetX, offsetY, color, fontfile, text);
    -----------------------------------------------------------------------------------^
```

Warning: Function "imagefontwidth" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 377 [nonexistent-function]

```
       let width  = (int) imagefontwidth(size) * strlen(text);
    -------------------------------------------^
```

Warning: Function "imagefontheight" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 378 [nonexistent-function]

```
       let height = (int) imagefontheight(size);
    -------------------------------------------^
```

Warning: Function "imagestring" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 389 [nonexistent-function]

```
       imagestring(this->_image, size, offsetX, offsetY, text, color);
    -----------------------------------------------------------------^
```

Warning: Function "imagecreatefromstring" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 398 [nonexistent-function]

```
      let maskImage   = imagecreatefromstring(mask->render());
    ---------------------------------------------------------^
```

Warning: Function "imagesx" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 399 [nonexistent-function]

```
      let mask_width  = (int) imagesx(maskImage);
    --------------------------------------------^
```

Warning: Function "imagesy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 400 [nonexistent-function]

```
      let mask_height = (int) imagesy(maskImage);
    --------------------------------------------^
```

Warning: Function "imagesavealpha" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 403 [nonexistent-function]

```
      imagesavealpha(maskImage, true);
    ---------------------------------^
```

Warning: Function "imagesavealpha" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 406 [nonexistent-function]

```
      imagesavealpha(newimage, true);
    --------------------------------^
```

Warning: Function "imagefill" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 410 [nonexistent-function]

```
      imagefill(newimage, 0, 0, color);
    ----------------------------------^
```

Warning: Function "imagecreatetruecolor" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 413 [nonexistent-function]

```
       let tempImage = imagecreatetruecolor(this->_width, this->_height);
    --------------------------------------------------------------------^
```

Warning: Function "imagecopyresampled" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 415 [nonexistent-function]

```
       imagecopyresampled(tempImage, maskImage, 0, 0, 0, 0, this->_width, this->_height, mask_width, mask_height);
    -------------------------------------------------------------------------------------------------------------^
```

Warning: Function "imagedestroy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 416 [nonexistent-function]

```
       imagedestroy(maskImage);
    --------------------------^
```

Warning: Function "imagesetpixel" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 439 [nonexistent-function]

```
        imagesetpixel(newimage, x, y, color);
    ----------------------------------------^
```

Warning: Function "imagedestroy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 445 [nonexistent-function]

```
      imagedestroy(this->_image);
    ----------------------------^
```

Warning: Function "imagedestroy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 446 [nonexistent-function]

```
      imagedestroy(maskImage);
    -------------------------^
```

Warning: Function "imagecopy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 461 [nonexistent-function]

```
      if imagecopy(background, this->_image, 0, 0, 0, 0, this->_width, this->_height) {
    ----------------------------------------------------------------------------------^
```

Warning: Function "imagedestroy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 462 [nonexistent-function]

```
       imagedestroy(this->_image);
    -----------------------------^
```

Warning: Function "imagefilter" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 472 [nonexistent-function]

```
       imagefilter(this->_image, IMG_FILTER_GAUSSIAN_BLUR);
    ------------------------------------------------------^
```

Warning: Constant 'IMG_FILTER_GAUSSIAN_BLUR' does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 472 [nonexistent-constant]

```
       imagefilter(this->_image, IMG_FILTER_GAUSSIAN_BLUR);
    -----------------------------------------------------^
```

Warning: Function "imagefilledrectangle" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 492 [nonexistent-function]

```
        imagefilledrectangle(this->_image, x, y, x2, y2, color);
    -----------------------------------------------------------^
```

Warning: Function "imagegif" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 516 [nonexistent-function]

```
       imagegif(this->_image, file);
    -------------------------------^
```

Warning: Function "imagejpeg" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 530 [nonexistent-function]

```
        imagejpeg(this->_image, file, quality);
    ------------------------------------------^
```

Warning: Function "imagejpeg" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 532 [nonexistent-function]

```
        imagejpeg(this->_image, file);
    ---------------------------------^
```

Warning: Function "imagepng" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 539 [nonexistent-function]

```
       imagepng(this->_image, file);
    -------------------------------^
```

Warning: Function "imagewbmp" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 545 [nonexistent-function]

```
       imagewbmp(this->_image, file);
    --------------------------------^
```

Warning: Function "imagexbm" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 551 [nonexistent-function]

```
       imagexbm(this->_image, file);
    -------------------------------^
```

Warning: Function "imagegif" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 563 [nonexistent-function]

```
       imagegif(this->_image);
    -------------------------^
```

Warning: Function "imagejpeg" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 567 [nonexistent-function]

```
       imagejpeg(this->_image, null, quality);
    -----------------------------------------^
```

Warning: Function "imagepng" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 571 [nonexistent-function]

```
       imagepng(this->_image);
    -------------------------^
```

Warning: Function "imagewbmp" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 575 [nonexistent-function]

```
       imagewbmp(this->_image);
    --------------------------^
```

Warning: Function "imagexbm" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 579 [nonexistent-function]

```
       imagexbm(this->_image, null);
    -------------------------------^
```

Warning: Function "imagecreatetruecolor" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 590 [nonexistent-function]

```
      let image = imagecreatetruecolor(width, height);
    -------------------------------------------------^
```

Warning: Function "imagesavealpha" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 593 [nonexistent-function]

```
      imagesavealpha(image, true);
    -----------------------------^
```

Warning: Function "imagedestroy" does not exist at compile time in /home/centos/cphalcon/phalcon/image/adapter/gd.zep on 604 [nonexistent-function]

```
       imagedestroy(image);
    ----------------------^
```

Warning: Function "utf8_encode" does not exist at compile time in /home/centos/cphalcon/phalcon/mvc/view/engine/volt.zep on 173 [nonexistent-function]

```
       return utf8_encode(text);
    ---------------------------^
```

Warning: Function "utf8_decode" does not exist at compile time in /home/centos/cphalcon/phalcon/mvc/view/engine/volt.zep on 180 [nonexistent-function]

```
       return utf8_decode(text);
    ---------------------------^
```

Warning: Function "\sodium\randombytes_buf" does not exist at compile time in /home/centos/cphalcon/phalcon/security/random.zep on 124 [nonexistent-function]

```
       return \\Sodium\\randombytes_buf(len);
    ----------------------------------------^
```

Warning: Function "\sodium\randombytes_uniform" does not exist at compile time in /home/centos/cphalcon/phalcon/security/random.zep on 320 [nonexistent-function]

```
       return \\Sodium\\randombytes_uniform(len) + 1;
    ---------------------------------------------^
```

```
PHP Fatal error:  Uncaught Error: Call to undefined function Zephir\utf8_decode() in /home/centos/zephir/Library/Compiler.php:2198
Stack trace:
#0 /home/centos/zephir/Library/Compiler.php(1149): Zephir\Compiler->createProjectFiles('phalcon')
#1 /home/centos/zephir/Library/Compiler.php(1194): Zephir\Compiler->generate(Object(Zephir\Commands\CommandBuild))
#2 /home/centos/zephir/Library/Compiler.php(1330): Zephir\Compiler->compile(Object(Zephir\Commands\CommandBuild), false)
#3 /home/centos/zephir/Library/Compiler.php(1414): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#4 /home/centos/zephir/Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#5 /home/centos/zephir/Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#6 /home/centos/zephir/compiler.php(21): Zephir\Bootstrap::boot()
#7 {main}
```
  thrown in /home/centos/zephir/Library/Compiler.php on line 2198
##

**Comment by surjit** [comment]
it seems like php gd library is not compiled if build from source otherwise sudo yum install php-gd

**Comment by andresgutierrez** [comment]
Make sure you have that function available in php first

**Comment by sergeyklay** [comment]
You have to install/enable xml extension
http://php.net/manual/en/function.utf8-decode.php
