### ISSUE TITLE
PHP7 install: Zephir\Exception: Parser extension couldn't be loaded  

### ISSUE THREAD

**Issue by kcloze** [zephir-lang/zephir#1272]
zephir build –backend=ZendEngine3
PHP Warning:  PHP Startup: zephir_parser: Unable to initialize module
Module compiled with build ID=API20151012,NTS,debug
PHP    compiled with build ID=API20151012,NTS
These options need to match
 in Unknown on line 0
Zephir\Exception: Parser extension couldn't be loaded 
##

**Comment by andresgutierrez** [comment]
It seems you have to rebuild the parser using the proper configuration:

```
cd zephir/parser
phpize --clean
cd ..
zephir build
```
