### ISSUE TITLE
Is there a problem with preg_match and matches inside an IF?

### ISSUE THREAD

**Issue by xEsk** [zephir-lang/zephir#1274]
Is there a problem with **preg_match** or I'm not using it correctly?

---

**Test case 1:**

```
    var matches;
    let matches =  null;
    if preg_match("/is([A-Z]\\w+)/", "isLogged()", matches) {
        var_dump(matches);
    }
```

**Output:**

> array(0) { } 

---

**Test case 2:**

```
    var matches;
    let ok =  preg_match("/is([A-Z]\\w+)/", "isLogged()", matches);
    var_dump(matches);
    if ok {
        var_dump(matches);
    }
```

**Output:**

> array(2) { [0]=> string(8) "isLogged" [1]=> string(6) "Logged" } 
> array(0) { } 

---

As you can see, the **matches** variable is filled with results, but when I use it into the **if** then is empty. Why? Is it a bug or I'm missing something?
##

**Comment by andresgutierrez** [comment]
The problem is not the `if`, but probably that `matches` must have memory allocated for it, it wasn't done in the second case: `matches = null`

**Comment by sergeyklay** [comment]
Can't reproduce.

Zephir code:
```zep
namespace Bug;

class Pregm
{
    public function test() -> void
    {
        var matches;
        let matches =  null;

        if preg_match("/is([A-Z]\\w+)/", "isLogged()", matches) {
            var_dump(matches);
        }

        var_dump(NULL);
    }
}
```

Test:
```php
<?php

use Bug\Pregm;

$test = new Pregm;
$test->test();
```

Output:
```
array(2) {
  [0]=>
  string(8) "isLogged"
  [1]=>
  string(6) "Logged"
}
NULL
```
