### ISSUE TITLE
php7: compiles but can not run

### ISSUE THREAD

**Issue by lscgzwd** [zephir-lang/zephir#1276]
PHP Warning:  PHP Startup: Unable to load dynamic library '/opt/remi/php70/root/usr/lib64/php/modules/xxexcel.so' - /opt/remi/php70/root/usr/lib64/php/modules/xxexcel.so: undefined symbol: ZEPHIR_CHECK_POINTER in Unknown on line 0

I find ZEPHIR_CHECK_POINTER  not defined in ZendEngine3, then I copy it from ZendEngine2.

but I can not compile .

errors:

/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c: In function ‘zim_XxExcel_Writer_setAuthor’:
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c:83: error: wrong type argument to unary exclamation mark
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c: In function ‘zim_XxExcel_Writer_setSheets’:
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c:118: error: wrong type argument to unary exclamation mark
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c: In function ‘zim_XxExcel_Writer_setTempFiles’:
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c:153: error: wrong type argument to unary exclamation mark
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c: In function ‘zim_XxExcel_Writer_setFileName’:
/home/nginx/workspace/xxexcel/ext/xxexcel/writer.zep.c:188: error: wrong type argument to unary exclamation mark
make: **\* [xxexcel/writer.lo] Error 1

**Comment by sergeyklay** [comment]
Have you used latest Zephir from master branch?

**Comment by lscgzwd** [comment]
yes, I clone zephir  just four hours ago(2016-07-03 12:00:00 UTC).

```
[root@localhost zephir]# git pull
Already up-to-date.
[root@localhost zephir]# git status
~ On branch master
```

``` zephir
if ($compilationContext->config->get('check-invalid-reads', 'optimizations')) {
    switch ($variable->getType()) {
        case 'variable':
        case 'string':
        case 'array':
            if (!$variable->isLocalOnly()) {
                $variable->setMustInitNull(true);
                $compilationContext->codePrinter->output('ZEPHIR_CHECK_POINTER(' . $variable->getName() . ');');
        }
        break;
    }
}
```

I can see that the check work when check-invalid-reads set to true, I just turn check-invalid-reads to false, it works ok.

**Comment by sergeyklay** [comment]
@steffengy ?

**Comment by mahmoud-eskandari** [comment]
Can i compile Code in php 7?
Is this Possible Now?

**Comment by sergeyklay** [comment]
@mahmoud-eskandari yes. but this question is not related to this problem
