### ISSUE TITLE
Cannot read constant

### ISSUE THREAD

**Issue by danielspk** [zephir-lang/zephir#1278]
I have the "Zephir\CompilerException: Cannot locate class 'FastRoute\Dispatcher'" error when you want to access a constant "Fast Route".

Example code:
`if (\FastRoute\Dispatcher::NOT_FOUND) { ... }`

Reference:
https://github.com/nikic/FastRoute/blob/master/src/Dispatcher.php

**Comment by andresgutierrez** [comment]
This is a compiler, and the class does not exist when it tries to read it

**Comment by danielspk** [comment]
As I can provide a reference to the class the compiler?

**Comment by dreamsxin** [comment]
You can add file `vendor/autoload.php` in zephir dir, and autoload the class.
