### ISSUE TITLE
at Library/Compiler.php(1350)

### ISSUE THREAD

**Issue by alisovpv** [zephir-lang/zephir#1285]
zephir fullclean
zephir build --backend=ZendEngine3

```
Preparing for PHP compilation...
Preparing configuration file...
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information

at Library/Compiler.php(1350)
#0 Library/Compiler.php(1414): Zephir\Compiler->install(Object(Zephir\Commands\CommandBuild), false)
#1 Library/Commands/CommandAbstract.php(108): Zephir\Compiler->build(Object(Zephir\Commands\CommandBuild))
#2 Library/Bootstrap.php(200): Zephir\Commands\CommandAbstract->execute(Object(Zephir\Config), Object(Zephir\Logger))
#3 compiler.php(21): Zephir\Bootstrap::boot()
#4 {main}
```

ubuntu 16.04
php 7.0.4

**Comment by sergeyklay** [comment]
@alisovpv What says compile-errors.log?

Also could you please locate the issue and provide code to reproduce?

**Comment by alisovpv** [comment]
compile-errors.log

`/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:` In function ‘zim_Phalcon_Annotations_Reader_parse’:
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:91:55: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                                                       ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct _}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:115:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                                                         ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:147:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                                                         ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *_\* [phalcon/annotations/reader.lo] Ошибка 1
make: **\* Ожидание завершения заданий…
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c: In function ‘zim_Phalcon_Annotations_Reader_parse’:
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:91:55: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
   ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(classAnnotations, &comment, &_0$$3, &_1$$3 TSRMLS_CC);
                                                       ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct _}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:115:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(propertyAnnotations, &comment, &_3$$7, &_4$$7 TSRMLS_CC);
                                                         ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
/home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:147:57: error: incompatible type for argument 1 of ‘phannot_parse_annotations’
     ZEPHIR_LAST_CALL_STATUS = phannot_parse_annotations(methodAnnotations, &comment, &_7$$12, &_8$$12 TSRMLS_CC);
                                                         ^
In file included from /home/fix/cphalcon/ext/phalcon/annotations/reader.zep.c:22:0:
./phalcon/annotations/annot.h:44:5: note: expected ‘zval \* {aka struct _zval_struct *}’ but argument is of type ‘zval {aka struct _zval_struct}’
 int phannot_parse_annotations(zval *result, zval *comment, zval *file_path, zval *line TSRMLS_DC);
     ^
make: *_\* [phalcon/annotations/reader.lo] Ошибка 1
`

**Comment by alisovpv** [comment]
Извините, я не пойму о каком коде вы говорите. Я просто установил  Zephir, скачал (git clone) Phalcon и пытаюсь его инсталлировать. 

google translate 

> Sorry, I do not understand what kind of code you are talking about. I just found Zephir, downloaded (git clone) Phalcon and try to install it.

**Comment by andresgutierrez** [comment]
Follow these steps:

```
git clone https://github.com/phalcon/cphalcon
cd cphalcon
git checkout 3.0.x
zephir build --backend=ZendEngine3
```

**Comment by alisovpv** [comment]
Extension instaled!
Thank you so much!
