### ISSUE TITLE
Error in extension

### ISSUE THREAD

**Issue by danielspk** [zephir-lang/zephir#1299]
Hello, compiling the extension works fine, but when used gives the following error: "php: symbol lookup error: /usr/lib/php/20151012/dsp.so: undefined symbol: zephir_is_true"

My version of php is PHP 7.0.10-1~dotdeb+8.1 (cli) ( NTS ).

Thank.

**Comment by andresgutierrez** [comment]
Can you please post the code you're using that causes this issue?

**Comment by danielspk** [comment]
This is the public repository: https://github.com/danielspk/TornadoHttpZephir

Run test: php test/index.php

Thank.

**Comment by dreamsxin** [comment]
You can update zephir and reinstall it:

``` shell
./install -c
```

and rm your project kernel

``` shell
rm ext/kernel/
```

**Comment by danielspk** [comment]
Thanks, the error was fixed.
