### ISSUE TITLE
[NFR] Group use

### ISSUE THREAD

**Issue by Izopi4a** [zephir-lang/zephir#1303]
is it hard and possible to have this feature in zephir also http://php.net/manual/en/migration70.new-features.php#migration70.new-features.group-use-declarations

php implementation [link](https://github.com/php/php-src/pull/1005/files)
##

**Comment by sergeyklay** [comment]
Zephir !== PHP

The fact that Zephir's syntax is similar to PHP's one doesn't mean that Zephir is PHP.<br>So Zephir **syntax** isn't obligated to support all stuff from PHP.

**Comment by Izopi4a** [comment]
Yes i know, i was just wondering if its like ~30 mins to be implemented, cuz its nice :D . Its not big deal its just nice. 

But if Andress / Steffengy says its pointless we can close it.

**Comment by Izopi4a** [comment]
the other nice feature I miss is 

```
$data = ( new MyClass() ) -> getData();
```

:D . But i guess its too much to be implemented.

**Comment by Jurigag** [comment]
Im guessing that all you mention here can be just done on compiling code from zephir to c, like parsing this correctly. But is it worth it really to do it ?
