### ISSUE TITLE
what happend? can't run zephir help?

### ISSUE THREAD

**Issue by jockchou** [zephir-lang/zephir#1311]
[root@jockchou snail]# zephir help
PHP Fatal error:  Declaration of Snail\Mvc\Application::any() must be compatible with Snail\Mvc\ApplicationInterface::any($route, $methods, $handleFunc = NULL) in Unknown on line 0

Fatal error: Declaration of Snail\Mvc\Application::any() must be compatible with Snail\Mvc\ApplicationInterface::any($route, $methods, $handleFunc = NULL) in Unknown on line 0
/usr/local/bin/zephir: line 26: 17703 Segmentation fault      (core dumped) php -d safe_mode=Off -d enable_dl=On $ZEPHIRDIR/compiler.php $*

**Comment by sergeyklay** [comment]
Snail?

**Comment by jockchou** [comment]
Yes. This is the first time I use Zephir. I written some code `https://github.com/jockchou/Snail`

I found it's difficult to debug, It takes me a long time to debug.

**Comment by sergeyklay** [comment]
As I can see the issue already fixed
https://github.com/jockchou/Snail/commit/0f325040d21169c30d459461ecc752360729a6d9#diff-f2becfca8af22967af7cec4041539e81R22
