### ISSUE TITLE
external class call not working

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1321]
I have external class in App\Model\Account
when i use it in zep, I'm getting error  Zephir\CompilerException: Class name: App\Model\Accounts does not exist

// zep source

```
class MyClass {
    public function acc(){
        var ac;
       let ac = \App\Model\Account::getDetails();
      return ac;
   }
}
```

use App\Model\Account;
var className = "Account";
If i try {className}::getDetails();

then getting
Fatal error: Class 'Account' not found

**Comment by sergeyklay** [comment]
@surjit Did you see https://github.com/phalcon/zephir/issues/304#issuecomment-61341940
