### ISSUE TITLE
Stubs generation for returned value

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1331]
Well, zephir don't generate stubs correctly for classes which are not in same namespace as current class and are not using explicitly `@return` annotation.

Example:

https://github.com/phalcon/cphalcon/blob/master/phalcon/db/adapter/pdo/mysql.zep#L407 this class is `Phalcon\Db\Adapter\Mysql`

Method returns `Phalcon\Db\Reference[]`

But in docs it's https://github.com/phalcon/phalcon-devtools/blob/3.0.x/ide/stubs/Phalcon/db/adapter/pdo/Mysql.php#L73 just `Reference[]` from `Phalcon\Db\Adapter\Pdo` namespace where this class doesn't exist.
##

**Comment by Jurigag** [comment]
Isn't this more like a bug in stubs generator ?

**Comment by sergeyklay** [comment]
Fixed in the `master` branch.

**Comment by Jurigag** [comment]
Somthing is broken again, see:
https://github.com/phalcon/phalcon-devtools/blob/master/ide/stubs/Phalcon/mvc/Model.php#L437

Just Resultset is returned, but from wrong namespace(`Phalcon\Mvc\Model`).

https://github.com/phalcon/phalcon-devtools/blob/2.1.x/ide/stubs/Phalcon/mvc/Model.php#L369 in 2.1.x stubs which was generated previously this works fine.

Though this https://github.com/phalcon/phalcon-devtools/blob/master/ide/stubs/Phalcon/db/adapter/pdo/Mysql.php#L75 is correct one now. Like something fixed but other problem now.

**Comment by sergeyklay** [comment]
I'll try to sort out

**Comment by sergeyklay** [comment]
As I can see fixed for now
