### ISSUE TITLE
ZendEngine3::zend_generator_create_zval

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1337]
The `ZendEngine3` kernel use outdated `zend_generator_create_zval`.
https://github.com/phalcon/zephir/blob/master/kernels/ZendEngine3/extended/fcall.c#L167

This function is no longer present in ZendEngine 3:
https://github.com/php/php-src/blob/master/Zend/zend_generators.h

---

Refs: https://github.com/phalcon/cphalcon/issues/12055#issuecomment-252565246

**Comment by andresgutierrez** [comment]
It was removed in php 7.1?

**Comment by sergeyklay** [comment]
@andresgutierrez As I can see yes
https://github.com/php/php-src/commit/ccf18da450881bee09e966c0a7fa4d67840d9e38
