### ISSUE TITLE
how can support  property and method using same name?

### ISSUE THREAD

**Issue by xuanskyer** [zephir-lang/zephir#1348]
like this:

```zephir
class Request {
	public get = [];

        public function get() {
                // ...
        }
}
```

**Comment by Jurigag** [comment]
This should work. Just perhaps get is keyword in zephir for generating getters and this is why it's not working. Try `$get`

**Comment by xuanskyer** [comment]
@Jurigag thanks!

I solved it use a dynamic manner .

I 'll try your method
