### ISSUE TITLE
New version ?

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/zephir#1355]
In latest phalcon 3.0.2
`#define PHP_PHALCON_ZEPVERSION "0.9.4a-dev"`

I think it will make sense to have a 0.9.5 version released and used for new phalcon build.
Trying to understand which version is required is just nearly impossible.

**Comment by sergeyklay** [comment]
Just released 0.9.5 now

**Comment by remicollet** [comment]
Thanks

**Comment by remicollet** [comment]
BTW:

* Library/Compiler.php => const VERSION = '0.9.4a-dev';
* parser/php_zephir_parser.h => :#define PHP_ZEPHIR_PARSER_VERSION "0.1.0"

**Comment by sergeyklay** [comment]
PHP_ZEPHIR_PARSER_VERSION !== VERSION, but yes, 0.9.4a-dev should be fixed

**Comment by sergeyklay** [comment]
Fixed
