### ISSUE TITLE
PHP7 and 64bit

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1356]
I have a 64bit system, but it seems that for the php7 zephir is generated as 32bit.

```zep
public function test()
{
    int tmp = 2147483648;
    var_dump(tmp);
}
```
> int(-2147483648)

It's related with integer overflow https://docs.zephir-lang.com/en/latest/types.html#integer, but _64-bit platforms usually have a maximum value of about 9E18_, so it should work, and it works on 64bit machine with the PHP 5.6

@andresgutierrez maybe we could use gen-build.php https://github.com/phalcon/zephir/issues/1257

**Comment by dreamsxin** [comment]
If like in C, the must be define like like this `long tmp = 2147483648 ` or `var tmp = 2147483648 `,  If like php must modify generate code `int` to `long` or `zend_long`.

**Comment by mruz** [comment]
I'm using `long tmp` right now.
Maybe for php5 it is modified by default and this is the reason why it's working for php5, but not for php7?

**Comment by dreamsxin** [comment]
At Linux,
LP64: long long int 64bit, unsigned long int 64bit
LLP64: long long int 64bit, long int 32bit
May be check PHP version use zend_long, 
```c
d(__x86_64__) || defined(__LP64__) || defined(_LP64) || defined(_WIN64)
# define ZEND_ENABLE_ZVAL_LONG64 1
#endif

/* Integer types. */
#ifdef ZEND_ENABLE_ZVAL_LONG64
typedef int64_t zend_long;
typedef uint64_t zend_ulong;
typedef int64_t zend_off_t;
# define ZEND_LONG_MAX INT64_MAX
# define ZEND_LONG_MIN INT64_MIN
# define ZEND_ULONG_MAX UINT64_MAX
# define Z_L(i) INT64_C(i)
# define Z_UL(i) UINT64_C(i)
# define SIZEOF_ZEND_LONG 8
#else
typedef int32_t zend_long;
typedef uint32_t zend_ulong;
typedef int32_t zend_off_t;
# define ZEND_LONG_MAX INT32_MAX
# define ZEND_LONG_MIN INT32_MIN
# define ZEND_ULONG_MAX UINT32_MAX
# define Z_L(i) INT32_C(i)
# define Z_UL(i) UINT32_C(i)
# define SIZEOF_ZEND_LONG 4
#endif
```

**Comment by sergeyklay** [comment]
Cc: @andresgutierrez

**Comment by sjinks** [comment]
PHP 7.0:

```c
	zval _0;
	int tmp;
	zval *this_ptr = getThis();

	ZVAL_UNDEF(&_0);

	ZEPHIR_MM_GROW();

	tmp = 2147483648;
	ZEPHIR_INIT_VAR(&_0);
	ZEPHIR_INIT_NVAR(&_0);
	ZVAL_LONG(&_0, tmp);
	zephir_var_dump(&_0 TSRMLS_CC);
	ZEPHIR_MM_RESTORE();
```

`zend_long` should be used instead of `int`.
