### ISSUE TITLE
_GET[_url] global variable sets incorrect value 

### ISSUE THREAD

**Issue by mbrostami** [zephir-lang/zephir#1371]
I couldn't reproduce issue in zephir. try this code in phalcon.
```php
<?php
$app = new Phalcon\Mvc\Micro();
$app->get('/test/{email}', function ($email) use ($app) {
    return $email;
});
$app->notFound(
    function () use ($app) {
        $app->response->setStatusCode(404, "Not Found");
        $app->response->sendHeaders();
    }
);
$app->handle();
var_dump(Phalcon\Di::getDefault()->get('request')->getQuery()['_url']);die;
```
Open http://localhost/test/hi+email@test.com
It will return "hi email@test.com" even in page source. 
I think there is an issue when zephir wants to set global variables like `_GET`. After tracing code, you can see method `Router::getRewriteUri()` is using `_GET['_url']`.

**Comment by andresgutierrez** [comment]
How do yo know this is caused by Zephir?

**Comment by Jurigag** [comment]
Post some code to reproduce issue without phalcon.

**Comment by mbrostami** [comment]
Hmmm, I figured out that .htaccess causes this, not zephir :(
