### ISSUE TITLE
zephir\parser\configure.js(2209, 9) Microsoft JScript 运行时错误: 'length' 为 null 或不是对象

### ISSUE THREAD

**Issue by bodhi-code** [zephir-lang/zephir#1386]
I have a problem,when I install zephir on windows10.

<bountysource-plugin>
---

**Comment by sergeyklay** [comment]
We need steps to reproduce

**Comment by bodhi-code** [comment]
I was configured in accordance with the configuration of the  zephir in windows, when I use VS 2015 to develop a dynamic link library php 5.5.38, the problem arises. Is it necessary to use VS 2012 to develop php 5.5.38 dynamic link library?

**Comment by gouchaoer** [comment]
你可以看看官方的windows下安装zephir的教程，php5.x和php7在windows下的编译环境是不一样的，5.x的早就有人打通了。php7的可以参考我的教程：http://qsalg.com/?p=549
