### ISSUE TITLE
why zephir not shows error on line

### ISSUE THREAD

**Issue by surjit** [zephir-lang/zephir#1388]
I used zephir months ago, it was showing specific line number of error
current version not showing and makes it too harder to find out errors

please advise how can i find error on which line ?
it just shows "cannot parse file"

**Comment by Jurigag** [comment]
It still shows, it just depends if this is zephir related syntax error(then there will be no line error cuz of limits of parser) or some other error(which will be shown). Cannot parse file is syntax error, like it's lemon error which is not providing(or not returning in zephir) a way to get why exactly file was not parsed.
