### ISSUE TITLE
php7.1 and const problems

### ISSUE THREAD

**Issue by rafmichalak84** [zephir-lang/zephir#1389]
Hey,
I just started to look for errors in phalcon to run it in php-7.1
and just found one cause of

--- test.zep ---
```
namespace Com\Test;

class Test
{
    const CON1 = 1;
    const CON2 = 2;
    const CON3 = 2;
    const CON4 = 2;
    const CON5 = 2;
}
```

compile ok
but when run php
--- test.php ---
```
$oClass = new ReflectionClass('\Com\Test\Test');
var_dump($oClass->getConstants());
```

i've got
```
array(5) {
  ["CON1"]=>
  NULL
  ["CON2"]=>
  bool(false)
  ["CON3"]=>
  bool(false)
  ["CON4"]=>
  bool(false)
  ["CON5"]=>
  bool(false)
}
```

zephir good interpreted

```
zephir_declare_class_constant_long(com_test_builder_ce, SL("CON1"), 1);
zephir_declare_class_constant_long(com_test_builder_ce, SL("CON2"), 2);
```

and how to crash and coredump
php script access to const like 
```
var_dump(\Com\Test\Test::CON2);
```
or change type from int/long to string
then is SegmentationFault after run php or php -m

<bountysource-plugin>
---

**Comment by rafmichalak84** [comment]
I created a patch for Zephir after which phalcon is compile and run for php7.1.1

please for feedback

**Comment by sergeyklay** [comment]
Fixed in `master` branch.
