### ISSUE TITLE
php 7.1 ts in window  const error

### ISSUE THREAD

**Issue by xqkeji** [zephir-lang/zephir#1394]
in php 7.1 ts
zephir const can not use string

for example 
```zep
class A
{
        const A = 1;
        const B = "test";
}
```

this example can complie,but can not execute.

if I delete `const B="test"`, it can execute.

**Comment by rafmichalak84** [comment]
Hi, I checked 10minutes ago and with latest version everything works great.

PHP 7.1.3 (cli) (built: Mar 31 2017 22:05:21) ( ZTS DEBUG )
Zephir 0.9.6a-dev-3ea0e94d8e

Please checked again and I will be waiting for feedback.

my test case
```
<?php
var_dump(new \Utils\Test());

var_dump(\Utils\Test::A);
var_dump(\Utils\Test::B);

```

**Comment by sergeyklay** [comment]
Can't reproduce

* PHP 7.1.3-3+deb.sury.org~xenial+1 (cli) (built: Mar 25 2017 14:00:03) ( NTS )
* Zephir 0.9.6a-dev-ec52b83e7f
