### ISSUE TITLE
Static return type stubs

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1397]
Static returned type in stubs is generated just as current class, example of problem:

https://github.com/phalcon/cphalcon/blob/3.0.x/phalcon/mvc/model.zep#L890
https://github.com/phalcon/phalcon-devtools/blob/3.0.x/ide/stubs/Phalcon/mvc/Model.php#L465

Though on 2.0.x repository it was correctly `@return static`

<bountysource-plugin>

---

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/ide-stubs#2
