### ISSUE TITLE
"A SMALL TASTE" button does nothing

### ISSUE THREAD

**Issue by tobeorla** [zephir-lang/zephir#1398]
**O.S**: Windows 10
**Browser**: Chrome
**URL**: https://zephir-lang.com/

The  "A SMALL TASTE" "See what zephir can do!" button does nothing. No Javascript errors got thrown.

**Comment by Jurigag** [comment]
This is https://github.com/phalcon/zephir-website issue

**Comment by tobeorla** [comment]
https://github.com/phalcon/zephir-website/issues/9
