### ISSUE TITLE
ArrayAccess doesn't work in zephir-land

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1400]
Not sure if fetch keyword supports ArrayAccess interface. Doesn't seems so, check this PR for more https://github.com/phalcon/cphalcon/pull/12670

It could be nice to implement it imho.

**Comment by Jurigag** [comment]
Well ArrayAccess interface doesn't work at all in zephir-land. Even isset or array["index"] when array is object implementing ArrayAcces doesn't work:

test.zep:

```zep
namespace Arraytest;

class Test implements \ArrayAccess
{
	protected test;

	public function __construct() {
		let this->test = [
			"one":1,
			"two":2,
			"three":3
		];
	}
	
	public function offsetSet(offset, value)
	{
		if is_null(offset) {
			let this->test[] = value;
		} else {
			let this->test[offset] = value;
		}
	}
	
	public function offsetExists(offset) {
		return isset this->test[offset];
	}
	
	public function offsetUnset(offset) {
		unset this->test[offset];
	}
	
	public function offsetGet(offset) {
		return isset this->test[offset] ? this->test[offset] : null;
	}
}
```

test2.zep:

```
namespace Arraytest;

class Test2
{
	public static function test()
	{
		var test;
		
		let test = new Test();
		var_dump(isset test["one"]);
		var_dump(test["one"]);
	}
}


```

test.php:

```
use Arraytest\Test2;
use Arraytest\Test;

Test2::test();
$test = new Test();
var_dump(isset($test["one"]));
var_dump($test["one"]);
```

Returns:

> bool(false)
> PHP Notice:  Cannot use a scalar value as an array in arraytest/test2.zep on line 11 in /root/test.php on line
>  5
> 
> Notice: Cannot use a scalar value as an array in arraytest/test2.zep on line 11 in /root/test.php on line 5
> NULL
> bool(true)
> int(1)

**Comment by Jurigag** [comment]
Looks like https://github.com/phalcon/zephir/issues/1061 this issue was related but code to reproduce got deleted.

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look
