### ISSUE TITLE
Model relations with find_in_set() feature

### ISSUE THREAD

**Issue by SimBioT1954** [zephir-lang/zephir#1401]
Hello! 
@sergeyklay 
It would be a nice feature to add support of find_in_set() Mysql function for model relationships.

E.g. 
```
table Posts
 -----------------------------------
|  id  |   related_users |   name    |
----------------------
|  1   |   1,2,3         | post_name |
 -----------------------------------
```

Model Users.php
```
$this->hasMany('id', 'Posts', 'related_users', [
            'alias' => 'posts',
            'in_set' => true
 ]);
```

Controller:
```
$user = Users::findFirstById(1);

foreach ($user->posts as $post) {

echo $post->name;

}
```

I know this is not that good as additional table **related_users** but I think in some special cases there is no other option. 
So I really think this feature would be really usefull 👍 
What do you think about this?

**Comment by Jurigag** [comment]
I think this is really bad. Just use `hasManyToMany`.

**Comment by Jurigag** [comment]
Also this is phalcon issue. https://github.com/phalcon/cphalcon

**Comment by sergeyklay** [comment]
Hello @SimBioT1954

This is NFR (new feature request) related to the [Phalcon](https://github.com/phalcon/cphalcon) project, not Zephir. 
I'm closing this issue here. Feel free to open a NFR at the appropriate repository.

Thank you
