### ISSUE TITLE
is_php_version usability

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1404]
```c
#define zephir_is_php_version(id) (PHP_VERSION_ID / 10 == id / 10 ?  1 : 0)
```

Currently it looks like this, i don't even know wtf is this really. Maybe better would be here to use somehow version_compare and `PHP_VERSION`?

**Comment by sergeyklay** [comment]
version_compare? in C? could you please provide example

**Comment by Jurigag** [comment]
Well version_compare is stupid idea. I think it should be something like(pseudocode):

```c
if(id is int) {
return PHP_VERSION_ID  == id
}

if(id is string && strlen(id) == 1) {
    return PHP_MAJOR_VERSION == id;
}

if(id contains one dot) {
    return PHP_MAJOR_VESION.".".PHP_MINOR_VERSION == id;
}

if(id contains two dot) {
    return PHP_VERSION == id;
}
```

**Comment by sergeyklay** [comment]
I still don't completely understand. What kind of problem you want to solve. Can you elaborate on that

**Comment by Jurigag** [comment]
To make it work how it supposed to be? Right now is_php_version doesn't work how it should be. In phalcon code there was `is_php_version("5")` which obviously wasn't working.

**Comment by sergeyklay** [comment]
So, it is just a Zephir bug (may be). There is no reason to introduce new internal API. Could you please create tests for Zephir?

**Comment by Jurigag** [comment]
Yes, it's zephir bug, but it means that is_php_version needs to be updated to work correctly like i wrote above for example. It's defintely zephir bug, just current code for this function is like this:

```
#define zephir_is_php_version(id) (PHP_VERSION_ID / 10 == id / 10 ?  1 : 0)
```

**Comment by sergeyklay** [comment]
```c
#include <stdio.h>

#define PHP_VERSION_ID 70100
#define zephir_is_php_version(id) (PHP_VERSION_ID / 10 == id / 10 ?  1 : 0)

main ()
{   
    int id_int = 70100;
    float id_float = 70100.0;
    
    if (zephir_is_php_version(id_int)) {
      printf("using for int\n");
    }
    
    if (zephir_is_php_version(id_float)) {
      printf("using for float\n");
    }
}
```

**Comment by Jurigag** [comment]
Yes but in phalcon it was used like `is_php_version("5")`

**Comment by sergeyklay** [comment]
So it is Phalcon bug, not Zephir :)

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
