### ISSUE TITLE
zephir_parse_file  terminates the program without any error messages

### ISSUE THREAD

**Issue by pakey** [zephir-lang/zephir#1409]
There is no error feedback after executing `zephir build`
After checking found in the implementation to the `Library/CompilerFile.php` file
```
$ir = zephir_parse_file(file_get_contents($zepRealPath), $zepRealPath);
```
The program is terminated, no one after any output, and can not capture the specific error message,
What should I do if I do not know where I can do it?

**Comment by sergeyklay** [comment]
Try to check log file.

**Comment by pakey** [comment]
the log file is empty

**Comment by sergeyklay** [comment]
Is it posible to see source to reproduce?

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#19
