### ISSUE TITLE
Do not use master branch for dev purposes

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1416]
@sjinks What do you think about protect master from pushes and keep it as stable version always. I propose to use `development` branch for fixes, testing, etc.

**Comment by sjinks** [comment]
Agreed.

**Comment by sjinks** [comment]
After 3.2.0?

**Comment by sergeyklay** [comment]
Yes

**Comment by sergeyklay** [comment]
I will keep this open until this not done.

**Comment by steffengy** [comment]
I think we agreed on master being NOT stable ages ago?

That's what tags are for... so you can tag against a specific version,
update & check and go back if necessary...
