### ISSUE TITLE
PDO connection is not destroyed

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1417]
On latest zephir version after merging this PR - https://github.com/phalcon/zephir/pull/1415 some PDO related stuff is broken -

https://travis-ci.org/phalcon/cphalcon/jobs/214812313 
https://travis-ci.org/phalcon/cphalcon/jobs/214812314

Im not sure what exactly happens here but it looks like that object containing pdo object is never destroyed or something like this causing multiple connections, don't have time to investigate right now, it could be nice if someone could dig it deeper.

**Comment by sergeyklay** [comment]
```
There were 4 errors:

1) Extension\Integral\RegexDNATest::testProcess
Parameter 3 to preg_match_all() expected to be a reference, value given

/home/vagrant/projects/c/zephir/unit-tests/Extension/Integral/RegexDNATest.php:29

2) Extension\PregmatchTest::testPregMatch
Parameter 3 to preg_match() expected to be a reference, value given

/home/vagrant/projects/c/zephir/unit-tests/Extension/PregmatchTest.php:29

3) Extension\PregmatchTest::testCollectMatches
Parameter 3 to preg_match() expected to be a reference, value given

/home/vagrant/projects/c/zephir/unit-tests/Extension/PregmatchTest.php:82

4) Extension\RouterTest::testRouter
Parameter 3 to preg_match() expected to be a reference, value given

/home/vagrant/projects/c/zephir/unit-tests/Extension/RouterTest.php:191

```

**Comment by sergeyklay** [comment]
Cant realize why on Travis all ok

**Comment by sjinks** [comment]
I have an idea.

**Comment by Jurigag** [comment]
Not sure why in travis okay, on ZE3 the check for those references was commented in zephir ZE3 for some reason - https://github.com/phalcon/zephir/pull/1415/files#diff-79d6f1266299a0ab0de6a3bb7b89f4c5L106, since we changed to ZEND things now we got error.

@sergeyklay

**Comment by sergeyklay** [comment]
@Jurigag https://github.com/phalcon/zephir/pull/1419
Could you please check again?

**Comment by Jurigag** [comment]
Is #1419 supposed to fix this issue with pdo stuff too? @sjinks Like both issues like mine and klay or aim only for one of them?

**Comment by sjinks** [comment]
Hope so. I have restarted failed builds in Travis, let's see. As far as I can see, the issues with ZVAL_COPY was that it created a copy of a zval which was never destroyed.

**Comment by Jurigag** [comment]
Fixed in master

**Comment by sjinks** [comment]
But I still see other failures… are they expected?

**Comment by Jurigag** [comment]
I think so.

**Comment by sjinks** [comment]
Mmm OK

**Comment by Jurigag** [comment]
Well actually `[PHPUnit_Framework_Exception] Access to undefined property _macros` is not expected, it's old issue that was already on php 7 but it was fixed as i remember. `Cannot call func_get_arg() dynamically` is exepcted. Benstalk errors idk why happens, will need to check.

**Comment by sergeyklay** [comment]
@sjinks
> Cannot call func_get_arg() dynamically

https://github.com/phalcon/cphalcon/blob/master/phalcon/text.zep#L245
and
https://github.com/phalcon/zephir/pull/1100

**Comment by sjinks** [comment]
OK
