### ISSUE TITLE
Func_get_arg optimizer

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1420]
We already have func_get_args and func_num_args optimizer but there is missing func_get_arg, though there is no `zend_copy_parameter` or something like equivalent to `zend_copy_parameters_array` to just get one argument, any idea how to solve it? Just get all parameters and return which we want? Or just some code from func_get_arg from php internally? @sjinks

**Comment by Jurigag** [comment]
Well i think best will be something like `zephir_func_get_arg(int)`

**Comment by sergeyklay** [comment]
Refs: https://github.com/sergeyklay/issue1394/pull/6#issuecomment-288876333

**Comment by Jurigag** [comment]
Well for func_get_arg _zend_get_parameters_array_ex can't be replacement i think cuz it will return all parameters, i think the best will be if we will create our own `func_get_arg` version which will be similar php built-in.

**Comment by sjinks** [comment]
@Jurigag the fix has just landed to master, please take a look
