### ISSUE TITLE
PHP 5.4 and PHP5.5

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1430]
I would suggest to remove php 5.4 and php 5.5 in some new versions and remove them in travis.

**Comment by sergeyklay** [comment]
We'll do it after release Phalcon 4.0.0

**Comment by Jurigag** [comment]
Okay, just phalcon already doesn't support php 5.4 and 5.5 but fine.

**Comment by sergeyklay** [comment]
Phalcon  3.x support 5.5

**Comment by Jurigag** [comment]
Oh right, okay, in phalcon 4 we should drop php 5 at all.

**Comment by sergeyklay** [comment]
Yes, we plan support only 7.x for Phalcon 4.x
