### ISSUE TITLE
Protected call

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1431]
Currently zephir allows to call protected method from other object in zephir code itself.

Is there any visbility set in zephir itself or just all methods are public and visibility is only for php?

Here is rellated pull request with tests - https://github.com/phalcon/zephir/pull/1429 Notice on php 7.1 it works as it should be.

**Comment by sjinks** [comment]
In my opinion, Zephir should follow PHP behavior — that is, call to a protected/private method of another class should fail.

**Comment by sjinks** [comment]
The question is, if we port ZE3 behavior into ZE2, will it break a lot of code?

**Comment by sergeyklay** [comment]
@sjinks I'm not sure. Lets try to do it

**Comment by Jurigag** [comment]
I agree, i just wonder what exactly was changed that for php 7.1 somehow it works, i guess latest ZE3 changes in zephir, but shouldn't it affect php 7 too? Or those changes were done only for php 7.1?

**Comment by sjinks** [comment]
I fixed scope issues for PHP 7.1 only, and tries not to touch PHP 7.0 code assuming it works :-)

**Comment by Jurigag** [comment]
Oh okay, then i guess that's why.

**Comment by sjinks** [comment]
7.0 now works the same way as 7.1.

**Comment by Jurigag** [comment]
So this "bug" happens only for php 5.x now? We could add ZendEngine2 label then.

**Comment by sjinks** [comment]
Closing in favor of #1429
