### ISSUE TITLE
Setting this to variable is not working on PHP 7/7.1

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1442]
For example this code:

https://github.com/phalcon/cphalcon/pull/12762/files

Seg faults on config = this;

https://travis-ci.org/phalcon/cphalcon/jobs/216322198#L1131

I will provide some test for it tomorrow maybe.

@sjinks

**Comment by sergeyklay** [comment]
@Jurigag https://github.com/phalcon/cphalcon/blob/master/phalcon/config.zep#L238

**Comment by sjinks** [comment]
Looks like the issue is somewhere else:

```
        public function testIssue1442()
        {
                var instance;
                let instance = this;
                return instance;
        }
```

This works and does not crash.

I will be very grateful for the simple test case :-)

**Comment by Jurigag** [comment]
Yea sure, will try to reproduce it.

**Comment by Jurigag** [comment]
Well on the code from this PR i have warning:

`PHP Warning:  Invalid arguments supplied for explode()`

When `_delimited` is changed to non-static then works fine, but don't have seg fault, hmmmm. Maybe there is somehow no warning and for some weird reason seg fault is detected in next line? I don't know really why this happens.

**Comment by Jurigag** [comment]
```
class Test
{
	protected static _delimiter = ".";

	public function testDelimiter(var delimiter = null)
	{	
		if empty delimiter {
			let delimiter = self::_delimiter;
		}
		
		return delimiter;
	}
}
```

```
$test = new Test3\Test();
var_dump($test->testDelimiter());
```

Output is:

`*uninitialized*`

**Comment by Jurigag** [comment]
Well i created seperated issue - https://github.com/phalcon/zephir/issues/1446 cuz it doesn't looks like related to this, maybe it's somehow causing this issue, idk.

**Comment by sjinks** [comment]
#1446 has been fixed. Could you please check if your `explode` issue is gone?

**Comment by Jurigag** [comment]
Well code in this PR is changed but yea, will check it in free time.
