### ISSUE TITLE
PHP7, preg_match third parameter

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#1443]
```zep
if preg_match("/[.]+/", ini) {
}
```
>Parameter 3 to preg_match() expected to be a reference, value given

**Comment by sjinks** [comment]
Happens when Zephir is compiled without `ZEPHIR_USE_PHP_PCRE`

**Comment by sjinks** [comment]
@mruz Could you please check with latest Zephir's master?

**Comment by mruz** [comment]
This is fixed, but I'm getting
> Cannot call extract() dynamically

I'll try to provide a code to reproduce.

**Comment by Jurigag** [comment]
That's correct. From php 7 or 7.1 you can't use extract etc functions dynamically(in our case use `zend_call_function` to call them), we need to write extract optimizer(and other optimizers) like lately we wrote `func_get_args`, `func_num_args` and `func_get_arg` optimizers

https://wiki.php.net/rfc/forbid_dynamic_scope_introspection

**Comment by mruz** [comment]
OK, but it worked couple of days ago on php7 and previous zephir.

**Comment by sergeyklay** [comment]
We fixed this few days ago :)

**Comment by Jurigag** [comment]
Yea worked but it wasn't correct anyway :) It's just how php works right now and zephir was ignoring it, we removed extended things from ZE3 and now we uses `zend_call_function`

**Comment by mruz** [comment]
Cool, thanks.
