### ISSUE TITLE
Zephir Parser

### ISSUE THREAD

**Issue by sergeyklay** [zephir-lang/zephir#1471]
Hello,

As you probably know we separated [Zephir Parser](https://github.com/phalcon/php-zephir-parser) and [Zephir](https://github.com/phalcon/zephir) to the two repositories. Currently Zephir Readme says that users can install Zephir by using `composer install`.

Unfortunately Composer doesn't support Git submodules, as the main aim of Composer is to provide a similar inter-project dependency functionality and it would be pointless to try to replicate submodules in Composer.

Composer has the option to download the source via a Git clone (`--prefer-source`) rather than downloading a zipball (`--prefer-dist`) which is the default. This allows you to edit the source code inside the vendors directory and then commit it through Git.

This means, in this case the user must go to `vendor/phalcon/zephir` and write there

```
git submodule init
git submodule update
```

and then he needs to run the install script

If he wants to update Zephir Parser he anyway needs to go to `vendor/phalcon/zephir`, to update the git-module and to run the install script.

All is not so dusty, but, for example, when Phalcon builds in any CI, then Zephir is installed there as a Composer dependency. It appears that if we want to use Zephir in CI we write composer install.. there

At this moment Zephir is pulled, but there is no parser (or git module). We need to dig up that folder with Zephir, get there and pull the module there.

For some reason this doesn'r work in some builds. As if the command git submodule init/update fails

There is one more unhandy point. Let's have a look at AppVeyor. If we build Phalcon or Zephir it's no use to compile the parser from source for Windows. It is difficult and takes a very long time. Besides, there are pre-arranged dll available. We can simply pull the needed dll from git-release. It turns out that int this case the git module doesn't matter at all, because it is not used at all.

Additionally, we still have in Zephir some code which try to compile parser by using source code distributed with Zephir together (it is an old parser, I haven't deleted it yet). As I see it, 2 parsers are too much.

I suggest the following flow:

1. The user always installs the Zephir Parser on his own. Now it is available for any platform - Windows, Linux, BSD, macOS, - as a PHP extension for PHP 5.5 - 7.2
2. The user installs Zephir and plays with it having the Zephir Parser **already installed**. If there is no parser we simply inform about this and exit.
3. The user can install the Zephir Parser only one time for any PHP version in his system, e. g. if he has PHP 5.5 and PHP 7.1 in his system.
4. We add one more step involving the parser installation into all CI where Zephir is needed. I've already done this for Zephir and Phalcon

Cc: @steffengy @sjinks @ovr

**Comment by Jurigag** [comment]
+1

**Comment by steffengy** [comment]
In my oppinion the parser and zephir itself are still **too intertwened**.

I think the **user-friendliest** way would be the following changes:
1. move the building of the parser entirely to the parser repository 
(shell-scripts, batch-scripts, instructions)
2. setup **CI** for the parser which builds **.dlls and .so** files for 5.6.X, 7.0.X, 7.1.X
3. **(auto-)publish** those artifacts on travis & appveyor
    (we actually do this for appveyor already, but only for x64 afaik)
4. keep a **commit reference** (hash) in the zephir repository as a **"parser-tag"**.   
    So basically when there isn't any parser loaded,
     zephir can look up the current php version and download the resulting
     .dll/.so file for the stored commit-hash from Travis/Appveyor.

If a user prefers to build the parser himself, 
he can **easily look up the instructions on the parser repository**.
If he doesn't care about it (we should still do some signing for security purposes),
he **won't have to waste any time to wait for a parser build**.

This also allows a composer install to fastly get a working state and smooth user experience.

If anyone has any questions about this, feel free to ask me.

**Comment by sergeyklay** [comment]
@steffengy 
I managed to prepare releases for Windows (TS and NTS) and PHP 5.5 - 7.2
https://github.com/phalcon/php-zephir-parser/releases/tag/v1.0.1

**Comment by steffengy** [comment]
@sergeyklay 
Yeah my suggestion is basically something like that automatized and also for linux.

On startup zephir just has to download and load the appropriate DLL/SO if there isn't
a loaded parser extension or fail and tell the user to deal with the parser installation
since he seems to be running some unconventional OS/PHP-version.

**Comment by steffengy** [comment]
@sergeyklay 
I just noticed that the appveyor builds are already automatized.
Then the only thing missing is doing the same for linux/travis.

And ofcourse modifying zephir to download the correct ones of a given parser release 
(which thanks to deterministic github release URLs 
e.g. https://github.com/phalcon/php-zephir-parser/releases/download/v1.0.1/FILENAME
is quite trivial)

**Comment by mruz** [comment]
So why we separated them if there isn't user-friendly solution?
How about if we have composer package for the parser? and in zephir's composer.json specify the version in the require `"phalcon/php-zephir-parser": "1.1.2"` which should install the parser.
Then we won't need "install_zephir_parser.sh" on zephir/phalcon/ice etc.

**Comment by sergeyklay** [comment]
@mruz anyway  in this case we'll need call some script to install parser from using composer hooks. Right? Also this may require root privileges.

**Comment by mruz** [comment]
yes, something like that should work:
```
    "scripts": {
        "post-install-cmd": ["./install"]
    }
```
I think it will ask for root password if needed.

**Comment by sergeyklay** [comment]
Actually I'm pretty sure this will not simplify the task. The provided `post-install-cmd` will work for Linux but not for Windows. Think about it this way: I need to install the software (dependency) _once_ to install Zephir. For example, I need to install Java as dependency to be able to install PhpStorm.

**Comment by mruz** [comment]
In my opinion even if it's only for Linux it's worth simplifying. It will cover TravisCI too. How about https://github.com/phalcon/zephir/issues/1471#issuecomment-291013327?

**Comment by danhunsaker** [comment]
Composer requirements include a way to require extensions. Just adding `ext-zephir_parser` will remind users to install the extension if they haven't already.

As for the install script we use in test environments, moving that to a different repo would be more maintainable, for sure. Then we just change the test code to grab the latest install script from GitHub (stable branch, of course) before running it as we're already doing now. For best results, move that install script into phalcon/php-zephir-parser itself, so it changes at the same time as the actual extension we're installing.
