### ISSUE TITLE
Memory leak in zephir_throw_exception_debug

### ISSUE THREAD

**Issue by sjinks** [zephir-lang/zephir#1482]
```c
	if (Z_TYPE_P(object) != IS_OBJECT) {
		object_copy = object;
		ALLOC_INIT_ZVAL(object);
		object_init_ex(object, zend_exception_get_default(TSRMLS_C));
		ZEPHIR_CALL_METHOD(NULL, object, "__construct", NULL, 0, object_copy);
	}

	Z_ADDREF_P(object);
```

When `object` is not an object, `ALLOC_INIT_ZVAL(object);` is called, and it creates a new `zval` but its address will be different (and not tracked by Zephir's memory management functions).

After `zephir_throw_exception_debug` returns, memory manager will free `object_copy`, and `object` will have one references more than necessary.

**Comment by virgofx** [comment]
@sjinks Could this be related to #1325? or will it fix it?

**Comment by sjinks** [comment]
Honestly, I think this is a different issue.
