### ISSUE TITLE
Non-tracked variables are not destroyed

### ISSUE THREAD

**Issue by sjinks** [zephir-lang/zephir#1483]
```c
zval _2$$3 = zval_used_for_init;

	while (1) {
		if (!(i < zephir_fast_strlen_ev(value))) {
			break;
		}
		_1$$3 = ZEPHIR_STRING_OFFSET(value, i);
		ZEPHIR_SINIT_NVAR(_2$$3);
		ZVAL_STRINGL(&_2$$3, &_1$$3, 1, 1);
		ZEPHIR_CALL_FUNCTION(&_3$$3, "ord", &_4, 79, &_2$$3);
		zephir_check_call_status();
		ZEPHIR_CALL_FUNCTION(&_5$$3, "dechex", &_6, 6, _3$$3);
		zephir_check_call_status();
		zephir_concat_self(&ret, _5$$3 TSRMLS_CC);
		i++;
	}
	RETURN_CTOR(ret);
```

As a result, the very last value of `_2$$3` will leak.

See: `Variable::initVariant()` in the compiler

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
