### ISSUE TITLE
Unnecessary memory allocation

### ISSUE THREAD

**Issue by sjinks** [zephir-lang/zephir#1487]
```c
PHP_METHOD(Test_SPropertyAccess, __construct) {

	zval *_0, _1, _2, *_3, *_4 = NULL;

	ZEPHIR_MM_GROW();

	ZEPHIR_INIT_ZVAL_NREF(_0);
	ZEPHIR_INIT_VAR(_0);
	ZVAL_STRING(_0, "abc", 1);
```

Both `ZEPHIR_INIT_ZVAL_NREF` and `ZEPHIR_INIT_VAR` allocate memory via `ALLOC_ZVAL`; memory allocated by `ZEPHIR_INIT_ZVAL_NREF` is leaked.

**Comment by sjinks** [comment]
Could be related to #1486

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
