### ISSUE TITLE
zephir_addcslashes() is missing

### ISSUE THREAD

**Issue by sjinks** [zephir-lang/zephir#1502]
`AddcslashesOptimizer`:

```php
$context->codePrinter->output('zephir_addcslashes(' . $symbolVariable->getName() . ', ' . $resolvedParams[0] . ' TSRMLS_CC);');
```

But `zephir_addcslashes` is not found in headers.

**Comment by sjinks** [comment]
It looks like the code was copied'n'pasted from `AddslashesOptimizer`:

```php
        if (count($expression['parameters']) > 1) {
            return false;
        }
```

In PHP, `addcslashes()` expects two parameters.

**Comment by sjinks** [comment]
@sergeyklay what do you think if I remove this optimizer, as it does not work anyway?

**Comment by sergeyklay** [comment]
How it works (I hope): https://github.com/phalcon/cphalcon/blob/master/phalcon/db/dialect/mysql.zep#L206

**Comment by sjinks** [comment]
No idea… `git grep` cannot find `zephir_addcslashes()`

**Comment by sjinks** [comment]
Ah, I know. That call has two parameters, the optimizer can handle only one.

**Comment by sjinks** [comment]
```c
ZEPHIR_SINIT_NVAR(_8$$10);
ZVAL_STRING(&_8$$10, "\"", 0);
ZEPHIR_CALL_FUNCTION(&_9$$10, "addcslashes", &_10, 150, defaultValue, &_8$$10);
```
