### ISSUE TITLE
Detect debug when building

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1520]
I have a small idea, sometimes i forgot to write builddev when i need to, how about:

- detect if we have php compiled as debug
- if yes then `zephir build` will always build extension with debug symbols(just `zephir builddev`)
- if not then as it is
- add `zephir buildprod` so someone can build extension without debug symbols anyway

**Comment by sjinks** [comment]
```php
if (PHP_DEBUG) {
// ...
}
```

`PHP_DEBUG` constant is available since PHP 5.2.7

**Comment by sergeyklay** [comment]
Implemented in the 0.11.x branch
