### ISSUE TITLE
Casting resource to int

### ISSUE THREAD

**Issue by maciejmrozinski** [zephir-lang/zephir#1524]
Hi,

Found an unexpected result when casting resources to ints (common thing in PHP):

```
    var key;
    let key =  (int) stream; //stream is resource #127
    echo $key;
```

Expected:
`127`
Current:
`1`

I always receive `1` instead of resource id. `intval` is also not working. `strval` gets `Resource id #127`

**Comment by sergeyklay** [comment]
Fixed in the `0.10.11` version. Thank you for the report, and for helping us make Zephir better.
