### ISSUE TITLE
Extending class with static is changing null value

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1536]
When extending zephir class which has static field it's changing it's value from `NULL` to `&NULL` in php 7 and 7.1, for php 5.5 and 5.6 it works fine.

Related PR with test - https://github.com/phalcon/zephir/pull/1535

@sjinks

**Comment by Jurigag** [comment]
@sjinks Any idea ?

**Comment by Jurigag** [comment]
After trying to find root of it i reproduced it in php without zephir so i guess this is php bug, reported it already. For phalcon i will just change affected code.

**Comment by Jurigag** [comment]
They wrote it's not a bug so we should use `ZVAL_DEREF` somewhere.

**Comment by hakimio** [comment]
@Jurigag Can you link here the bug which you opened upstream?

**Comment by Jurigag** [comment]
https://bugs.php.net/bug.php?id=74648
