### ISSUE TITLE
Random Core Dumps on PHP 5.5(possibly 5.6 too)

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1542]
Some latest changes to zephir triggered somehow i think this bug in php - https://bugs.php.net/bug.php?id=64827 when running phalcon tests. I got two core dumps here:

https://pastebin.com/nMRHmf1k

Not sure what is causing it, it's not really reproducible, some times it runs fine, some times core dump and sometimes zend_mm_heap corrupted

**Comment by Izopi4a** [comment]
omg spend a hour thinking what i screw after updating my libs .. .

+1

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
