### ISSUE TITLE
Class "SoapClient" does not exist at compile time

### ISSUE THREAD

**Issue by sandeep048** [zephir-lang/zephir#1545]
I am planning to use zephir to create a php extension which needs to use SOAP REST API's.
Kindly let me know if I can use php standard classes in zephir-lang.

**Comment by sandeep048** [comment]
can I link php_soap.so library while compiling this zephir extension?

**Comment by sergeyklay** [comment]
You can provide prototype. In the configuration file:

```json
{
    "prototype-dir": {
        "soap": "prototypes/soap"
    }
}
```
Then you will need to create the SoapClient stub.

Another way is to provide [header files](https://github.com/php/php-src/tree/master/ext/soap). Also see [Extension Configuration File](https://docs.zephir-lang.com/en/latest/config.html).

**Comment by PcMaKeR** [comment]
Hi, I'm getting an error.

I try everyhing. What am I missing?

Platform: Windows 10.
PHP: 7.3.7
Zephir: 0.12.0

Error:
`PHP Fatal error:  Uncaught SoapFault exception: [Client] Error finding "uri" property in D:\Projects\admin\public\index.php:35
Stack trace:
#0 [internal function]: SoapClient->__call('__construct', Array)
#1 D:\Projects\admin\public\index.php(35): Common\WindowsApi->__construct('http://localhos...', Array)
#2 {main}
  thrown in D:\Projects\admin\public\index.php on line 35`

windowsapi.zep:
`namespace PxPanel\Common;

class WindowsApi
{
    private uri;
    private client;

    public function __construct(url, soapOptions){
        var sclient = "\\SoapClient";
        var_dump(url);
        var_dump(soapOptions);
        //var_dump(this->client);
        let this->client = new {sclient}(url,soapOptions); //error line
        // let this->client = new \SoapClient(url,soapOptions); //same error
        var_dump(this->client);
    }

    public function CallSoapApi(soapMethod, soapMethodParams) {
        /*var returnValue;

        let returnValue = this->client->__soapCall(soapMethod, ["parameters": soapMethodParams]);
*/
        return this->client;
    }
}`

php code:
`use Common\WindowsApi;
$sc = new WindowsApi('http://localhost/pxpanelapi/WebServerApi.svc?wsdl',['soap_version' => SOAP_1_1]);
var_dump($sc->CallSoapApi('AddWebsite',$params));`
