### ISSUE TITLE
Whether it is supported to import a static library(xxx.a) and invoke it's function.

### ISSUE THREAD

**Issue by ctrl-cli** [zephir-lang/zephir#1546]
Whether it is supported to import a static library(xxx.a) and invoke it's function.

If this support,how to configure.

**Comment by sergeyklay** [comment]
Actually there is no ability to import a static library.  I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by rabbitUdomly** [comment]
Still not supported?

**Comment by Jeckerson** [comment]
@rabbitUdomly https://docs.zephir-lang.com/0.12/en/config#extra-libs

**Comment by rabbitUdomly** [comment]
@Jeckerson Thanx, but in my case, he doesn't see the function from the static library. Is there a more detailed description of this somewhere? Ideally with an example.
