### ISSUE TITLE
How to change line when echo something?

### ISSUE THREAD

**Issue by ghost** [zephir-lang/zephir#1555]
In PHP, I use "\n" or "EOF" to change line. How to change line when echo something in Zephir?

**Comment by Jurigag** [comment]
https://forum.zephir-lang.com use forum for questions

**Comment by sergeyklay** [comment]
We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the Zephir, support requests, and questions like this please visit the [official forums](https://forum.zephir-lang.com).
