### ISSUE TITLE
get variable value using dynamic name

### ISSUE THREAD

**Issue by laurenti** [zephir-lang/zephir#1557]
How to get variable value using dynamic name. If I use :

```zep
var myHash_one = ["first": 1, "second": 2, "third": 3];
var nr = "one";
var qry;
let qry = "myHash_" . nr;
var_dump({qry});;   // ---> Segmentation fault (core dumped)
```

or

```
var s3;
let s3 = {qry};   // ---> Segmentation fault (core dumped)
```

When build extension I get 

> Segmentation fault (core dumped)

 error.

I use PHP 7.0.20 and ZEPHIR both 0.9.8 and 0.9.9

**Comment by sergeyklay** [comment]
Actually there is no ability to get value using dynamic name. I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.
