### ISSUE TITLE
zephir build doesn't create a dll, instead opens configure.js in Notepad++

### ISSUE THREAD

**Issue by ilhanyumer** [zephir-lang/zephir#1564]
I'm trying to build a dll file but it doesn't build any dll. I run this command: `zephir build`

Then the output is:
```
Preparing for PHP compilation...
Preparing configuration file...
```
And then it opens the `configure.js` in Notepad++. http://i.imgur.com/vBQiWSn.png And it stays like this forever. If I close the Notepad++ it prints 2 more lines and there is no dll http://i.imgur.com/Hssuc2b.jpg

### Details

* Everything is 64bit
* Zephir Parser => enabled
* Author => Zephir Team and contributors
* Version => 1.0.3
* Build Date => May 13 2017 15:03:23
* PHP 5.6.31 (cli) (built: Jul  5 2017 22:24:47)
* Copyright (c) 1997-2016 The PHP Group
* Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
* Microsoft Windows [Version 6.3.9600]
* Installation type: installing via package manager
* Visual Studio Ultimate 2012 with Blend
  * Blend for Visual Studio
  * LightSwitch
  * Microsoft Foundation Classes for C++
  * Microsoft Office Developer Tools
  * Microsoft SharePoint Developer Tools
  * Microsoft Web Developer Tools

compile-errors.log:

> Microsoft (R) Program Maintenance Utility Version 11.00.50727.1
> Copyright (C) Microsoft Corporation.  All rights reserved.
> 
> NMAKE : fatal error U1064: MAKEFILE not found and no target specified
> Stop.

The compile.log is empty.

**Comment by sergeyklay** [comment]
I apologize @ilhansubasi for completely overlooking this. Thank you for your report. FYI: I'm not a Windows user so often I find it hard to understand how to reproduce the issue. But now I have a Windows system and I hope things will go better. Is the issue still actual for you? So thanks again for the report, and again I am sorry about the delay.

**Comment by marcelto** [comment]
I have this same issue running PHP 7.2.7 nts, Windows 10 x64, zephir 0.10.10, Visual Studio 2017.

**Comment by marcelto** [comment]
Got past this with the following [https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/](https://www.winhelponline.com/blog/error-there-is-no-script-engine-for-file-extension-when-running-js-files/).  Ran into bison is required error only becuase I forgot to run `%PHP_SDK%\bin\phpsdk_setvars`.  Afterwards the dll generated.

**Comment by sayonara90s** [comment]
I have this same problem. @marcelto 's solution doesn't work for me. Makefile still not found. I hope this error is last.

**Comment by marcelto** [comment]
@mixinix check for Windows settings and ensure .js files are set to open with the Microsoft Windows Based Script Host.  I did this prior to running the registry fix.  Also, since this is Windows we're talking about, rebooting after your changes may not be a bad idea.

**Comment by Bushido2404** [comment]
@sayonara90s use visual studio command prompt it might help
