### ISSUE TITLE
How to call native c++ function

### ISSUE THREAD

**Issue by bsidhu009** [zephir-lang/zephir#1565]
How can i call c++ function and return output in zephir function 
here c++ function
std::string myoutput(const std::string& input)

**Comment by sjinks** [comment]
It's not a good idea to call a C++ function from C.

```c++
#include <cstring>
#include <cstdlib>

extern "C" {
char* myoutput_wrapper(const char* s)
{
    std::string r = myoutput(s);
    char* ret = static_cast<char*>(std::calloc(r.size() + 1), 1);
    if (ret) {
        std::memcpy(ret, r.c_str(), r.size());
    }

    return ret;
}
}
```

and then call `output_wrapper()` from Zephir. It will be your responsibility to `free()` the return value when you no longer need it.
