### ISSUE TITLE
php7.1.8 

### ISSUE THREAD

**Issue by Tinywan** [zephir-lang/zephir#1572]
##  error
```
www@tinywan1:~/php-zephir-parser$ zephir 
/usr/local/bin/zephir: 25: /usr/local/bin/zephir: php: not found
```

**Comment by sergeyklay** [comment]
Can you provide a bit more information and describe the error

**Comment by Tinywan** [comment]
@sergeyklay now Ok ,but cphalcon not build
+  PHP Version ： 7.1.8
+ [https://github.com/phalcon/cphalcon/issues/12476](https://github.com/phalcon/cphalcon/issues/12476)

**Comment by sergeyklay** [comment]
From the README:

> First, you have to get [Zephir Parser](https://github.com/phalcon/php-zephir-parser).

**Comment by Tinywan** [comment]
Installl 
```bash
sudo apt-get install php7.0-dev gcc make re2c autoconf
```
