### ISSUE TITLE
Operator 'concat-assign' is not supported for variable type: int

### ISSUE THREAD

**Issue by malios** [zephir-lang/zephir#1573]
Given the following code:

```zep
    namespace ExtTest;

    class Test
    {
        public static function test()
        {
            var a, b;
            let a = "1";
            let b = "2";
            let b .= a;
            return b;
        }
    }
```

I get the following compiler error:

```
Zephir\CompilerException: Operator 'concat-assign' is not supported for variable type: int in /path/to/project/test.zep on line 10

                let b .= a;
        -----------------^

Expected result: b = "21".
```

I think zephir compiler tries to cast a and b to integer which is odd, because php does do opposite for concat operations.

**Comment by malios** [comment]
I get similar compiler error for div-assign.
Code:

```zep
    public function div(int num)
    {
        var a;
        let a = 42;
        let a /= num;
        return a;
    }
```

The code compiles if I replace variable num with a constant number.

```zep
        var a;
        let a = 42;
        let a /= 7;
        return a;
```

**Comment by sergeyklay** [comment]
Fixed in the [latest stable release](https://github.com/phalcon/zephir/releases/tag/0.10.6). Feel free to open a new issue if the problem appears again. Thank you for contributing.
