### ISSUE TITLE
Error on zephir build on hello world documentation exxample

### ISSUE THREAD

**Issue by rodriguescr** [zephir-lang/zephir#1577]
Bellow the return of the command:

```
est-gnote extension # zephir build
Preparing for PHP compilation...
Preparing configuration file...
./configure: line 5222: syntax error near unexpected token `('
./configure: line 5222: `  $as_echo_n "(cached) " >&6'
Compiling...
Installing...
Zephir\CompilerException: Internal extension compilation failed. Check compile-errors.log for more information
```

```
est-gnote extension # cat compile-errors.log 
make: *** Nenhum alvo indicado e nenhum arquivo make encontrado.  Pare.
make: *** Nenhum alvo indicado e nenhum arquivo make encontrado.  Pare.
```

est-gnote extension # cat compile.log

The code i'm trying to compile:

```zep
namespace Extension;

class Teste
{

    public static function say()
    {
        echo "hello world!";
    }

}
```

**Comment by sjinks** [comment]
What are the versions of autotools and automake on the system where you build the extension?

**Comment by rodriguescr** [comment]
Hi,

```
est-gnote extension # apt version autotools-dev
20150820.1
est-gnote extension # apt version automake
1:1.15-4ubuntu1
```

**Comment by sergeyklay** [comment]
Can you check if you have **all the deps installed**?

* gcc
* make
* autoconf
* automake
* pkg-config

**Comment by rodriguescr** [comment]
Hi,

There's the output of the linux machine:

est-gnote gabriel # apt install gcc make autoconf automake pkg-config
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
autoconf is already the newest version (2.69-9).
automake is already the newest version (1:1.15-4ubuntu1).
gcc is already the newest version (4:5.3.1-1ubuntu1).
make is already the newest version (4.1-6).
pkg-config is already the newest version (0.29.1-0ubuntu1).
0 pacotes atualizados, 0 pacotes novos instalados, 0 a serem removidos e 0 não atualizados.

All of the dependencies are met and the packages updated.

**Comment by sergeyklay** [comment]
@rodriguescr Which PHP version do you use?

**Comment by rodriguescr** [comment]
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

**Comment by sergeyklay** [comment]
🤔  interesting.. Actually as you can see there is no problem with [building / compiling / testing](https://travis-ci.org/phalcon/zephir). I have to dig in this a bit more.

**Comment by rodriguescr** [comment]
I'm using this directly in my Linux Desktop, if you want to, i can make a Skype or Teamviewer session with you to check.

Skype: gabriel_rodrigues1
Email: gabriel@modulotrestecnologia.com.br

Thx in advance.

**Comment by sergeyklay** [comment]
@rodriguescr Could you please provide `re2c` version

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
