### ISSUE TITLE
Access to PHP $GLOBALS superglobal array

### ISSUE THREAD

**Issue by wisegoodvin** [zephir-lang/zephir#1580]
Is it possible to organize access to the superglobal $GLOBALS array, as to $ _POST, $ _GET, and others?

**Comment by Jurigag** [comment]
What you mean? From latest zephir it's organized - if you try access non existing super global then fatal error is thrown.

**Comment by wisegoodvin** [comment]
Really? I've got parser exception `Zephir\Parser\ParseException: Syntax error in D:\php\zephir\myext\app.zep on line 4` when i try to compile this:
```zephir
namespace Foo;
class App {
	public static function test(var val) {
		let GLOBALS["key"] = val;
	}
}
```
I think this is another error.

My system:
OS: Windows 7 x64
PHP: 7.1.6 x64
Zephir: 0.9.11 (git cloned 2017-09-21 from development branch)
Zephir parser: 1.0.3
VS: 2015 (cl.exe version 19.00.23918, link.exe version 14.00.23918.0)

**Comment by Jurigag** [comment]
It should be `_GLOBALS` i think.

**Comment by wisegoodvin** [comment]
The same error - parser

**Comment by sergeyklay** [comment]
@wisegoodvin Yes, there is no` _GLOBALS` support: https://github.com/phalcon/php-zephir-parser/blob/development/parser/scanner.re#L596-L637. Do we really need this in Zephir?

**Comment by wisegoodvin** [comment]
Ok, I probably did not wrote correctly:
What about access to Zend global symtable? Where PHP store their "global" variables.

Example:
index.php (main web server page)
```php
<?php
$foo = "bar";
MyExt::vartest(); // in that method i need to change $foo variable
// and create new var, called $test with some val
echo $foo . $test; // and access to it
?>
```

But now in zephir i can't do this.
Later I will try to publish a snippet of the php extension code that it does.
Если опять не понятно выразился - могу на русском написать.

**Comment by flyingangel** [comment]
You can try another approach
```
<?php
$foo = "bar";
$test = MyExt::vartest($GLOBALS); // $GLOBALS['foo'] = xx; return $test;
// and create new var, called $test with some val
echo $foo . $test; // and access to it
?>
```

**Comment by sergeyklay** [comment]
I want to close this issue because I don't want a bunch of these lying around. I'd like to add support for anything/everything at some point, but keeping the issue open doesn't help that. :) If anyone wants to get started, I'd love that.

**Comment by erycson** [comment]
I was able to access $GLOBALS as described below, but I noticed that some variables created in Zephir using GLOBALS are not being reflected in PHP

Versions: Zephir 0.12.20 and Zephir Parser 1.3.6

File: zephir.patch
```
diff --git a/Library/Variable/Globals.php b/Library/Variable/Globals.php
index b31c5bf1..511971ac 100644
--- a/Library/Variable/Globals.php
+++ b/Library/Variable/Globals.php
@@ -22,6 +22,11 @@ class Globals
      * The variables passed to the current script via the URL parameters.
      */
     const GET = '_GET';
+	
+    /**
+     * References all variables available in global scope
+     */
+    const GLOBALS = 'GLOBALS';
 
     /**
      * The variables passed to the current script via the HTTP POST method.
@@ -73,6 +78,7 @@ class Globals
         self::SESSION => 1,
         self::REQUEST => 1,
         self::FILES => 1,
+        self::GLOBALS => 1,
     ];
 
     /**

```

File: php-zephir-parser.patch
```
diff --git a/parser/scanner.re b/parser/scanner.re
index bc8125f..9e8d193 100644
--- a/parser/scanner.re
+++ b/parser/scanner.re
@@ -608,7 +608,12 @@ int xx_get_token(xx_scanner_state *s, xx_scanner_token *token) {
 				token->len = YYCURSOR - start;
 				s->active_char += (YYCURSOR - start);
 			}
-
+			
+			if (!strcmp(token->value, "GLOBALS")) {
+				token->opcode = XX_T_IDENTIFIER;
+				return 0;
+			}
+				
 			if (token->len > 3 && token->value[0] == '_') {
 
 				if (!strcmp(token->value, "_GET")) {

```
