### ISSUE TITLE
Compilation error on 'zephir_bitwise_xor_function'

### ISSUE THREAD

**Issue by wisegoodvin** [zephir-lang/zephir#1581]
I'm try to compile that code:
```zephir
namespace Foo;
class App {
	public static function getInt(int num) { return num; }
	public static function bitwiseXorTest() {
		var i = self::getInt(123), j = self::getInt(321);
		return i ^ j;
	}
}
```
and after executing `zephir compile` i've got... nothing:
> Preparing for PHP compilation...
Preparing configuration file...
Compiling...

... and that error in `compile-errors.log`:
```
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe" : returned code "0x460"
Stop.
```
Then i try to `cd ext` and `nmake`, then i've got that error:
```
Creating library D:\php\zephir\myext\ext\x64\Release_TS\php_myext.lib and object D:\php\zephir\myext\ext\x64\Release_TS\php_myext.exp
app.zep.obj : error LNK2001: unresolved external symbol "zephir_bitwise_xor_function"
D:\php\zephir\myext\ext\x64\Release_TS\php_myext.dll : fatal error LNK1120: unresolved external elements: 1
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\link.exe" : returned code "0x460"
Stop.
```

OS: Windows 7 x64
PHP: 7.1.6 x64
Zephir: 0.9.11 (git cloned 2017-09-21 from `development` branch)
Zephir parser: 1.0.3
VS: 2015 (cl.exe version 19.00.23918, link.exe version 14.00.23918.0)

**Comment by sergeyklay** [comment]
Fixed in the [latest stable release](https://github.com/phalcon/zephir/releases/tag/0.10.2). Feel free to open a new issue if the problem appears again. Thank you for contributing.
