### ISSUE TITLE
Compiling Zephir file into C

### ISSUE THREAD

**Issue by Jammmmm** [zephir-lang/zephir#1593]
Is it possible to take a Zephir file (.zep) and convert to C source?

I have the Windows PHP extension (from https://github.com/phalcon/php-zephir-parser/releases/tag/v1.1.0), but I don't see any way of converting into C code.

If a Zephir binary is required, are there prebuilt Windows binaries available?

**Comment by Jurigag** [comment]
You need zephir parser https://github.com/phalcon/php-zephir-parser first to install and add it as extension to php.

To have just C source you need to do `zephir generate` after installing both zephir parser and zephir.

Zephir parser is just parser. It doesn't generate C code. This repo does that.

**Comment by Jammmmm** [comment]
As I said, I've added the extension to PHP, and I've tested to ensure that works fine (zephir_parse_file () works).

I don't have a "zephir" command though, which is why I was asking if a prebuilt Windows binary exists.

Is the only way to get this command to build php-zephir-parser from scratch?

Alternatively, and probably a better option, is there a function in the PHP extension to generate the C source? eg. zephir_generate_c () ?

**Comment by Jurigag** [comment]
https://github.com/phalcon/zephir/blob/development/WINDOWS.md

Did you even care to read?

**Comment by Jammmmm** [comment]
I did read. The page details how to build the binary, hence why I asked "are there prebuilt Windows binaries available"

So no prebuilt Windows binary exists. Gotcha.

**Comment by Jurigag** [comment]
What you mean by windows binary? There is no binary of zephir at all. It's php code only + c code which is included in every extension(kernel) - this repo  + parser - zephir-praser repo.

Not sure what you mean by binary.

**Comment by Jammmmm** [comment]
"zephir generate" implies there's a command involved, which is why I initially thought it would need to be built.

I've checked the repo and have found a "bin" directory that contains "zephir" and "zephir.bat". I didn't know that zephir was not something that needed to be built, but instead was interpreted itself.

Sorry for the confusion.
