### ISSUE TITLE
Duplicate extension key prefix in the global configuration

### ISSUE THREAD

**Issue by aiddroid** [zephir-lang/zephir#1604]
Here is the config.json
```js
{
    "namespace": "utils",
    "name": "utils",
    "description": "An utils helper extension",
    "author": "aiddroid",
    "version": "0.0.1",
    "verbose": false,
    "requires": {
        "extensions": []
    },
    "globals": {
        "utils.enable_cache": {
            "type": "bool",
            "default": true
        }
    }
}
```
but got "utils.utils.enable_cache" in phpinfo().
<img width="978" alt="phpinfo" src="https://user-images.githubusercontent.com/3241146/32821231-f2d9b916-c997-11e7-808b-f36ea378c770.png">

and after I removed the "utils" prefix from globals section in config.json, The key became "enable_cache" in phpinfo().It's very strange.
![image](https://user-images.githubusercontent.com/3241146/32821339-678449b6-c998-11e7-96d3-313b3cbb41e4.png)

**Comment by aiddroid** [comment]
<img width="978" alt="phpinfo" src="https://user-images.githubusercontent.com/3241146/32821215-df089646-c997-11e7-927a-f7ec69c38fd3.png">

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Thank you for contributing
