### ISSUE TITLE
array_search invalid position when contain zero(int|string) value.

### ISSUE THREAD

**Issue by pentagonal** [zephir-lang/zephir#1609]
```zephir
namespace Test;

class Test
{
    public function __construct()
    {
        // ----- start code point

        // string|int -> 0
        array itoA64 = [".", "/", "0", "1", "2", "3", "4", "value", "OtherValue"];

        // ----- start code execute
        
        // expected result must be -> int(7)
        var pos = array_search("value", itoA64);
        // returning -> int(2)
        var_dump(pos);
        // expected result must be -> int(8)
        let pos =array_search("OtherValue", itoA64);
        // returning -> int(2)
        var_dump(pos);
    }
}

```

Using:
- zephir : [0.10.6](https://github.com/phalcon/zephir/tree/0.10.6)
- Linux Mint (Ubuntu)
- Php (CLI) `5.6`, `7.0`, `7.1`
- GCC `gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)`

No `extra-sources`, `prototype` or additional `C` files include.

even though the key for zero value has `A` it will be return key name `A` of zero value.

**Comment by Jurigag** [comment]
This is really strange, when removing 0 it works.

**Comment by sergeyklay** [comment]
@pentagonal 
Actually as workaround you can use something like that:
```zep
string zero = "0";
array itoA64 = [".", "/", zero, "1", "2", "3", "4", "value", "OtherValue"];

var pos = array_search("value", itoA64);
```

I'll try to sort out as soon as I can

**Comment by sergeyklay** [comment]
@pentagonal Could you please try development branch
