### ISSUE TITLE
zephir build : The Zephir Parser extension is not loaded

### ISSUE THREAD

**Issue by vmohanraaj** [zephir-lang/zephir#1614]
I am using Ubuntu16.10 (64 bit), and I followed steps as per the documentation https://docs.zephir-lang.com/en/latest/tutorial.html .
Zephir version 0.10.6-0b7210d4f6

While 
```
admin@ubuntu:~/utils$ zephir build


────────────────────────────────────────────────────────────
  The Zephir Parser extension is not loaded.
  Note: Zephir no longer distributed with internal parser.
  
  To install latest stable Zephir Parser please refer to:
  https://github.com/phalcon/php-zephir-parser
────────────────────────────────────────────────────────────
```
I am getting above message, And also I have installed **zephir-parser** as per the steps given in https://github.com/phalcon/php-zephir-parser. And I verified in phpinfo(), zephir-parser is loaded.

And my system config is:
```
admin@ubuntu:~$ php -v
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

admin@ubuntu:~$ phpize -v
Configuring for:
PHP Api Version:         20151012
Zend Module Api No:      20151012
Zend Extension Api No:   320151012

admin@ubuntu:~$ uname -a
Linux ubuntu 4.4.0-103-generic #126-Ubuntu SMP Mon Dec 4 16:23:28 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux


admin@ubuntu:~$ php -i | grep extension_dir
extension_dir => /usr/lib/php/20151012 => /usr/lib/php/20151012
admin@ubuntu:~$ ls /usr/lib/php/20151012/zephir*
zephir_parser.so

```
Kindly fix this issue.

**Comment by sergeyklay** [comment]
You have to install/enable Zephir Parser for CLI SAPI. Could you please provide output of:
```
php --ri "Zephir Parser"
```

**Comment by vmohanraaj** [comment]
Thank God and @sergeyklay. 
Before that I got 
 `admin@ubuntu:~$ php --ri "Zephir Parser"
Extension 'Zephir Parser' not present.`

Now added the line
 ```ini
[Zephir Parser]
extension=zephir_parser.so
```
to **/etc/php/7.0/cli/php.ini**. 

Its now working. 
You saved me lot.
Happy Zephir coding.
This answer will definitely helpful to many people in world for those who are all facing same kind of issue.
