### ISSUE TITLE
require statement breaks local variable scope

### ISSUE THREAD

**Issue by zacek** [zephir-lang/zephir#1621]
There is some problem in the code zephir generates for requirement statement in PHP 7. Local variable values overwrite global variables when require statement is used (the required file can be empty).

Minimalistic example is attached. The render method in the example extension class is inspired by Phalcon\Mvc\View\Engine::render(). Thus, this bug causes problems with volt template rendering in Phalcon.

**Components versions**
* zephir builder: v1.1.2 (latest development version f3afc60 tested too)
* zephir: 0.10.7 (latest development version 8059e66 tested too)
* PHP: 7.0.25 (latest ubuntu 17.10 version 7.1.11 tested too)

**How to reproduce:**
1) create simple extension (`zephir init mira`) and copy this `mira.zep` file in it:
```zephir
namespace Mira;

class Engine
{
    public function render(string! templatePath, var params)
    {
	var key, value;

	if typeof params == "array" {
	    for key, value in params {
		let {key} = value;
	    }
	}

        require templatePath;
    }
}
```
build it (`zephir build`), install `mira.so`, create `mira.ini` and enable it (`phpenmod mira`).

2) create file mira.php:
```php
<?php
$engine = new \Mira\Engine();

$a = 1;
$engine->render('mira2.php', ['a' => 2]);

// expected output: $a == 1
print 'a == ' . $a;
```
and an empty file `mira2.php`

3) run
`php mira.php`
The result displayed is 'a=2' which means that the `$a` variable has been overwritten in the `Engine::render()` call.

**Note:** If you comment out the line with the require statement in the Engine extension the variable `$a` is _not_ affected.

All the example files can be found in the attached [demo.zip](https://github.com/phalcon/zephir/files/1775275/demo.zip).

-------

### Refs

- https://github.com/phalcon/zephir/pull/1488
- https://github.com/phalcon/zephir/issues/1403
- https://github.com/phalcon/cphalcon/issues/12176
- https://github.com/phalcon/cphalcon/issues/12648
- https://github.com/phalcon/cphalcon/pull/13288
- https://github.com/phalcon/cphalcon/issues/12385

**Comment by zacek** [comment]
I've added workaround for `\Phalcon\Mvc\View\Engine\Volt` to https://github.com/phalcon/cphalcon/issues/12176

**Comment by sergeyklay** [comment]
@zacek Could you please explain a bit more. Is there any code example?

**Comment by zacek** [comment]
This defect affects the Phalcon volt template engine - variables assigned in the template, e.g.
```
$this->view->param = 'value'; 
```
overwrite local `$param` variable when the page gets rendered.

As this defect seems to be quite difficult to fix I've published my workaround in the related defect for those who need the fix ASAP. The fix is just to move the problematic code (method `render()`) from Volt class in zephir to PHP. This seems to work properly. So whoever needs to use the volt templating and cannot wait for the fix can simply extend the `Volt` class as proposed in the workaround and use the extended class.

**Comment by zacek** [comment]
the code of the extended class is in my last comment to this defect: phalcon/cphalcon#12176
I've mentioned it here just for completeness as this defect (in zephir) is the root cause of the problem in the Volt class (in cphalcon).

**Comment by sergeyklay** [comment]
As I know @AlexNDRmac tries to sort out in these days.

**Comment by Jurigag** [comment]
@AlexNDRmac any progress ?

**Comment by AlexNDRmac** [comment]
Yes... I have some little progress. Now I trying to implement symbol table.

**Comment by dschissler** [comment]
@sergeyklay You closed my other issue but it is not the same.  You broke usage using `phar://` protocol when called from within a phar between version 0.10.11 and 0.10.12.  This is recent new breakage.  That said, if you fix it all at once then great.

**Comment by sergeyklay** [comment]
Fixed here:

- 0.11.6: https://github.com/phalcon/zephir/releases/tag/0.11.6
- 0.10.13: https://github.com/phalcon/zephir/releases/tag/0.10.13

Thank you for the report, and for helping us make Zephir better.
