### ISSUE TITLE
ZEPHIR_CALL_CE_STATIC_ZVAL is missing in ZendEngine3

### ISSUE THREAD

**Issue by xEsk** [zephir-lang/zephir#1622]
The **ZEPHIR_CALL_CE_STATIC_ZVAL** macro is missing in **fcall.h** (ZendEngine3), causing this error when trying to execute the extension:

>dyld: lazy symbol binding failed: Symbol not found: _ZEPHIR_CALL_CE_STATIC_ZVAL
>  Referenced from: ObjectFoundation/Lib/foundation-php71.so
>  Expected in: flat namespace

I'm using the latest zephir (development) version.

**Comment by sergeyklay** [comment]
@xEsk Could you please provide minimal code to reproduce

**Comment by xEsk** [comment]
```php
class Test1
{
    public static function foo()
    {
        return "hello";
    }
}
```
Simple test code:
```php
var aClass = "Test1";
var method = "foo";
echo {aClass}::{method}();
```

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.

**Comment by xEsk** [comment]
Great! Good job! :)
