### ISSUE TITLE
Allow nullable parameter

### ISSUE THREAD

**Issue by flyingangel** [zephir-lang/zephir#1639]
Like disabling automatic conversion `string! text` https://docs.zephir-lang.com/en/latest/oop.html#strict-flexible-parameter-data-types

Automatic conversion failed for `array`, maybe we can allow nullable parameter?
`function myfunc(array? arr) -> array?`
http://php.net/manual/fr/migration71.new-features.php

**Comment by Jeckerson** [comment]
Already implemented. Just use `function(array param = null)`
