### ISSUE TITLE
zephir build problem

### ISSUE THREAD

**Issue by jiujiucheng** [zephir-lang/zephir#1652]
when i use **zephir build** ，the problem happens:

PHP Fatal error:  Cannot declare class Phalcon\Di, because the name is already in use in /opt/src/zephir/prototypes/phalcon.php on line 4

Fatal error: Cannot declare class Phalcon\Di, because the name is already in use in /opt/src/zephir/prototypes/phalcon.php on line 4

any one help me to fix it?

**Comment by danhunsaker** [comment]
I'll be submitting a fix for this soon. What's going on is you're somehow loading the compiler twice (at least), and it's using a `require` where it should be a `require_once`. I'm not sure how this would come about in a regular `zephir build`, but with any luck it should be fixed fairly soon.

**Comment by jiujiucheng** [comment]
I found the compiler.php  on line: 862
```
$extension = str_replace('.php', '', $file);
	if (!extension_loaded($extension)) {
			require $file->getRealPath();				
	}
````
when i change _require_  to _require_once_,it is not working. so i check my php extension,
 
```
php -m | grep phalcon
phalcon7
```
It is **phalcon7** but not phalcon ,it is so confusing ... @danhunsaker ,shout it be a bug to fix?

**Comment by sergeyklay** [comment]
@zhangyaohui1986 The `phalcon7` is not an official Phalcon Framework. Just disable it or create your own `phalcon7.php` optimizer
