### ISSUE TITLE
Error build

### ISSUE THREAD

**Issue by tumour** [zephir-lang/zephir#1657]
Здравствуйте Сергей, извините, что на русском языке, я с ошибками пишу на английском).
Вообще у меня проблемы установки zephir.

The Zephir Parser extension is not loaded.
Note: Zephir no longer distributed with internal parser.
  
To install latest stable Zephir Parser please refer to:
https://github.com/phalcon/php-zephir-parser

Постоянно пишет эту ошибку. Расширение Zephir Parser стоит. В phpinfo() оно есть.
Ставлю zephir по документации, не каких левых советчиков не слушал. 
Все ровно с сайта https://zephir-lang.com/

Использую php 7.2, ubuntu 16.04, composer, вообще все, что нужно.
Помогите пожалуйста =)

**Comment by sergeyklay** [comment]
@tumour Я почти всегда обитаю в нашем Discord чатике. Если есть срочный вопрос, можно связаться через https://phalcon.link/discord
