### ISSUE TITLE
Segmentation fault when using $return_value

### ISSUE THREAD

**Issue by jgmdev** [zephir-lang/zephir#1660]
If declaring a function that returns bool with a return variable named $return_value the generated extension crashes.

```php
namespace Test;
class SomeTest
{
    public static function bug() -> bool
    {
        bool $return_value = true;
        return $return_value; /*Segfault*/
    }
}
```
It seems the generated code conflicts with the return_value variable declared by the zend engine for all functions. Took me a long debugging session to figure this out...

**Comment by danhunsaker** [comment]
Oops. Yeah, that would certainly cause issues. Time to decide how to handle this one.

- Forbid using that variable name, as a reserved keyword.
- Detect variables with that name, and rename them internally.
- Throw a warning that there's a conflict there, but allow it anyway, in case the user knows the value's purpose and wants to take advantage of it being exposed.
- Some combination of those, probably selected via configuration of some kind.

Thanks for the heads up!

**Comment by jgmdev** [comment]
I think the best option would be the second one "Detect variables with that name, and rename them internally."

**Comment by ruudboon** [comment]
@sergeyklay I think we can close this one?

**Comment by sergeyklay** [comment]
Yes. This is fixed. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
