### ISSUE TITLE
Class or var names with only capitalized letters makes compilation fails

### ISSUE THREAD

**Issue by mikachou** [zephir-lang/zephir#1668]
For instance if my class name is RBF, then declare
```class RBF```
makes the compilator fails when i launch `zephir build`, but not if my class name is RbF or rBF.

The same thing occurs with vars, for instance : I can name a var Lu, or LuL, but not LU. I cannot have a variable name which is A because `zephir build` fails

**Comment by mikachou** [comment]
I forgot to precise : the same error message is displayed with error : 
```
Syntax error in xxx/yyy on line zzz
class RBF
--------^
```

**Comment by danhunsaker** [comment]
Hmm. We may have classified all-uppercase names as reserved for constants. If that's the case, this is expected behavior, but should be documented...

**Comment by sergeyklay** [comment]
@mikachou It is common parser issue - using all-uppercase names.

**Comment by sergeyklay** [comment]
This issue was moved to phalcon/php-zephir-parser#39
