### ISSUE TITLE
any preg_match equivalent? 

### ISSUE THREAD

**Issue by streetlist** [zephir-lang/zephir#1672]
any preg_match equivalent? it's quite limited without some regex features / functionality to the language.

**Comment by danhunsaker** [comment]
You have full access to any PHP function you need/like. There's additional overhead involved, but Zephir will automatically call into PHP to use them.

**Comment by Jurigag** [comment]
? I don't understand, you can use preg_match. https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/router.zep#L451

**Comment by navisoft** [comment]
@streetlist I don't see any equivalent of preg_match function. Using it like PHP function.

**Comment by danhunsaker** [comment]
Yes. You can use any PHP function you like. So just use PHP's `preg_match`.

**Comment by Jurigag** [comment]
I just linked you to the same usage of preg_match like in php in phalcon. Not sure what other problems you have.
