### ISSUE TITLE
Can zephir support rewriting or hooking php's built-in function?

### ISSUE THREAD

**Issue by phith0n** [zephir-lang/zephir#1680]
Can zephir support rewriting or hooking php's built-in function, or are you going to do it in future?

**Comment by danhunsaker** [comment]
Not certain I properly understand this question. What I'm seeing, here, is that you want to replace functions provided elsewhere in PHP with your own, or at least be able to intercept calls to those functions to do other things instead/before/after?

I'm not sure whether that's possible...

**Comment by phith0n** [comment]
Yes, your understanding is correct.

With this feature, I can modify the built-in function, extend the web application without editing the php code.

I see that there was a extension runkit, supported this feature: http://php.net/manual/en/function.runkit-function-redefine.php

But it is no longer maintained, so I want to know if you support it.

**Comment by danhunsaker** [comment]
I don't believe we do. We might be able to look into it at some point, though, or perhaps someone enterprising could pick up runkit maintenance.
