### ISSUE TITLE
Improved Error Output Color

### ISSUE THREAD

**Issue by dschissler** [zephir-lang/zephir#1703]
The current yellow output color for error messages sucks donkey balls.  I have a new Dell XPS and the screen can be incredibly bright and the transition between white and black backgrounds seems intense enough to be damaging to my eyes and I have a contrary interest in preserving my hawk like vision well into old age.  So I'm using all whitish backgrounds and this brings me to the donkey ball suckage of the current yellow color.  This is not good and its approaching near impossible to read.  Before I even changed to a black background on my dim screened Thinkpad just to be able to use Zephir.  Things could be better.

**Comment by dschissler** [comment]
The Solarized theme is a good compromise between a light background and being able to see the error messages.  It should definitely be able to just work on a default white terminal though.

**Comment by dschissler** [comment]
I think that simply changing the yellow to the orange that you use when displaying *" ! [NOTE] Don't forget to restart your web server"* would be ideal.  Any chance that you can find the time to fit in this very small quality of life improvement?

**Comment by sergeyklay** [comment]
@dschissler Yes, this is exactly what i want to do. Sorry, too much painstaking replacement in many places. I will do it gradually

**Comment by sergeyklay** [comment]
@dschissler The compiler's messages was divided into streams in the `development` branch. Thus, now it is possible to redirect compiler's output as follows:
```sh
zephir generate 2> errors.log 1> /dev/null 
```

I would like to remove coloring for _compiler output_ at all because it is just a markup that will remains in the file after the redirection, eg:
```
$ cat errors.log
\033[0;31mSome compiler's message\033[0m
```

This will not affect to standard commands' output.

**Comment by dschissler** [comment]
You can do fancy stuff with [posix_isatty](http://us2.php.net/manual/en/function.posix-isatty.php) to then strip the colors but that seems like a waste of time considering how much work Zephir needs.  Also it would hurt platform compatibility.

**Comment by sergeyklay** [comment]
Yes. So I propose think about coloring for compiler output as a low priority feature that may be implemented or not.

**Comment by dschissler** [comment]
Good enough.  Don't even consider this until you've spent half a year adding operators and language structure.
