### ISSUE TITLE
makefile fatal error while trying to build zephir

### ISSUE THREAD

**Issue by fire-falcon** [zephir-lang/zephir#1708]
I have installed zephir on Windows 7, where I am uisng XAMPP as a web server. It's all working. But when I try to execute command `zephir build` in my project, it's giving the following error in `compile_errors.log` file:

`makefile(23) : fatal error U1001: syntax error : illegal character '{' in macro`

I am using Visual Studio Command Prompt.

What are my options here? 

When I tested the `zephir build` command with simple Hello World tutorial, it worked perfectly and generated my `.dll` file.

Any help would be appreciated. Thanks in advance.

**Comment by sergeyklay** [comment]
@fire-falcon Could you please provide full log/output? Please use something like http://vpaste.net for this

**Comment by fire-falcon** [comment]
@sergeyklay  This is my full log from compile_errors.log file:
[full log](http://vpaste.net/0ZJxu)

**Comment by sergeyklay** [comment]
Hmm.. I'm sorry but this is not enough. Could you provide `config.w32` I'll try to sort out

**Comment by fire-falcon** [comment]
@sergeyklay  config is [here](http://vpaste.net/isKie)

**Comment by sergeyklay** [comment]
@fire-falcon Could you provide PHP version?

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
