### ISSUE TITLE
0.10.12 broke "require" call while running in a phar archive and other concerns about "require" changing for a future Phalcon 3 LTS bugfix version.

### ISSUE THREAD

**Issue by dschissler** [zephir-lang/zephir#1713]
@sergeyklay 

My VM is a standard Ubuntu 18.04, PHP 7.2, latest zephir parser extension, latest Phalcon 3 LTS.

I see that 0.10.12 advertised as initial PHP 7.3 support.  Something changed between 0.10.11 and 0.10.12 that breaks the "phar://" protocol from working correctly when called from zephir code that is run in [initiated from] a phar.  I've tested it twice now after switching back and forth, deleting the extension cache directories each time.

I know that the behavior of Zephir `require` has never worked the same/correctly in PHP 7 as it did in PHP 5, but whatever you did to to improve this has now broken phar use within zephir.

I'm concerned that also the behavior of the `require` has changed for the stable branch of Phalcon 3, because it never worked correctly and if you have now fixed it in Zephir then there could be different behavior for someone's Phalcon 3 setup (even if now possibly correct and broken before).  I see that a new Phalcon 3 has not yet been released, so that is a good thing IMO.

I encourage you to set aside the `0.10.11` zephir branch as **possibly** (not certainly) the zephir version that is most compatible with how things have been done.  I don't believe that it was correct to have made whatever changes you made on a "bugfix" version of zephir but to have instead created the 0.11.0.

I believe that considering how broken the `require` has been for the entire life of Phalcon 3 that even fixing it at the very end of its support is the incorrect thing to do, since it changes behavior.

**Comment by dschissler** [comment]
For now I'll beusing the latest Zephir and ignoring this one broken aspect for now and when I need to be working with phars then I'll revert to the `0.10.11` version.

**Comment by dschissler** [comment]
Additionally I've discovered that the implementation of Zephir `require` is quite odd in that if it fails to find a file then it will immediately halt the current method and then it will return a null to the previous method.  I see that Phalcon has also needed to write some odd code to work around this, (if you are aware of that or not).  I think that some more sane behavior should take place there like for starters not halting the calling function immediately if the file doesn't exist.  Or if it does halt then halt the entire program or something sane like that so that a file check would need to be called first (I don't prefer this option but its at least understandable).  Its just very odd non-intuitive hacky behavior as it is now.  Then its behavior when used for templating is broken (there is a bug around here somewhere) and now its broken when used in phar.  It sounds to me like `require` could use a complete overhaul.  Perhaps that is what you have been working on, I have no idea.

**Comment by dschissler** [comment]
After thinking about it I think that I prefer that `require` halts if it can't load the file, possibly throwing a low level exception.  This is in line with PHP and the "require" word.  You'd probably have to write new code to get it to work like.  Probably the current behavior could be salvaged for use for a `include` language feature.

**Comment by dschissler** [comment]
Related bug with `require`: [#1621](https://github.com/phalcon/zephir/issues/1621).

**Comment by sergeyklay** [comment]
This issue has been around for about two years. All us well know (and long ago) about it. @AlexNDRmac  and I are involved in solving this bug.

**Comment by sergeyklay** [comment]
@dschissler Could you please provide code to reproduce? I need the code that did work previously. Also please provide exact worked Zephir version.

**Comment by dschissler** [comment]
I'm sorry but my extension code is not yet public and the setup required is too much.  Simply `0.10.11` works and `0.10.12` does not work for zephir code doing a `require` call on something stored within the phar archive (so using `phar://` protocol).  That is the best that I can provide at the moment.

**Comment by sergeyklay** [comment]
I'll try to figure it out, but if just `require phar:///tmp/1.phar` is not enough I can't fix it without a code to reproduce. And I strongly doubt that this issue and  #1621 are different problems.

**Comment by dschissler** [comment]
Perhaps its a protocol issue? Try `require "file:///asdfasdf"` (file system protocol).

But called via unoptimized string of course.

**Comment by sergeyklay** [comment]
@dschissler Do you need a patch for the 0.10.x branch or the 0.11.x is satisfied your needs?

**Comment by dschissler** [comment]
@sergeyklay The latest `development` branch source works with with the phar so the revert worked.  Thanks.

I'm liking the new zephir direction and I was never a fan of the old kind-of-broken install methods.  However, I had a problem with `zephir build`:

```
dschissler@host:/opt/project$ zephir build

                                          
  The "--backend" option does not exist.  
                                          

build [--backend BACKEND] [--dev] [--no-dev]
```

I was able to get it working by using `zephir compile` and then `sudo zephir install`.

**Comment by dschissler** [comment]
It would be really nice if zephir could only use `sudo` on the specific necessary commands like most projects.  It would be great if for example I could just type `zephir install` and it would call `sudo` only at the one relevant command instead of running the entire script as sudo.  It seems to me that most projects do that.  The same with `zephir build` in that it can compile without root and then only needs root for the installation copy portion.

**Comment by sergeyklay** [comment]
@dschissler 

> The "--backend" option does not exist.  

It is the bug. Open please an issue. I'll fix it asap.

> It would be really nice if zephir could only use sudo on the specific necessary commands like most projects. 

I constantly forget about the sudo... Please open a new issue so that I do not forget about it. I'll try to deal with this in the near future
