### ISSUE TITLE
PHP Warning:  require_once(/root/zephir/vendor/autoload.php): failed to open stream: No such file or directory in /root/zephir/compiler.php on line 14

### ISSUE THREAD

**Issue by thinkeng** [zephir-lang/zephir#1714]
PHP Warning:  require_once(/root/zephir/vendor/autoload.php): failed to open stream: No such file or directory in /root/zephir/compiler.php on line 14

**Comment by sergeyklay** [comment]
@niuxiongwen Could yoi please provide Zephir version and steps to reproduce

**Comment by danhunsaker** [comment]
Following the old install instructions would do this. Running the `install` script without first running `composer install`, specifically, would do this. It might be helpful to add the `composer install` step to the `install` script itself?

**Comment by sergeyklay** [comment]
Yeah, I think so
