### ISSUE TITLE
zephir build error

### ISSUE THREAD

**Issue by thinkeng** [zephir-lang/zephir#1716]
PHP Warning:  exec() has been disabled for security reasons in /root/zephir-0.11.2/Library/Compiler.php on line 1040
Preparing for PHP compilation...
PHP Warning:  exec() has been disabled for security reasons in /root/zephir-0.11.2/Library/Compiler.php on line 1043
Preparing configuration file...
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 150
PHP Warning:  file(/root/utils/.temp/0.11.2/gcc-version-temp): failed to open stream: No such file or directory in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 100
PHP Warning:  Invalid argument supplied for foreach() in /root/zephir-0.11.2/Library/Compiler.php on line 2352
PHP Warning:  exec() has been disabled for security reasons in /root/zephir-0.11.2/Library/Compiler.php on line 1053
Compiling...
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  file_get_contents(/root/utils/.temp/0.11.2/php-includes): failed to open stream: No such file or directory in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 121
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 146
PHP Warning:  exec() has been disabled for security reasons in /root/zephir-0.11.2/Library/Compiler.php on line 1074
Installing...
PHP Warning:  system() has been disabled for security reasons in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 150
PHP Warning:  file(/root/utils/.temp/0.11.2/gcc-version-temp): failed to open stream: No such file or directory in /root/zephir-0.11.2/Library/FileSystem/HardDisk.php on line 100
PHP Warning:  Invalid argument supplied for foreach() in /root/zephir-0.11.2/Library/Compiler.php on line 2352
PHP Warning:  exec() has been disabled for security reasons in /root/zephir-0.11.2/Library/Compiler.php on line 1156
Internal extension compilation failed. Check compile-errors.log for more information

**Comment by danhunsaker** [comment]
You won't be able to build extensions on secured systems, which are generally production systems anyway and should never be used for high load operations that aren't part of normal function.

In other words, the computer you're running this on is set up to disable certain functions that Zephir needs to do its thing. You'll need to re-enable them, but if you're building on a system used to host content on the wider Internet, that's a really bad idea, and you should use a different machine instead. Possibly a virtual machine on your own computer.
