### ISSUE TITLE
Consider dropping PHP 7.0 support for Zephir/Phalcon before Phalcon 4 is released

### ISSUE THREAD

**Issue by dschissler** [zephir-lang/zephir#1720]
Consider cutting PHP 7.0 support for the Phalcon 4.0 release.  Currently CentOS/RHEL only has PHP 5.4 and so an updated package would already be needed and its likely that they would skip straight to PHP 7.2.  It appears that Debian is the only significant distro that is back on specifically 7.0 and they will be releasing a new version with probably 7.2 by the middle of 2019.

If PHP 7.0 is dropped then its less conditionals in the code and more time to support future PHP versions and more possibilities for taking advantage of newer PHP internals.

[PHP Supported Versions](http://php.net/supported-versions.php)

It doesn't seem to me that you will be missing much by dropping PHP 7.0 for a mid 2019 release.  If CentOS was already on PHP 7.0 by default then I'd say that it was good reason to stay back but its already incompatible as it is now.

You will pay a maintenance and development cost for support 7.0 and I don't believe that you will get much out of it other than the marketing jingle "PHP 7".  You seem to have a lot of time now but what about tomorrow?  Something could happen in your life and then you will have very limited time.  Its better to think of the future IMO.

CentOS
PHP 5.4.16
https://distrowatch.com/table.php?distribution=centos

Debian
PHP 7.0.19
Debian 10 is expected around 2019-06
https://distrowatch.com/table.php?distribution=debian

Ubuntu 18.04
PHP 7.2.10
https://distrowatch.com/table.php?distribution=ubuntu

**Comment by dschissler** [comment]
I want to add that Phalcon 3 already supports PHP 7.1 and 7.2 so the more conservative people already have quite a lot of room to get onto recent PHP versions and they can continue using Phalcon 3 just the same.  Considering that Phalcon 4 will be coming off a Phalcon LTS I think that you have room to be edgier with this next release.

Look at this [article about PHP 7.1 features](https://blog.shameerc.com/2016/11/php-71-8-new-features-you-need-to-know). That looks like **a hell of a lot** of internal PHP changes to me.  Are you prepared to not be able to offer great new Zephir constructs and operators because you need to support PHP 7.0?

**Comment by danhunsaker** [comment]
The only version really tying our hands is 5.6, right now.

**Comment by dschissler** [comment]
Has anyone investigated the internals of PHP 7.0 vs 7.1 in terms of new operators?  How much actual investigation has gone into getting an idea of how to add newer features into modern PHP Zephir?  It seems to me that 97% of that work goes back to the Andres days of PHP 5 and that PHP 7.0 was just shoe horned in and left to bit rot.  I see it that PHP 7.0 was a pretty boring feature release but it had a radically new engine but PHP 7.1 brought in tons of new operators and language features.  I find it unlikely that none of those new code paths have any value.

**Comment by sergeyklay** [comment]
We will consider your proposal. Thank you for reaching out to us to point this.

**Comment by dschissler** [comment]
RHEL 8.0 beta is out and it supports PHP 7.2.

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8-beta/html-single/8.0_beta_release_notes/

**Comment by dschissler** [comment]
@niden @sergeyklay 

From the Phalcon blog:

> NOTE: This is the last release for the v3.x series. Our next version will only support PHP version 7.2 or later. If you are using PHP < 7.2 then you will need to use this version

Like a drunken philosopher prophet - this best kind.  If you want to know about the Wall then I'll break that down for you as well.
