### ISSUE TITLE
zephir build error

### ISSUE THREAD

**Issue by thinkeng** [zephir-lang/zephir#1727]
[root@localhost utils]# zephir build
Preparing for PHP compilation...
Preparing configuration file...
configure: error: Cannot find php-config. Please use --with-php-config=PATH
Compiling...
sh: php-config: 未找到命令
kernel/array.h:25:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/debug.h:25:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/exception.h:24:23: 致命错误：Zend/zend.h：没有那个文件或目录
 #include <Zend/zend.h>
                       ^
编译中断。
kernel/exit.h:22:23: 致命错误：Zend/zend.h：没有那个文件或目录
 #include <Zend/zend.h>
                       ^
编译中断。
In file included from ./php_utils.h:11:0,
                 from ./php_ext.h:4,
                 from kernel/fcall.h:24:
./kernel/globals.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/file.h:23:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/filter.h:23:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/globals.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/iterator.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/main.h:23:34: 致命错误：Zend/zend_interfaces.h：没有那个文件或目录
 #include <Zend/zend_interfaces.h>
                                  ^
编译中断。
kernel/math.h:23:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/memory.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/object.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/operators.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
In file included from ./php_utils.h:11:0,
                 from ./php_ext.h:4,
                 from kernel/require.h:24:
./kernel/globals.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/string.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/time.h:20:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/variables.h:24:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
kernel/concat.h:4:17: 致命错误：php.h：没有那个文件或目录
 #include <php.h>
                 ^
编译中断。
Installing...
Internal extension compilation failed. Check compile-errors.log for more information

**Comment by sergeyklay** [comment]
It is root of the problem:

```
configure: error: Cannot find php-config. Please use --with-php-config=PATH
```

You should add path to `php-config` to the `$PATH` variable
