### ISSUE TITLE
[0.10.13] Version not bumped

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/zephir#1742]
```
$ zephir version
0.10.12

```

**Comment by sergeyklay** [comment]
Thank you. I'll fix this asap

**Comment by remicollet** [comment]
Also bad with 0.11.4: 

https://github.com/phalcon/zephir/blob/0.11.4/Library/Zephir.php#L21

So, tag is not correct

**Comment by sergeyklay** [comment]
@remicollet No, it is correct. Since 0.11.4 the `$Id$` placeholder will be replaced during a PHAR build:

https://github.com/phalcon/zephir/blob/d0a6a8af0b78240a0f3e1f05d39baf73699a5570/box.json.dist#L53-L54

**Comment by remicollet** [comment]
Notice the phar reports
`Zephir 0.11.4-eb5db1a`
When 0.11.4 tag point to d0a6a8af0b78240a0f3e1f05d39baf73699a5570

**Comment by sergeyklay** [comment]
@remicollet Yeah, there was a confusion with the versions. My bad. I will fix 0.11.x here: #1743 + #1744 The 0.10.x branch will be fixed a bit later. I need a day or two to fix Phalcon blocking issue

**Comment by sergeyklay** [comment]
- 0.11.6: https://github.com/phalcon/zephir/releases/tag/0.11.6
- 0.10.14: https://github.com/phalcon/zephir/releases/tag/0.10.14

Thank you for the report, and for helping us make Zephir better.
