### ISSUE TITLE
Discussion/Enhancement: Why does a child class need to implement the same exact typed method signature as the parent?

### ISSUE THREAD

**Issue by dschissler** [zephir-lang/zephir#1745]
I've been playing around overloading `Phalcon\Config::merge` and I ran into this at runtime.

```
PHP Warning:  Declaration of Project\Application\Config::merge(ArrayAccess $config): Project\Application\Config should be compatible with Phalcon\Config::merge(Phalcon\Config $config) in Unknown on line 0
```

Is this a necessity?  This really limits the inheritance capabilities within Zephir.  I don't think that it should function this way unless some special modifier has been assigned to a method.

If you agree that it shouldn't be this way then I can relabel this as "Relaxation of method signature for types" or something like that.  I'm just not sure if there is a thoughtful reason why it is the way that it is, but regardless it seems to really get in my way and I feel like that I'm imprisoned between interfaces and method signatures.

**Comment by dschissler** [comment]
Also I'll add that lets face it, a warning is basically a full on error in this case.  Nobody is going to put something into production that spews warnings into the logs.  A warning in this case is effectively as prohibiting as a full on halt error.

**Comment by danhunsaker** [comment]
If you look closer at the error message, you'll see that it's coming from PHP, not Zephir itself. This is a restriction that PHP places on things. We can't relax it or remove it.

That said, are you running a custom compile of Phalcon built with Zephir 0.11.x? Because that's unsupported entirely - Phalcon should always be built with Zephir 0.10.x.

**Comment by dschissler** [comment]
> That said, are you running a custom compile of Phalcon built with Zephir 0.11.x? Because that's unsupported entirely - Phalcon should always be built with Zephir 0.10.x.

If that is the case then it really should be written out in a more obvious way.  I can't say that is not written out somewhere but I've never seen it.

However, my Phalcon is coming from the Ubuntu package and my extension is currently built with 0.11.6.

Perhaps the `merge` method could be relaxed to `var config` and then it could attempt to case an object to array or just to expand it to also accepting an array.

```php
    return $config
        ->merge(new Config([
            'paths' => [
                'otherDir' => '/abc'
            ]
        ]));
```

could become the following in user code:

```php
    return $config
        ->merge([
            'paths' => [
                'otherDir' => '/abc'
            ]
        ]);
```

**Comment by danhunsaker** [comment]
That's something to bring up in the Phalcon repo.

**Comment by dschissler** [comment]
Yeah

**Comment by dschissler** [comment]
@danhunsaker As a member of the Phalcon team I'd hope that you could get on top of that pretty screwed situation of quietly not supporting the latest version of Zephir when there are no visible (or at least prominent) notifications or labellings for such a situation.  That seems to me like something that should make its way out of the chat room and into public knowledge.

**Comment by danhunsaker** [comment]
I'm only on the Zephir team. I have nothing to do with Phalcon, generally. All I know is that odd numbered minor versions are intended to be unstable dev versions, while even numbered minor versions are intended to be stable and usable. Much like the Linux kernel back in the 2.x days (if not since).

**Comment by dschissler** [comment]
You are a a Github Phalcon "People".  I just assumed.  That is about 99% why I removed myself from that list.  I found it to be a totally pointless designation without significance.
