### ISSUE TITLE
Anonymous function

### ISSUE THREAD

**Issue by zuozhehao** [zephir-lang/zephir#1751]
```zep

namespace Work\Abc;

use Work\Task\Timer;

class Test {


    public function a()
    {
        var result;

	Timer::start(function () {

            let result = Timer::wait();

         });	
     }
}
```
[ERROR] Class name: Work\Timer does not exist in `let result = Timer::wait();`

**Comment by zuozhehao** [comment]
@sergeyklay

**Comment by sergeyklay** [comment]
@zuozhehao I'll take a look a bit later. Most likely in the next week. Thank you for the report.

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look

**Comment by dschissler** [comment]
@zuozhehao You should be able to get it to work for now by changing it to:

```zephir
let result = \Work\Task\Timer::wait();
```

Its because the thingy thing can't get up to the thing.

Other than that Yeaaah baby yeeaah, I've loving the new anon functions.  @sergeyklay @dreamsxin You guys make drinking fun again. :beer: :beers: :beer: :beer: :beer:

As you can see I'm doing all kinds of wonderful that wasn't possible until recently.

```zephir
    protected function attachEventsManager(<Di> di)
    {
        var em, eventFunc;

        let em = new EventsManager();

        let eventFunc = function(event, di, data) {
            var instance = data["instance"];

            if typeof instance == "object" {
                // if instance instanceof AutosetupInterface {
                if instance instanceof \Perch\Di\Service\AutosetupInterface {
                    instance->autosetup();
                }
            }
        };

        em->attach("di:afterServiceResolve", \Closure::bind(eventFunc, di));
        di->setInternalEventsManager(em);
    }
```

**Comment by dreamsxin** [comment]
@dschissler You are right.

It's just a matter of parsers.

```output
Warning: Class "xxx" does not exist at compile time in /home/myleft/work/mytest/mytest/app.zep on line 25 [nonexistent-class]
```

**Comment by sergeyklay** [comment]
Anyway it is issue I guess (although not critical).

**Comment by dschissler** [comment]
Maybe whoever tackles that can get `::class` working since there may be some overlap in research.  With this bug fix and that new feature then Zephir pretty much has all of the basics.
