### ISSUE TITLE
Compilation error with inheritance of prototype interfaces

### ISSUE THREAD

**Issue by sandrokeil** [zephir-lang/zephir#1758]
I use Zephir Parser 1.1.4 and Zephir 0.11.6 with [Docker image php:7.2-cli-alpine3.8](https://github.com/sandrokeil/docker-files/blob/master/zephir/7.2-cli) and I get the following error:

> In ClassDefinition.php line 857:                                                
  Class ArangoDb\Exception\ConnectionException must implement a method called: "getMessage" as requirement of interface: "Psr\Http\Client\NetworkExceptionInterface"

This error occurs if [prototype definitions](https://docs.zephir-lang.com/en/0.10/config#prototype-dir) are used. I have defined the following prototypes:
```
<?php
namespace Psr\Http\Client;

interface ClientInterface
{
    public function sendRequest(\Psr\Http\Message\RequestInterface $request) : \Psr\Http\Message\ResponseInterface;
}
interface ClientExceptionInterface extends \Throwable
{
}
interface NetworkExceptionInterface extends \Psr\Http\Client\ClientExceptionInterface
{
    public function getRequest() : \Psr\Http\Message\RequestInterface;
}
interface RequestExceptionInterface extends \Psr\Http\Client\ClientExceptionInterface
{
    public function getRequest() : \Psr\Http\Message\RequestInterface;
}
```
This is my zep file:
```
namespace ArangoDb\Exception;

use Psr\Http\Client\NetworkExceptionInterface;
use Psr\Http\Message\RequestInterface;

class ConnectionException extends \RuntimeException implements NetworkExceptionInterface
{
    /**
     * @var RequestInterface
     */
    private request;

    public function getRequest() -> <RequestInterface>
    {
        return this->request;
    }
}
```
If I replace the class definition with `class ConnectionException extends \RuntimeException implements \Throwable` it works. It looks like it can not validate the inheritance tree correctly.

**Comment by sergeyklay** [comment]
@sandrokeil Thank you for the report. I'll try to sort out ASAP.

**Comment by sergeyklay** [comment]
@sandrokeil I found a bug. Thinking about a possible solution.

**Comment by sergeyklay** [comment]
Fixed in current `development` branch. Thank you for the report, and for helping us make Zephir better.
