### ISSUE TITLE
"./install -c  " can't work!

### ISSUE THREAD

**Issue by dly667** [zephir-lang/zephir#1768]
Git Way
First make sure that the Zephir parser extension is installed and activated. You can follow this tutorial.

The Zephir compiler currently must be cloned from Github:

git clone https://github.com/phalcon/zephir
Run the Zephir installer:

cd zephir
./install -c

Failed to this step
thanks

**Comment by sergeyklay** [comment]
@dly667 The documentation you use refers to the 0.10.x branch. The documentation for the 0.11.x (current, actual branch) is not updated yet. I bring my apologies for this. Please take a look at https://github.com/phalcon/zephir-docs/issues/175

**Comment by danhunsaker** [comment]
We should probably adjust the 0.10 docs to specify the 0.10.x branch when cloning, to avoid this kind of issue in future versions. Do the same in 0.11's docs, while we're at it?

**Comment by sergeyklay** [comment]
@danhunsaker I agree. For example we can add a note to the 0.10 docs like "note that you need to get a relevant docs version branch using git clone"

**Comment by dly667** [comment]
thanks
