### ISSUE TITLE
foreach loop

### ISSUE THREAD

**Issue by arkanSoul** [zephir-lang/zephir#1774]
Just found out about zephir and I try to figure it out.
I am passing an array but I get this error when `zephir build`

```
Syntax error in /home/osboxes/Desktop/utils/utils/greeting.zep on line 13

	        foreach($arr as $key => $value) {
	---------------------^
```

```zep
namespace Utils;

/**
 * This is a sample class
 */
class Greeting
{
    /**
     * This is a sample method
     */
    public function say($arr)
    {
        foreach($arr as $key => $value) {
	   echo $key . ": " $value;
	}
    }
}
```

Can you provide an example please; Thanks in advance.

**Comment by sandrokeil** [comment]
You have to use a [for statement](
https://docs.zephir-lang.com/en/0.11/control-structures).

**Comment by sergeyklay** [comment]
@arkanSoul  There is no `foreach` control flow statement for traversing items in a collection/arrays. As @sandrokeil mentioned you have to use `for` instead.
