### ISSUE TITLE
File already exists at path: IR/compiled-files-sum

### ISSUE THREAD

**Issue by ghost** [zephir-lang/zephir#1776]
Hello! I have this problem for more than a while now, I do not know exactly where I made a mistake, the only solution I found is to delete the .zephir folder. But then build time takes longer. Thanks :)

https://imgur.com/a/dWnX3NB

**Comment by zlianon** [comment]
@sergeyklay Where would this problem be solved?

**Comment by niden** [comment]
You can also run

`zephir fullclean`

before running

`zephir build`

**Comment by ghost** [comment]
@niden Yes, but then build time takes longer.
Edit: The biggest problem is that I just make a small change and build time takes longer.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
