### ISSUE TITLE
zephir stubs - missing "use" statements

### ISSUE THREAD

**Issue by niden** [zephir-lang/zephir#1778]
The stubs generated using `zephir stubs` are missing the `use` statements at the top of the file.

This might not be a problem since for most of the stubs we have the fully qualified namespace for certain elements i.e. 

```zep
    /**
     * Sets the dependency injector
     *
     * @param \Phalcon\DiInterface $container
     */
    public function setDI(\Phalcon\DiInterface $container) {}
```

However it seems return variables are not properly parsed 
```zep
    /**
     * Returns the internal dependency injector
     *
     * @return \Phalcon\DiInterface
     */
    public function getDI(): DiInterface {}
```
The same happens with variables
```zep
    /**
     * @var <UrlInterface>
     */
    private $url;
```
I think either we need to add the `use` statements at the top of the file or parse variables as well as return values with the full namespaces.

**Comment by sergeyklay** [comment]
Fixed in development branch. Thank you for the bug report!
