### ISSUE TITLE
Array of object as return type is reported to php as type, not array

### ISSUE THREAD

**Issue by onshorechet** [zephir-lang/zephir#1779]
Returning an array of type in zephir is reported as just the type to php.  Because of this is it impossible to correctly implement override methods in php.  Below is the minimal example.  You can also note the use of this in the cphalcon project in, https://github.com/phalcon/cphalcon/blob/master/phalcon/mvc/model.zep::1653.

Zephir-Lang
```
namespace Issue;
class Test
{
    public static function say() -> <Test[]>
    {
        return [];
    }
}
```

Php Class:
```
class PhpTest extends \Issue\Test
{
    //PHP Fatal error:  Declaration of PhpTest::say(): array must be compatible with Issue\Test::say(): Issue\Test in php shell code on line 8
    public static function say(): array
    {
        return [];
    }
}
```

Centos7 with Zephir@0.11.8 and Zephir-Parser@v1.1.4

**Comment by sergeyklay** [comment]
@chet0xhenry I found a bug. Working on possible solution

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. I'll release new version ASAP. Feel free to open a new issue if the problem appears again. And thank you for contributing.

**Comment by dreamsxin** [comment]
Fixed in the development branch. Feel free to open a new issue if the problem appears again. And thank you for contributing.
