### ISSUE TITLE
Access to constants in array or `let`

### ISSUE THREAD

**Issue by niden** [zephir-lang/zephir#1783]
It appears Zephir doesn't like constants
```
[ERROR] Unknown type: static-constant-access   
```

Code to reproduce:
**Fails**
```zep
let client = [
	\Memcached::OPT_HASH       : \Memcached::HASH_MD5,
	\Memcached::OPT_PREFIX_KEY : "prefix."
];
```

**Fails**
```zep
let hash   = \Memcached::OPT_HASH,
    md5    = \Memcached::HASH_MD5,
    prefix = \Memcached::OPT_PREFIX_KEY;

let client = [
    hash   : md5,
    prefix : "prefix."
];
```

**Fails**
```zep
let prefix     = \Memcached::OPT_PREFIX_KEY;
```

But if I replace the constants with their actual values, the extension compiles fine
```zep
let client     = [
    1     : 2,
    -1002 : "prefix."
];
```

**Comment by sergeyklay** [comment]
@niden Yes, it is old issue. First of all this may not work if you trying to compile with disabled memcached extension.  Theoretically you can even compile it, but I want to draw your attention that Zephir is not PHP and the value of the constant will not calculate dynamically. The value of the constant will be calculated once, at compile time. Thus, if the user updates the memcached, he may be unpleasantly surprised to realize that the extension continue use old constant values (previous version). Btw, did you try `constant("\Memcached::OPT_PREFIX_KEY")`?

**Comment by niden** [comment]
No I actually never did. I circumvented the issue by putting the actual value of the constant :)

This can be closed.
