### ISSUE TITLE
Noob questions.

### ISSUE THREAD

**Issue by mrtwj** [zephir-lang/zephir#1785]
0. Is there a more appropriate forum for noob questions than in issues?
1. Does Zephir support true generics in some form e.g. Java generics?
2. What are the limitations of closures? There's no callable type supported that I can see, so how would you assign a closure to a variable?
3. Does Zephir support generator yield syntax?
4. What salient PHP 5.X and 7.X features are missing from Zephir?
5. Is there any documentation for the Zephir compiler other than code comments?
6. Does Zephir support custom class type hints/assignments?

**Comment by phalcorine** [comment]
For question 5 @travis-fyf , you could check out this link: https://docs.zephir-lang.com/

**Comment by sergeyklay** [comment]
@mrtwj We only accept bug reports, new feature requests and pull requests in GitHub. For questions regarding the usage of the framework, support requests, and questions like this please visit the [official forums](https://forum.phalconphp.com) as well as [Discord server](https://phalcon.link/discord). Sorry it took this long
