### ISSUE TITLE
What should “.gitignore” look like?

### ISSUE THREAD

**Issue by dongasai** [zephir-lang/zephir#1793]
How should I set the version control rules for my custom extensions?

**Comment by dongasai** [comment]
In the rule of "https://github.com/phalcon/cphalcon/blob/master/.gitignore" "ext/kernel, *.zep.c, *.zep.h" file is to join a version control, but in the "https://github.com/phalcon/cphalcon/blob/master/CONTRIBUTING.md" is not allowed in the version control

**Comment by sergeyklay** [comment]
@dongasai The initial idea was that only maintainers add these files. Perhaps this will be changed in the future. Any modern project written on Zephir, can completely ignore the `ext` directory. Btw, Phalcon has a lot of C files inside `ext` directory which are created by hand.
