### ISSUE TITLE
Does zephir-0.11.9 not support window?

### ISSUE THREAD

**Issue by xqkeji** [zephir-lang/zephir#1801]
After upgrading to zephir-0.11.9, zephir build prompts: "[NOTE] Installation is not implemented for Windows yet. Aborting."

**Comment by dreamsxin** [comment]
Download url https://github.com/phalcon/php-zephir-parser/releases/tag/v1.2.0
Supported PHP versions: 7.0, 7.1, 7.2, 7.3 and 7.4 (nightly).

**Comment by dreamsxin** [comment]
Install and compile must be manual compilation.
