### ISSUE TITLE
Objects are not traversable with foreach

### ISSUE THREAD

**Issue by CameronHall** [zephir-lang/zephir#1818]
Presently, the only way to iterate over an object is with the PHP userland method `get_object_vars()`. 
I believe [this check](https://github.com/phalcon/zephir/blob/0a5dcb6b00fdf4ae267f676d580a3ac3d4ccc339/kernels/ZendEngine3/main.c#L35) should consider whether the parameter inherits `ArrayAccess` or any other classes that inherit `Traversable`

**Comment by ViltusVilks** [comment]
Yes, it will be very good, because yield also should be somehow implemented.

**Comment by CameronHall** [comment]
Looks like https://github.com/phalcon/zephir/issues/1400 is related.

**Comment by dreamsxin** [comment]
I will try to implement.
