### ISSUE TITLE
Using C constants from header file in zephir code

### ISSUE THREAD

**Issue by glanceded** [zephir-lang/zephir#1827]
I am trying to use a c header file constants.h and inserting it in constants-sources directive from config.json file, but it seems that i can' use those constants in my *.zep files.

Is this possible? I have managed to use the custom optimizers to achieve the same thing that could be achieved with a simple header file...

**Comment by ViltusVilks** [comment]
You can use regular PHP ext constants, i.e. defined in .zep files.

**Comment by Jurigag** [comment]
Well therotically it is somehow possible - you can actually write c code in zephir files directly.

Check this out - https://github.com/phalcon/zephir/blob/master/test/cblock.zep

So i guess you can include whatever header file you want, and assign value of constant to some variable - i guess you want to do this.

Feel free to reopen this if it doesn't solve your problem.
