### ISSUE TITLE
I get non-existent warning function for existent function.

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1843]
If I have the param <Closure> cb then cb() in that function...

`Warning: Function "cb" does not exist at compile time.`

I'm guessing it's probably trying to call it by name if I run it. Given ->call will break the bind the only thing that seems like it can work is call_user_func.

**Comment by sergeyklay** [comment]
Could you please provide the code to reproduce

**Comment by Jurigag** [comment]
If this function is defined in php then compiler doesn't know about it until you will import it somehow during compilation.

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
