### ISSUE TITLE
Zephir can barely handle any non-trivial mathematical expression, unsafe for use.

### ISSUE THREAD

**Issue by joeyhub** [zephir-lang/zephir#1844]
I have some mathematical expressions, nothing crazy and zephir is messing up all over the place. It's just not safe to use. You can't trust it without extensive testing and verification.

In one case I had something like:

```
float f;
let f = 5.0;
let f = 4.0 * (cond ? f : -f);
```

In this case to convert it to C it just needs remove let. I could compile it with sed or grep.

What happens instead is that for some reason it decides to make it a zval, boxing it and unboxing it with our only hope being for GCC to compile that out.

In cases where you have `var x = expression;` all it does is check the type of the expression node which seems to need to be split, IE, literal should have two types. The result is bizarre error messages. It fails to resolve the type even for cases where they type can easily be determined as all sources for the node tree and operations have determined types. There's nothing dynamic happening.

The absolute worse is that I have an expression with a divide. Everything is a double as in all sources either are literal double or hinted double. When I run my tests the results indicate massive precision loss. I try everything until finally looking at the C where I see zephir_safe_div_double_long. It makes no sense. I can parse the AST myself and deduce it to want to be double_double for a double does of that precision. It's also inconsistent.

```
float a = 1.0, b = 2.0, c = 3.0;
float bob = a / (b * c);
```

In this case the calculation is wrong. The precision loss can be so severe you can get sacked if you generate billing using zephir.

```
float tim = b * c;
let bob = a / tim;
```

This one is fine.

I'm quite disappointed with this. I thought zephir being used for phalcon meant it was relatively robust but it seems to instead be struggling at the basics still. It's not as bad as it used to be and works a bit better that it used to at least using it to generate C you intend to then convert by hand taking out all the junk that makes things slow like the automstic memory management but it also still has a very long way to go.

**Comment by joeyhub** [comment]
Also you're putting in the macro for zts when calling in the param list but not in the callee's function prototype.

**Comment by joeyhub** [comment]
As a matter of emergency you need to remove mentions on the site of it making things more reliable. It is somewhere between alpha and beta test level of quality, you can't make out like it's good to go when it has fundamental catastrophic deficiencies that can result in significant damage without immediate detection, like it getting the wrong types even when you specify the right types then silently losing precision.

**Comment by joeyhub** [comment]
Zephir is also outputting lines that are dead code and make no sense at all for complex expressions.

**Comment by Jeckerson** [comment]
Related - https://github.com/zephir-lang/zephir/discussions/2189
