### ISSUE TITLE
[NFR]Support `use` keyword in Closures

### ISSUE THREAD

**Issue by dreamsxin** [zephir-lang/zephir#1848]
Example
```php
$func = function() use ($a) {
    return $a + 1;
}
```

Here `$a` becomes a local static variable of function `$func`.

@sergeyklay Who can implementation parse code.

**Comment by niden** [comment]
This is definitely needed

**Comment by sergeyklay** [comment]
@dreamsxin I'll try to implement parser

**Comment by sergeyklay** [comment]
Refs: https://github.com/phalcon/zephir/issues/888

**Comment by sergeyklay** [comment]
@dreamsxin Parser done https://github.com/phalcon/php-zephir-parser/pull/69

**Comment by dreamsxin** [comment]
@sergeyklay Please help optimize code in https://github.com/dreamsxin/zephir/commit/404130d0426d1e8a83d8d4e7b4ddc799d7e4b633
