### ISSUE TITLE
[BUG] Extended classes can't access their private variables

### ISSUE THREAD

**Issue by zsilbi** [zephir-lang/zephir#1851]
Hey,

If a class - written in Zephir - contains private variables and extended in PHP, it won't be able to access those variables in its original methods.

I ran into this when I was trying to extend `\Phalcon\Session\Manager` and `\Phalcon\Session\Bag` in v4.0.0-alpha.4

Code to reproduce the issue:

```zep
/** Example.zep **/

class Example
{
    private privateVariable;

    public function setPrivateVariable(value)
    {
        let this->privateVariable = value;

        return this;
    }

    public function getPrivateVariable()
    {
        return this->privateVariable;
    }
}
```

In PHP it is extended without any new methods:

```zep
/** My/Example.php **/

namespace My;

class Example extends \Example {}
```

Test code:

```php
$example = new \My\Example;
$example->setPrivateVariable('test');

var_dump($example->getPrivateVariable());
```

Result:

`Notice: Undefined property: My\Example::$privateVariable`

Changing `private` variables to `protected` solved the errors.

Zephir version: 0.11.12
PHP: 7.3.4 or 7.2.16 (tried both)

Thanks

**Comment by sergeyklay** [comment]
Thank you for the report. We'll try to sort out ASAP.
