### ISSUE TITLE
"use" keyword in closures compile error

### ISSUE THREAD

**Issue by zuozhehao** [zephir-lang/zephir#1860]
```
namespace Example;
class Closure
{
    public function callback(array! abc)
    {

        return function () use (abc) {

            return abc["a"];

        };
    }
}
```

`[ERROR] Cannot use non-initialized variable as an array in`

**Comment by sergeyklay** [comment]
@zuozhehao Which version do you tested?

**Comment by zuozhehao** [comment]
@sergeyklay 

PHP 7.3.4 (cli) 
Zephir 0.12.0

**Comment by sergeyklay** [comment]
@zinovyev We'll recheck in next days. Thank you for the report.

**Comment by zuozhehao** [comment]
@dreamsxin 

还有点小问题。
```
    public function handle(<\Swoole\Server> serv)
    {

        return function () use (serv) { };

    }
```

Compiling 正常， Installing... 报错。

查看错误日志。

```
错误：‘zephir_read_static_property_ce’的第 1 个实参类型不兼容
  zephir_read_static_property_ce(serv, test_1__closure_ce, SL("serv"), PH_NOISY_CC);
  ^
```

尝试手动修改

zephir_read_static_property_ce(serv, test_1__closure_ce, SL("serv"), PH_NOISY_CC);

改为

zephir_read_static_property_ce(`&`serv, test_1__closure_ce, SL("serv"), PH_NOISY_CC);

则正常。

**Comment by dreamsxin** [comment]
@zuozhehao 已经修改，再更新测试下试试。

**Comment by zuozhehao** [comment]
@dreamsxin 测试没问题。
