### ISSUE TITLE
Warning: Clock error detected. Your creation may be incomplete.

### ISSUE THREAD

**Issue by zuozhehao** [zephir-lang/zephir#1861]
```
PHP 7.3.4 (cli)
Zephir 0.12.0
CentOS Linux release 7.5.1804 (Core) 
```
make: Warning: File `/example/ext/modules/example.la' has modification time 9.9 s in the future
make: Warning: Clock error detected. Your creation may be incomplete.

I tried to calibrate the system time, using `touch *`was the same error.

**Comment by dreamsxin** [comment]
是你的文件修改日期跟当前系统时间不一致了吧。
```shell
make clean
```

**Comment by zuozhehao** [comment]
都有执行 fullclean 偶尔还是那样。

**Comment by sergeyklay** [comment]
I'm closing this issue but if I have made an oversight, please do get back in touch. Thanks
