### ISSUE TITLE
ZEPHIR_CALL_METHOD() zephir_call_class_method_aparams() bug

### ISSUE THREAD

**Issue by zhaoyanliang8** [zephir-lang/zephir#1863]
https://github.com/phalcon/zephir/blob/df9c16e50788dc9631e7d291fc6f3c5c7f107380/kernels/ZendEngine3/fcall.c#L542
In php7, `ce->name` is `zend_string*`, We should wrap it with the `ZSTR_VAL` macro.
This is not the point

----
in "cphalcon/phalcon/mvc/controller.zep"
```
abstract class Controller extends Injectable implements ControllerInterface
{

	/**
	 * Phalcon\Mvc\Controller constructor
	 */
	public final function __construct()
	{
		if method_exists(this, "onConstruct") {
			this->{"onConstruct"}();
		}
	}
}
```

in php code
```php
<?php
use Phalcon\Mvc\Controller;

class MyController extends Controller
{
	private function onConstruct()
	{

	}
}

$c = new MyController;
```
I incorrectly defined onConstruct as a ***private*** method, and I got an exception :

> Fatal error: Uncaught RuntimeException: ***Call to undefined method MyController::onconstruct()*** in test.php:12
>Stack trace:
>#0 test.php(12): Phalcon\Mvc\Controller->__construct()
>#1 {main}
>  thrown in test.php on line 12

This is a confusing error message.

```php
<?php
class Controller
{
	public function __construct()
	{
		if ( method_exists($this, 'onConstruct') ) {
			$this->onConstruct();
		}
	}
}

class MyController extends Controller
{
	private function onConstruct()
	{

	}
}

$c = new MyController;
```
If we define the Controller in php code, we will get an exception:
PHP Fatal error:  ***Call to private method MyController::onConstruct() from context 'Controller'*** in test.php on line 7

`zephir_call_class_method_aparams()` should handle this situation, keeping the error message consistent with php

**Comment by sergeyklay** [comment]
Fixed in the `0.12.0` version (https://github.com/phalcon/zephir/pull/1864). Feel free to open a new issue if the problem appears again. Thank you for contributing.
