### ISSUE TITLE
typeof operator from image resource return "unknown type"

### ISSUE THREAD

**Issue by emiliodeg** [zephir-lang/zephir#1866]
I've been writting Gd image tests and when I tried with `__destruct()` [method](https://github.com/phalcon/cphalcon/blob/4.0.x/phalcon/Image/Adapter/Gd.zep#L102) didn't work as expected

`
if typeof image  == "resource" {
    imagedestroy(image);
}
`
The operator `typeof` inside if always return `unknow type` then always fails

### Expected 

`typeof image` return "resource"

### Actual Behavior
`typeof image` return "unknow type"

### Details

* Phalcon version: 4.0.0 beta 1
* PHP Version: 7.2.14
* Operating System: nanofile PHP 7.2
* Installation type: Compiling from source
* Zephir version 0.11.8
* Server: Apache (nanofile php 7.2)
* Other related info (Database, table schema):

**Comment by sergeyklay** [comment]
Looks like it is fixed now.

Zephir code:

```zep
namespace Bug;

class LoadJpeg
{
    protected image;

    public function __construct(string filename)
    {
        let this->image = imagecreatefromjpeg(filename);
    }

    public function diagnose() -> string
    {
        return typeof this->image;
    }

    public function __destruct()
    {
        fprintf(STDERR, "this->image (%s)\n", this->diagnose());

        var image;
        let image = this->image;

        if typeof image  == "resource" {
            fprintf(STDERR, "image is resource\n");
            imagedestroy(image);
        } else {
            fprintf(STDERR, "image isn't resource\n");
        }
    }
}
```

The test:
```php
<?php

use Bug\LoadJpeg;

$test = new LoadJpeg(
    "/home/klay/Pictures/zephir-issue-1.jpg"
);

echo $test->diagnose(), PHP_EOL;
unset($test);
```

Output:
```
resource
this->image (resource)
image is resource
```

Thank you for the bug report
