### ISSUE TITLE
PHP 7.4

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1876]
So alpha is already released, with final version to be released on 21st November. We should focus on preparing to make zephir and phalcon working with PHP 7.4, first noticeable thing i noticed is that `ZEND_ACC_SHADOW` constant is removed on PHP 7.4.

Better to start it earlier than later so we already have extension working from day one.

@dreamsxin @niden @sergeyklay

**Comment by sergeyklay** [comment]
We'll try to sort out. Thank you

**Comment by remicollet** [comment]
From UPGRADINGS.INTERNALS

```
    - ZEND_ACC_SHADOW property flag is removed. Instead of creating shadow
      clone, now we use the same private property_info, and should also
      check property_info->ce (in the same way as with methods).
```

**Comment by sergeyklay** [comment]
Implemented. Tests for PHP 7.4 are passed for a moth or so.
