### ISSUE TITLE
Extending From Abstract ArrayAccess

### ISSUE THREAD

**Issue by mesutaksak** [zephir-lang/zephir#1890]
There are two classes I wrote As follows,

AbstractCollection.zep

    namespace App;

    use ArrayAccess;

    abstract class AbstractCollection implements ArrayAccess
    {
        private keys   = [];
        private values = [];

        abstract protected function setDefault(string id)->bool;

    public function offsetSet(var id, var value)
    {
        let id = (string)id;

        if isset this->keys[id] && this->keys[id] === true {
            throw new \RuntimeException("Cannot override key ".id);
        }

        let this->keys[id]   = false,
            this->values[id] = value;
    }

    public function offsetGet(var id) -> var
    {
        var raw, val;

        let id = (string)id;

        if !isset this->keys[id]  {
            throw new NotFoundException(id);
        }

        return this->values[id];
    }

    public function offsetExists(var id) -> bool
    {
        let id = (string)id;
        return isset this->keys[id];
    }

    public function offsetUnset(var id) -> void
    {
        let id = (string)id;
        if isset this->keys[id] {
            unset this->keys[id];
            unset this->values[id];
        }
    }

    }

Collection.zep

    namespace App;

    class Collection extends AbstractCollection
    {
        protected function setDefault(string id)->bool
        {
            return true;
        }
    }

test.php

    $col = new App\Collection();

    print_r($col);
    $col['a'] = 1;
    print_r($col);
    $col['b'] = 2;
    print_r($col);

output :

	Spf\Collection Object
	(
		[keys:Spf\AbstractCollection:private] => Array
			(
			)

		[values:Spf\AbstractCollection:private] => Array
			(
			)

	)
	Spf\Collection Object
	(
		[keys:Spf\AbstractCollection:private] => Array
			(
				[a] => 
			)

		[values:Spf\AbstractCollection:private] => Array
			(
				[a] => 1
			)

	)
	Spf\Collection Object
	(
		[keys:Spf\AbstractCollection:private] => Array
			(
				[b] => 
			)

		[values:Spf\AbstractCollection:private] => Array
			(
				[b] => 2
			)

	)

Linux Alphine 3.9 on docker
Compiler gcc
Zephir 0.11.12

when l add new item to collection, always  just last item exists!
without abstract and not extending class all is normal.

**Comment by sergeyklay** [comment]
@dreamsxin Any idea?

**Comment by dreamsxin** [comment]
What's PHP version? I test PHP 7.1, it's correct.

```php
$col = new Mytest\Collection();

print_r($col);
$col['a'] = 1;
print_r($col);
$col['b'] = 2;
print_r($col);
$col['c'] = 3;
print_r($col);
```
```text
Mytest\Collection Object
(
    [keys:Mytest\app:private] => Array
        (
        )

    [values:Mytest\app:private] => Array
        (
        )

)
Mytest\Collection Object
(
    [keys:Mytest\app:private] => Array
        (
            [a] => 
        )

    [values:Mytest\app:private] => Array
        (
            [a] => 1
        )

)
Mytest\Collection Object
(
    [keys:Mytest\app:private] => Array
        (
            [a] => 
            [b] => 
        )

    [values:Mytest\app:private] => Array
        (
            [a] => 1
            [b] => 2
        )

)
Mytest\Collection Object
(
    [keys:Mytest\app:private] => Array
        (
            [a] => 
            [b] => 
            [c] => 
        )

    [values:Mytest\app:private] => Array
        (
            [a] => 1
            [b] => 2
            [c] => 3
        )

)
```

**Comment by mesutaksak** [comment]
Sorry for l forget write php version,
l am using PHP 7.3

https://github.com/phpearth/docker-php/blob/master/docker/7.3-nginx.Dockerfile

**Comment by dreamsxin** [comment]
Use Zephir 0.12.1/PHP 7.3, it's correct.

**Comment by mesutaksak** [comment]
l not see 0.12.1 yet but,
l have tryed with Zephir 0.12.0/PHP 7.3, now all is ok,

Good job!
Thanks.
