### ISSUE TITLE
Lowercase directory name when creating stubs

### ISSUE THREAD

**Issue by ruudboon** [zephir-lang/zephir#1892]
When generating stubs I see that all directory names are lowercase.
The original directory's are camelcase.
Is this intended?

**Comment by sergeyklay** [comment]
No, it is not intended. Is there any problem with this?

**Comment by ruudboon** [comment]
Yes. See the ide-stubs repo also. All dirs are lowercase.
Could this be related to this line?
https://github.com/phalcon/zephir/blob/baa91276224e49bd1383f480ff650d0a49b0468d/Library/Stubs/Generator.php#L82

**Comment by sergeyklay** [comment]
Yes, I think so. But I'm still can't understand issue you trying to solve.

**Comment by ruudboon** [comment]
Source dir:
<img width="446" alt="Screenshot 2019-07-27 at 10 26 46" src="https://user-images.githubusercontent.com/7444246/61992035-2d4b5380-b059-11e9-8bf3-cad0af19bb08.png">
Directories starting with a capital
```
zephir stubs
```
Result:
acl\adapter\AbstractAdapter.zep.php
<img width="463" alt="Screenshot 2019-07-27 at 10 35 22" src="https://user-images.githubusercontent.com/7444246/61992116-41438500-b05a-11e9-9177-2de596ee71ac.png">

Expected result:
Acl\Adapter\AbstractAdapter.php

**Comment by sergeyklay** [comment]
Yes, I understand the expecting result. I'm interested in a _real problem_ you have :) As a far as I know most popular IDEs just scans whole directory and let's say "include" all files.

**Comment by ruudboon** [comment]
Yeah it looks like it's working on my system but not sure if that's the case for all ide's and all os.
Would be also be more clear if it matches the source in casing and filename (removing .zep.).
And even it is bad practice and would only be possible on linux you could have 2 files with the same name and different casing. I do think it's a low prio but would be nice if we can fix it.

**Comment by sergeyklay** [comment]
> Would be also be more clear if it matches the source in casing and filename (removing .zep.).

```shell
find . -type f -name "*.zep.php" | sed -e 'p' -E -e "s/.zep.php/.php/g" | xargs -n2 mv
```

**Comment by sergeyklay** [comment]
Closing, this is implemented. If there are bugs, we can follow up in separate issues. Thank you for contributing!
