### ISSUE TITLE
static property reference bug

### ISSUE THREAD

**Issue by zhaoyanliang8** [zephir-lang/zephir#1904]
see pull request #1903 

```zend_update_static_property()``` has been modified in php7.3
https://github.com/php/php-src/blob/PHP-7.2.21/Zend/zend_API.c#L4070-L4106
https://github.com/php/php-src/blob/PHP-7.3.8/Zend/zend_API.c#L4080-L4102

but merge changes to php7.2 may cause php to crash sometimes

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look

**Comment by dreamsxin** [comment]
@zhaoyanliang2 你能解决这个问题么？

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.

**Comment by sergeyklay** [comment]
I open this again because changes proposed in the https://github.com/phalcon/zephir/pull/1927 leads to segmentation fault. For more see: https://github.com/phalcon/zephir/issues/1941#issuecomment-538654340 and https://github.com/phalcon/zephir/pull/1954

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look

**Comment by Jeckerson** [comment]
Closing due legacy version support.
