### ISSUE TITLE
Zephir stubs remove slash from \Exception class when extending

### ISSUE THREAD

**Issue by ruudboon** [zephir-lang/zephir#1907]
If an class extends \Exception it will result the slash will be removed
Phalcon\Collection\Exception
Source
```

/**
 * This file is part of the Phalcon Framework.
 *
 * (c) Phalcon Team <team@phalconphp.com>
 *
 * For the full copyright and license information, please view the LICENSE.txt
 * file that was distributed with this source code.
 */

namespace Phalcon\Collection;

use Throwable;

/**
 * Exceptions for the Collection object
 */
class Exception extends \Exception implements Throwable
{
}

```
Generated stubs
```
<?php

namespace Phalcon\Collection;

/**
 * Exceptions for the Collection object
 */
class Exception extends Exception implements \Throwable
{

}
```

This happens also in Phalcon\Exception
Related to https://github.com/phalcon/ide-stubs/issues/25

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
