### ISSUE TITLE
'void' return type hint is ignored

### ISSUE THREAD

**Issue by JellyBrick** [zephir-lang/zephir#1908]
## Log
`Fatal error: Declaration of Pocketmine\Utils\BinaryStream::setOffset(int $offset) must be compatible with pocketmine\network\mcpe\protocol\Packet::setOffset(int $offset): void in /develop/pocketmine/src/network/mcpe/protocol/DataPacket.php on line 38`

## Code
```php
interface Packet{
        public function setOffset(int $offset) : void
        //...
}
```
_Packet.php_

```php
abstract class DataPacket extends BinaryStream implements Packet{
     //....
}
```
_DataPacket.php_

```zephir
    public function setOffset(int offset) -> void
    {
        let this->offset = offset;
    }
```
_binarystream.zep_

**However, the generated code has no type hints.**
(Stubs included)

```php
    /**
     * @param int $offset
     */
    public function setOffset(int $offset) {}
```
_binarystream.zep stub_

**Comment by Jurigag** [comment]
I'm guessing stubs generations wasn't made when 7.1 was released, that's why we ignore void. I guess someone would need to update it and add check for php 7.1

**Comment by JellyBrick** [comment]
@Jurigag #1910
