### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chrysanthemum** [zephir-lang/zephir#1913]
What is the reason for this?

$ ./.ci/memcheck.sh
==22576== Memcheck, a memory error detector
==22576== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==22576== Using Valgrind-3.13.0 and LibVEX; rerun with -h for copyright info
==22576== Command: /php-src/php-7.2/php/bin/php -d extension=ext/modules/test.so unit-tests/phpunit --no-coverage --testsuite Extension\ Test\ Suite
==22576==
Could not open input file: unit-tests/phpunit

**Comment by ruudboon** [comment]
Please use the issues for bugs only.
But it looks like your missing phpunit (composer install)
