### ISSUE TITLE
BUG: AssignSuperGlobals

### ISSUE THREAD

**Issue by chrysanthemum** [zephir-lang/zephir#1917]
test/assign.zep

```
function testAssignSuperGlobals()
{
let _GET = array_merge(_GET, ["g3": "ccc", "g4": "ddd"]);
}
```
t.php
http://localhost/t.php?g1=aaa&g2=bbb
```
<?php
testAssignSuperGlobals();
print_r($_GET);
```
result:
```
Array
(
    [g1] => aaa
    [g2] => bbb
)
```

g3 / g4 are lost in the $GET

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for contributing.
