### ISSUE TITLE
Stubs not generating correct return on optional var

### ISSUE THREAD

**Issue by ruudboon** [zephir-lang/zephir#1922]
When generating stubs and we have something like:
```
public function getVar(string! key) -> var | null
```
It will result in something like this causing a PHP error.
```
public function getVar(string $key): ? {}
```
Expected result
```
public function getVar(string $key) {}
```

**Comment by danhunsaker** [comment]
Looks like the `null` check needs to be tempered by whether there's a concrete non-null type being output.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
