### ISSUE TITLE
Improve Zephir analyzer

### ISSUE THREAD

**Issue by ruudboon** [zephir-lang/zephir#1924]
A few cases are currently not detect by the Zephir analyser. If possible we would like to add them.

**Classes that should be abstract are not abstract**
https://github.com/phalcon/cphalcon/blob/41d398bbf802c02815394d7bbd72f8bf85142d4f/phalcon/Factory/AbstractFactory.zep#L16

https://github.com/phalcon/cphalcon/blob/41d398bbf802c02815394d7bbd72f8bf85142d4f/phalcon/Factory/AbstractFactory.zep#L65

**Abstract interfaces aren't check against the super.**

https://github.com/phalcon/cphalcon/blob/41d398bbf802c02815394d7bbd72f8bf85142d4f/phalcon/Mvc/Application.zep#L82

https://github.com/phalcon/cphalcon/blob/41d398bbf802c02815394d7bbd72f8bf85142d4f/phalcon/Application/AbstractApplication.zep#L97

**Double use statements**
Double use statements aren't detected

https://github.com/phalcon/cphalcon/blob/a48b31967a1ce27c10cbed61bee42e0c90addc86/phalcon/Acl/Adapter/Memory.zep#L22

**Classnames use conflicts**
Use can have the same name as the class.

https://github.com/phalcon/cphalcon/blob/master/phalcon/Forms/Element/Select.zep

** Non existing use not detected **
When we have a use to non existing class we would like to detect this.

**Comment by sergeyklay** [comment]
Closing this in favor of https://github.com/phalcon/zephir/issues/1628
