### ISSUE TITLE
[0.12.7] undefined symbol ZEPHIR_NULL

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/zephir#1946]
Trying to run test suite.

`PHP Warning:  PHP Startup: Unable to load dynamic library '/dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/ext/modules/test.so' (tried: /dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/ext/modules/test.so (/dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/ext/modules/test.so: undefined symbol: ZEPHIR_NULL), /usr/lib64/php/modules//dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/ext/modules/test.so.so (/usr/lib64/php/modules//dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729`

**Comment by remicollet** [comment]
`sed -e s'/ZEPHIR_NULL/ZVAL_NULL/' -i kernels/ZendEngine3/string.c` seems enough

**Comment by sergeyklay** [comment]
I'm sorry, I introduced this. I hope it fixed now. Thank you again!
