### ISSUE TITLE
Question about test suite

### ISSUE THREAD

**Issue by remicollet** [zephir-lang/zephir#1949]
```
There were 2 errors:

1) Extension\InternalClassesTest::testStaticMethodCall
Error: Class 'Phalcon\Di' not found

/dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/unit-tests/Extension/InternalClassesTest.php:24

2) Extension\InternalClassesTest::testStaticPropertyFetch
Error: Class 'Phalcon\Mvc\Model\Query' not found

/dev/shm/BUILD/zephir-1c107e0c8966233f0d35156419e2c97729dcc4ce/unit-tests/Extension/InternalClassesTest.php:30

ERRORS!
Tests: 539, Assertions: 1646, Errors: 2.

```

Where do these classes come from ?
Of course, when phalcon ext is installed, test suite passes, but fails without

**Comment by sergeyklay** [comment]
I hope I fixed this in https://github.com/phalcon/zephir/pull/1948/commits/650708de9df9039f04eda0fc150bd94e5a5b9753. Thank you for the bug report.

**Comment by remicollet** [comment]
Yes, thanks

Build + test suite tested with PHP 7.2, 7.3 and 7.4

**Comment by sergeyklay** [comment]
@remicollet Question: do you provide rpm for Zephir ?

**Comment by remicollet** [comment]
Yes, but for now only version 0.10 used to build stable phalcon 3.4 

phalcon 4  is available in "testing" repository, but build without zephir (which was broken, but need to do more tests and report any issue)

As soon, as I will be able to build phalcon 4 using zephir 0.12, it will be in the repo.

**Comment by remicollet** [comment]
FYI, using **zephir 0.12.4** (or 0.12.7) and **phalcon 4.0.0rc.1**
```
+ /usr/bin/zephir clean
+ /usr/bin/zephir fullclean
+ /usr/bin/zephir generate

                                                                                                                        
 [ERROR] Method '__construct' was defined more than one time                                                            
```

Any idea ?
Should I open a phalcon or zephir bug report ?

**Comment by sergeyklay** [comment]
@remicollet I think it is Phalcon bug

**Comment by remicollet** [comment]
>  I think it is Phalcon bug

ok, reported as https://github.com/phalcon/cphalcon/issues/14446

**Comment by sergeyklay** [comment]
Can we close this one?

**Comment by sergeyklay** [comment]
@remicollet Released https://github.com/phalcon/zephir/releases/tag/0.12.8
