### ISSUE TITLE
Zephir stubs allow multiline @param

### ISSUE THREAD

**Issue by Jurigag** [zephir-lang/zephir#1968]
When the parameter is provided like this:

```
     * @param array options = [
     *     'prefix' => 'phalcon'
     *     'lifetime' => 3600
     * ]
```

Which is totally correct phpdoc, it helps for plugin https://github.com/klesun/deep-assoc-completion to autocomplete code.

It's not detected correctly as parameter, it just add those lines as they are and additionally adds another `@param` from method parameters. I guess current regexp needs somehow to change https://github.com/phalcon/zephir/blob/development/Library/Stubs/MethodDocBlock.php#L110 here but im not regexp expert.

**Comment by sergeyklay** [comment]
Closing, this is implemented. If there are bugs, we can follow up in separate issues.
