### ISSUE TITLE
Classes cannots implement interface method with void interface

### ISSUE THREAD

**Issue by bobcolten** [zephir-lang/zephir#1981]
Now when making own Zephir extension its not able to use Phalcon extension interface which has the `void` such as `setDI`.  It is good from the PHP class or using also all in own extension.

You cannot implement a method   `must be compatible with Phalcon\Di\InjectionAwareInterface::setDI(Phalcon\Di\DiInterface $container): void in Unknown on line 0`

**Comment by bobcolten** [comment]
I mean to say that Zephir extension will not be good for Zephir extension.

**Comment by sergeyklay** [comment]
@bobcolten Could you please provide minimal code to reproduce the issue?

**Comment by hellobbq** [comment]
```
use Phalcon\Mvc\View\Engine;

class CustomView extends Engine {
	public function render(var path, var params, var mustClean = false)
	{
		// ...
            this->_view->setContent("content...");
	}
}
```

has warning 'must be compatible with...'

**Comment by sergeyklay** [comment]
```diff
- public function render(var path, var params, var mustClean = false)
+ public function render(string path, var params, boolean mustClean = false)
```
