### ISSUE TITLE
Method context loses track of 'this' after calling static method and compiled with "internal-call-transformation": true

### ISSUE THREAD

**Issue by andrewdalpino** [zephir-lang/zephir#2007]
The following block of code ([source](https://github.com/RubixML/Tensor/blob/master/tensor/matrix.zep)) results in the unintended side effect of losing reference to 'this' after the static method call ...

```zephir
    public function reciprocal() -> <Matrix>
    {
        var_dump(this);

        var ones = self::ones(this->m, this->n);

        var_dump(this);

        ...
    }
```

**Output**

```sh
 ["a":protected]=>
  array(3) {
    [0]=>
    array(3) {
      [0]=>
      int(22)
      [1]=>
      int(-17)
      [2]=>
      int(12)
    }
    [1]=>
    array(3) {
      [0]=>
      int(4)
      [1]=>
      int(11)
      [2]=>
      int(-2)
    }
    [2]=>
    array(3) {
      [0]=>
      int(20)
      [1]=>
      int(-6)
      [2]=>
      int(-9)
    }
  }
  ["m":protected]=>
  int(3)
  ["n":protected]=>
  int(3)
}

NULL
```

... when running this [test](https://github.com/RubixML/Tensor/blob/master/tests/MatrixTest.php) and the extension is compiled with the internal-call-transform optimization. Notice `this` is null after the static method call.

Assigning 'this' to a temporary variable before calling the static method can be used as a workaround  ...

```zephir
var temp = this;
```

To me, this means that somehow 'this' is being sent into oblivion after a static method call from a method context, but you'll know more about whats going on under the hood. This particular phenomena is the cause of 2 separate errors in the test suite. I'm assuming it's unexpected behavior since it works fine when compiled with "internal-call-transformation:" false.

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Feel free to open a new issue if the problem appears again. Thank you for the bug report.
