### ISSUE TITLE
I can not run zephir build on windows

### ISSUE THREAD

**Issue by eureka2** [zephir-lang/zephir#2019]
Hi,

with :

os version : Windows 10
php version : 7.3.9 
zephir version : 0.12.12

I cannot compile my first [extension](https://docs.zephir-lang.com/0.12/en/tutorial)

Here are the commands I launched:

**********************************************************************
** Visual Studio 2017 Developer Command Prompt v15.0
** Copyright (c) 2017 Microsoft Corporation
**********************************************************************

C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools>`cd /var/www/html/phpext`
C:\var\www\html\phpext>`C:\php-sdk\bin\phpsdk_setvars`
C:\var\www\html\phpext>`zephir init Utils`
C:\var\www\html\phpext>`cd utils`
C:\var\www\html\phpext\utils>`zephir build
`
 **! [NOTE] Installation is not implemented for Windows yet. Aborting.**

C:\var\www\html\phpext\utils>`zephir compile`
 Preparing for PHP compilation...
 Preparing configuration file...
 Compiling...

C:\var\www\html\phpext\utils>`zephir install`

 **! [NOTE] Installation is not implemented for Windows yet. Aborting.**

C:\var\www\html\phpext\utils>`cd ext`
C:\var\www\html\phpext\utils\ext>`configure`

> Saving configure options to config.nice.bat
> Checking for cl.exe ...  <in default path>
>   Detected compiler MSVC15 (Visual C++ 2017)
>   Detected 32-bit compiler
> Checking for link.exe ...  &lt;in default path>
> Checking for nmake.exe ...  &lt;iin default path>
> Checking for lib.exe ...  &lt;iin default path>
> Checking for bison.exe ...  &lt;iin default path>
>   Detected bison version 3.3.2
> Checking for sed.exe ...  &lt;iin default path>
> Checking for re2c.exe ...  &lt;iin default path>
>   Detected re2c version 1.1.1
> Checking for zip.exe ...  &lt;iin default path>
> Checking for lemon.exe ...  &lt;iin default path>
> Checking for 7za.exe ...  &lt;iin default path>
> Checking for mc.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86
> Checking for mt.exe ...  C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x86
> 
> Build dir: C:\var\www\html\phpext\utils\ext\Release_TS
> PHP Core:  php7ts.dll and php7ts.lib
> 
> 
> Creating build dirs...
> Generating files...
> Generating Makefile
> Generating main/config.pickle.h
> Generating pickle deps
> Done.
> 
> 
> 
> Enabled extensions:
> +-----------+-------+
> | Extension  | Mode |
> 
> 
> +------------------+-----------------------------+
> |                             |                                            |
> +------------------+-----------------------------+
> | Build type           | Release                                |
> | Thread Safety     | Yes                                       |
> | Compiler            | MSVC15 (Visual C++ 2017) |
> | Architecture       | x86                                       |
> | Optimization      | PGO disabled                       |
> | Native intrinsics | SSE2                                      |
> | Static analyzer   | disabled                                |
> 
> 
> Type 'nmake' to build PHP

C:\var\www\html\phpext\utils\ext>`nmake`

Microsoft (R) Program Maintenance Utility Version 14.16.27026.1
Copyright (C) Microsoft Corporation. Tous droits réservés.

C:\var\www\html\phpext\utils\ext>

What's wrong ?

Thanks for your help

Best regards

**Comment by sergeyklay** [comment]
@eureka2 There should be log file. Could you please attach this file to the issue?

**Comment by eureka2** [comment]
Thank you for your reply,
here are the log files:
[compile.log](https://github.com/phalcon/zephir/files/3889051/compile.log)
[compile-errors.log](https://github.com/phalcon/zephir/files/3889052/compile-errors.log)

**Comment by sergeyklay** [comment]
Looks like it is _linking issue_ related to incorrectly configured environment. Do you use standard PHP setup?

**Comment by sergeyklay** [comment]
FYI: There is AppVeyor setup to build test extension. Fill free to borrow any part of it:
https://github.com/phalcon/zephir/blob/development/appveyor.yml

**Comment by eureka2** [comment]
Hi @sergeyklay,

I found !
The DOS shell  must be started as an **administrator**

However 'zephir buid' does not work on Windows!
We must successively execute::
`zephir init Utils`
`cd utils`
`zephir compile`
`cd ext`
`./configure`
`nmake`

Thanks for your help

This issue can be closed

Best regards
