### ISSUE TITLE
Zephir very slow...

### ISSUE THREAD

**Issue by ismail0234** [zephir-lang/zephir#2047]
I rewrote an existing library with zephir. The difference between the results was very large while testing. Do I need to do something about optimization while compiling?

I compile on windows. (PHP 7.3 TS X64)

**ZEPHIR**

> 1.2733 second
> 1.2994 second
> 1.3462 second
> 1.3551 second
> 1.3623 second
> 1.3793 second
> 

**PHP**

> 0.5676 second
> 0.5759 second
> 0.5843 second
> 0.6069 second
> 0.6084 second
> 0.6774 second

**Comment by sergeyklay** [comment]
Please provide a full list of enabled extensions, as well as the project code and used benchmark

**Comment by ismail0234** [comment]
Zephir Version Files:
https://github.com/ismail0234/pdodatabase-zephir

PHP Version Files:
https://github.com/ismail0234/pdodatabase


Benchmark Code:
```php

$start = microtime(1);
use IS\QueryBuilder\Database\PDOClient;
$db = new PDOClient(array(
    // Server Ip Default: localhost
    'ip'         => 'localhost',
    // Database Name
    'database'   => 'test',
    // Database Engine Name oracle,mysql ...
    'dbengine'   => 'mysql',
    // Database Username
    'username'   => 'root',
    // Database Password
    'password'   => '',
    // Database Charset Default: utf8
    'charset'    => 'utf8',
    // Database table prefix Default: null
    'prefix'     => '',
    // Persistent Database Connection Time
    'persistent' => 30,
    // Database query log Default: off
    'querylog'   => true,
    // Database Send Exception Default: on
    'exception'  => false,
));



for ($i = 0; $i < 100000; $i++) {
    $db->select('*')->from('users' . $i);
    $db->having('a', 'b');
    $db->where('test', 'x')->whereIn('abc', array(1, 2, 3, 4, 5));
    $db->orderby('cfg', 'DESC');
    $db->clearQuery();
}

echo number_format((microtime(1) - $start), 25, ".", ""). '<br>';
```

[PHP Modules]
```php
bcmath
bz2
calendar
Core
ctype
curl
date
dom
exif
fileinfo
filter
gd
gettext
gmp
hash
iconv
imap
intl
json
ldap
libxml
mbstring
mysqli
mysqlnd
odbc
openssl
pcre
PDO
pdo_mysql
PDO_ODBC
pdo_pgsql
pdo_sqlite
pgsql
Phar
readline
Reflection
session
shmop
SimpleXML
SPL
standard
tokenizer
wddx
xml
xmlreader
xmlwriter
Zephir Parser
zip
zlib
```
@sergeyklay

**Comment by ismail0234** [comment]
@sergeyklay is there any improvement?

**Comment by sergeyklay** [comment]
@ismail0234 I didn't even have the time to prove that the issue is exists. So no, there is no improvement. I'm sorry for the delay. I'll try to deal as soon as possible. 

@dreamsxin Could you take a look by any chance?

**Comment by Jurigag** [comment]
Pdo is already provided as extension, moving the same php code to zephir code won't speed up your application, it will actually it.

**Comment by Ultimater** [comment]
I'll take a look at this.
