### ISSUE TITLE
Strange binary size growth

### ISSUE THREAD

**Issue by colorvamp** [zephir-lang/zephir#2066]
With newer versions of zephir, the extension size had become 3 times bigger which seems very strange to me. I asked first here: https://forum.phalcon.io/discussion/20367/zephir-compiled-binary-size before opening a bug report.

Taking exactly this simple code:

```zep
	namespace Test01;

	class innerserver{
		public static version = 1001;
		public static name = "";
		public static dbprefix = "";
		public static ip = null;
		public static function name() -> string{
			if (self::name !== "") {return self::name;}

			var line;
			if (!empty(_SERVER["DOCUMENT_ROOT"])) {
				let line = _SERVER["DOCUMENT_ROOT"];
			} else {
				let line = getcwd();
			}

			var r = false;
			var m = [];
			let r = preg_match("!(?<name>[^\/\.]+)\.test\.com!",line,m);
			let self::name = r ? m["name"] : "";
			return self::name;
		}
		public static function dbprefix() -> string{
			if (self::dbprefix !== "") {return self::dbprefix;}

			var name;
			var pos;
			var prefix;

			let name = self::name();
			if (name == "alfa") {
				let name = "sigma";
			}

			let pos = strpos(name,"-");
			if (pos !== false) {
				let prefix = substr(name,0,2).substr(name,pos + 1,2);
			} else {
				let prefix = substr(name,0,4);
			}

			let self::dbprefix = prefix;
			return self::dbprefix;
		}
		public static function ip() -> string|bool{
			if (self::ip !== null) {return self::ip;}

			if (isset(_SERVER["SERVER_ADDR"]) && !empty(_SERVER["SERVER_ADDR"])) {
				let self::ip = _SERVER["SERVER_ADDR"];
				return self::ip;
			}

			var name = "";
			var file = "";
			var blob = "";
			var r = false;
			var m = [];

			let name = self::name();
			let file = "/etc/nginx/sites-available/".name.".test.com";
			if (file_exists(file)) {
				let blob = file_get_contents(file);
				let r = preg_match("!listen (?<ip>[0-9]+.[0-9]+.[0-9]+.[0-9]+):80;!",blob,m);
				if (r) {
					let self::$ip = m["ip"];
					return self::ip;
				}
			}

			return false;
		}
	}
```

Old version:
zephir --version
Zephir 0.12.2 by Andres Gutierrez and Serghei Iakovlev (b3f17c25)
Resulting Module Size: 42.7KB

New version:
zephir.phar --version
Zephir 0.12.17 by Andres Gutierrez and Serghei Iakovlev (6724dbf)
Resulting Module Size: 140.7KB

I always delete 'ext' folder before doing a new build because "zephir clean" sometimes is not enough and produce mixed results.

Thanks

**Comment by sergeyklay** [comment]
@colorvamp Did you compare results using `zephir build` with `--no-dev`?


P.S. There is `zephir fullclean` command in addition to `zephir clean`.

**Comment by colorvamp** [comment]
Yes, I even deleted "ext" folder.
Casually yesterday I was working a bit on this and comparing generated files. The main change is a lot of "TSRMLS_CC" disappeared

**Comment by sergeyklay** [comment]
Yes, TSRMLS_CC is deprecated. Thus it has been removed from Zephir

**Comment by colorvamp** [comment]
ok, other than that there are no changes in generated code i can appreciate. I was checking for new dependencies that can justify the x3 binary size, but the number of includes remains the same.
