### ISSUE TITLE
Undefined index: value

### ISSUE THREAD

**Issue by ghost** [zephir-lang/zephir#2071]
My code compilation is returning the following error inside zephir. zephir/Library/Operators/Bitwise/BitwiseBaseOperator.php line 196.

Like this:
In BitwiseBaseOperator.php line 196:
                          
  [ErrorException]        
  Undefined index: value  
                          

Exception trace:
  at phar:///usr/bin/zephir/Library/Operators/Bitwise/BitwiseBaseOperator.php:196
 Zephir\{closure}() at phar:///usr/bin/zephir/Library/Operators/Bitwise/BitwiseBaseOperator.php:196
 Zephir\Operators\Bitwise\BitwiseBaseOperator->compile() at phar:///usr/bin/zephir/Library/Expression.php:600
 Zephir\Expression->compile() at phar:///usr/bin/zephir/Library/Expression.php:513
 Zephir\Expression->compile() at phar:///usr/bin/zephir/Library/Operators/Unary/NotOperator.php:38
 Zephir\Operators\Unary\NotOperator->compile() at phar:///usr/bin/zephir/Library/Expression.php:600
 Zephir\Expression->compile() at phar:///usr/bin/zephir/Library/Optimizers/EvalExpression.php:93
 Zephir\Optimizers\EvalExpression->optimize() at phar:///usr/bin/zephir/Library/Statements/IfStatement.php:36
 Zephir\Statements\IfStatement->compile() at phar:///usr/bin/zephir/Library/StatementsBlock.php:225
 Zephir\StatementsBlock->compile() at phar:///usr/bin/zephir/Library/ClassMethod.php:1871
 Zephir\ClassMethod->compile() at phar:///usr/bin/zephir/Library/ClassDefinition.php:1262
 Zephir\ClassDefinition->compile() at phar:///usr/bin/zephir/Library/CompilerFile.php:263
 Zephir\CompilerFile->compileClass() at phar:///usr/bin/zephir/Library/CompilerFile.php:857
 Zephir\CompilerFile->compile() at phar:///usr/bin/zephir/Library/Compiler.php:713
 Zephir\Compiler->generate() at phar:///usr/bin/zephir/Library/Console/Command/GenerateCommand.php:72
 Zephir\Console\Command\GenerateCommand->execute() at phar:///usr/bin/zephir/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/zephir/vendor/symfony/console/Application.php:1001
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/zephir/vendor/symfony/console/Application.php:255
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/zephir/Library/Console/Application.php:162
 Zephir\Console\Application->doRun() at phar:///usr/bin/zephir/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at phar:///usr/bin/zephir/zephir:21
 require() at /usr/bin/zephir:17

**Comment by AlexNDRmac** [comment]
@joaorsilva can you give code sample which causes this error?
