### ISSUE TITLE
[ERROR] File not found at path: 0.12.17-6724dbf/gcc-version

### ISSUE THREAD

**Issue by maybeTomorrow** [zephir-lang/zephir#2072]
Zephir 0.12.17 by Andres Gutierrez and Serghei Iakovlev (6724dbf)

php -v
PHP 7.3.16 (cli) (built: Mar 26 2020 11:13:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.16, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.16, Copyright (c) 1999-2018, by Zend Technologies

phpize -v
Configuring for:
PHP Api Version:         20180731
Zend Module Api No:      20180731
Zend Extension Api No:   320180731

使用内建 specs。
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
目标：x86_64-redhat-linux
gcc 版本 4.8.5 20150623 (Red Hat 4.8.5-39) (GCC) 

zephir build 
 Preparing for PHP compilation...
 Preparing configuration file...

                                                                                
 [ERROR] File not found at path: 0.12.17-6724dbf/gcc-version

**Comment by sergeyklay** [comment]
@maybeTomorrow Is this works for you?

```bash
$ zephir fullclean
$ zephir build
```

**Comment by sergeyklay** [comment]
I'm closing this issue due to the lack of any reaction. I'll open it again if the need arises
