### ISSUE TITLE
How to call win32 api using zephir？

### ISSUE THREAD

**Issue by thinker-gao** [zephir-lang/zephir#2077]
How to call win32 api using zephir？Not seen in the documentation

**Comment by ViltusVilks** [comment]
build .NET proxy app and use dotnet class in php to invoke methods.

**Comment by thinker-gao** [comment]
Can't you use zephir to call win32api directly?

**Comment by ViltusVilks** [comment]
if You write custom h/c files and put it on compilation stage then probably yes.
