### ISSUE TITLE
Failed to compile on windows

### ISSUE THREAD

**Issue by yogawa** [zephir-lang/zephir#2081]
Environtment
```
Windows 10 Pro x64
Zephir 0.12.17
Visual Studio Community Edition 2019
```

i execute `zephir compile` command in my project directory and this is the result

```
D:\test\zephir>zephir compile
The system cannot find the path specified.
 Preparing for PHP compilation...
The system cannot find the path specified.
 Preparing configuration file...
 Compiling...
```

and this is the contents of compile-errors.log file

```
Microsoft (R) Program Maintenance Utility Version 14.25.28614.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1064: MAKEFILE not found and no target specified
Stop.
```

**Comment by sergeyklay** [comment]
@yogawa Is `zephir generate` does the work? This command should generate C-code as well as prepare all the required files.

**Comment by yogawa** [comment]
@sergeyklay yes, `zephir generate` does the work
when i executed `zephir generate` command, no error message displayed on the console

So what exactly program that not found in the error message "The system cannot find the path specified."

**Comment by sergeyklay** [comment]
@yogawa Most likely it is `%PHP_DEVPACK%\\phpize`. Could you please ensure you have `%PHP_DEVPACK%` environment variable pointed to PHP Developer pack installation path.

**Comment by yogawa** [comment]
@sergeyklay  i forgot to add `PHP_DEVPACK` and `PHP_SDK` path
thank you very much

case closed

**Comment by sergeyklay** [comment]
You're welcome
