### ISSUE TITLE
Can't set default array value on extends

### ISSUE THREAD

**Issue by mruz** [zephir-lang/zephir#2089]
Zephir
```zep
namespace Ice;

class Test
{
    protected rules = [] { set, get };
}
```

PHP
```php
<?php
use Ice\Test;

class Users extends Test
{
    protected $rules = [
        'username' => 'required',
    ];
}

$user = new Users();
var_dump($user->getRules());

$user->setRules([
        'username' => 'required'
]);

var_dump($user->getRules());
```

Output:
```
array(0) {
}
array(1) {
  ["username"]=>
  string(8) "required"
}
```

Expected to get it after an object is initialized. Looks like https://github.com/phalcon/zephir/issues/537 returned.

> PHP 7.4.5 (cli) ( NTS )
> Copyright (c) The PHP Group
> Zend Engine v3.4.0, Copyright (c) Zend Technologies

**Comment by sergeyklay** [comment]
@mruz Could you please check previous Zephir version just to clarify we don't break anything in https://github.com/phalcon/zephir/pull/2078

**Comment by mruz** [comment]
@sergeyklay seems fine on zephir 0.12.17, I also added a test for it.

**Comment by sergeyklay** [comment]
@dreamsxin I need your help here. Could you please take a look. Also see https://github.com/phalcon/zephir/pull/2090

**Comment by dreamsxin** [comment]
@sergeyklay create_object  is later than declare property.
```c
test_properties_protectedproperties_ce->create_object = zephir_init_properties_Test_Properties_ProtectedProperties;
```

**Comment by sergeyklay** [comment]
Fixed in the `development` branch. Thank you for the bug report!

**Comment by mruz** [comment]
@sergeyklay thank you!

**Comment by sergeyklay** [comment]
You're welcome
