### ISSUE TITLE
[Bug] Can't install on Ubuntu 20.04 LTS

### ISSUE THREAD

**Issue by OrangeTanguine** [zephir-lang/zephir#2095]
Hi !
The Repository installation does not work.
I have an error message when i do an apt-get update :

> The repository 'https://packagecloud.io/phalcon/stable/ubuntu focal Release' does not have a Release file

**Comment by sergeyklay** [comment]
Hello,

I'll prepare packages ASAP. This issue is duplicate for: https://github.com/phalcon/cphalcon/issues/14958.

Thank you for the report!
