### ISSUE TITLE
Syntax error in objects containing subobjects

### ISSUE THREAD

**Issue by rigin** [zephir-lang/zephir#2106]
Hello,

When using type constructs.
```
let io = new \stdClass();
let io->answer = new \stdClass();

let io->answer->{key} = value;
```
an error occurs in the line.

`let io->answer->{key} = value;`

The compiler does not allow assigning a value to a property of a subobject.

Respectfully,
Vadim Rigin.

**Comment by Jeckerson** [comment]
It is only possible to declare separately:

```zep
var answer, io;
let io = new \stdClass();

let answer = new \stdClass();
let answer->key = "123";

let io->answer = answer;
```
