### ISSUE TITLE
On Ubuntu: Zephir not running and says permission denied

### ISSUE THREAD

**Issue by fakharak** [zephir-lang/zephir#2107]
I am using Ubuntu 18.04 and PHP 7.4.8, i am installing Zephir using .PHAR and following the instructions in official documentation having link:

https://docs.zephir-lang.com/0.12/en/installation

Heading: "Release PHAR"

I downloaded zephir.phar, renamed it to zephir (as per instructions) and pasted it into /usr/bin (which is in $PATH).

Now when i run zephir, i get this as output
Permission Denied.

Please let me know the correct method to isntall it in Ubuntu.

**Comment by sergeyklay** [comment]
@fakharak Did you change file mode (`sudo chmod +x /usr/bin/zephir`)?

**Comment by fakharak** [comment]
Yes @sergeyklay , i made it executable (but not from the command line) and it worked but now i am having another issue: 

When i run it from /home/ubuntu (Ubuntu is my default user on EC2 Instance that looks like ~/  on terminal ) it does not show any issue and runs correctly, but when i run ti from any sub-folder like from within "Downloads" or "Pictures" it gives this error which i am not able to rectify:
---- Issue---
PHP Fatal error:  Uncaught RuntimeException: Unable to create logs directory: "/home/ubuntu/.local/state/zephir/1cf969726aaaeca1" in phar:///usr/bin/zephir/Library/DependencyInjection/ZephirKernel.php:153
Stack trace:
#0 phar:///usr/bin/zephir/vendor/symfony/http-kernel/Kernel.php(762): Zephir\DependencyInjection\ZephirKernel->getLogDir()
#1 phar:///usr/bin/zephir/vendor/symfony/http-kernel/Kernel.php(642): Symfony\Component\HttpKernel\Kernel->buildContainer()
#2 phar:///usr/bin/zephir/vendor/symfony/http-kernel/Kernel.php(135): Symfony\Component\HttpKernel\Kernel->initializeContainer()
#3 phar:///usr/bin/zephir/Library/DependencyInjection/ContainerFactory.php(46): Symfony\Component\HttpKernel\Kernel->boot()
#4 phar:///usr/bin/zephir/zephir(18): Zephir\DependencyInjection\ContainerFactory->create()
#5 /usr/bin/zephir(17): require('phar:///usr/bin...')
#6 {main}
  thrown in phar:///usr/bin/zephir/Library/DependencyInjection/ZephirKernel.php on line 153

**Comment by sergeyklay** [comment]
Hm...
As a workaround try to create /home/ubuntu/.local/state/zephir by hand.

**Comment by fakharak** [comment]
@sergeyklay Resolved But in a  different way:

The folders "/home/ubuntu/.cache" and "/home/ubuntu/.local" both were already there but they were (perhaps) hidden.

I noticed those folders only when i executed the command "ls -la" from within /home/ubuntu/ ...

... then i resolved the issue by changing the permissions of ".cache" and ".local" folders using ...

sudo chmod g+rwX -R .local
sudo chmod g+rwX -R ./.local

sudo chmod g+rwX -R .cache
sudo chmod g+rwX -R ./.local

(I am a little new on Ubuntu, though so i typed both forms like .cache and ./cache at the end of those commands).

You can please guide me which one is more appropriate. (I am still testing from other folders, like sub-folders of sub-folders and parent folders of /ubuntu)

**Comment by sergeyklay** [comment]
Well, `$HOME/.local` (which is `/home/ubuntu/.local` in your case) must be writable by the user on whose behalf it zephir is running (a least it should have enough privilege to create state files in `$HOME/.local/state/zephir/*`). That's expected.

**Comment by fakharak** [comment]
Great thanks @sergeyklay for the prompt response. That is much helpful, really appreciate. Regards.

**Comment by sergeyklay** [comment]
Can I close this issue?
