### ISSUE TITLE
When compiling an application that contains camelcase class and namespace names, the compiler converts all file and folder names to lowercase.

### ISSUE THREAD

**Issue by rigin** [zephir-lang/zephir#2109]
When compiling an application that contains camelcase class and namespace names (and, accordingly, camelcase folder and file names), the compiler converts all file and folder names to lowercase.

Screenshot
https://yadi.sk/i/ayKU74mHjqYA9g 

This causes compilation errors.

`make: *** Нет правила для сборки цели «/home/rigin/D/YandexDisk/lighttpd/htdocs/dev/zephir/Cat/ext/cat.c», требуемой для «cat.lo».  Останов.`

When renaming the root generated files .c and .h to lower case, the compiler generates a lot of errors related to case mismatch between class names and file names.

**Comment by AlexNDRmac** [comment]
Which version of Zephir and which OS are you using?

**Comment by rigin** [comment]
Zephir 0.12.19  Ubuntu 18.04

**Comment by rigin** [comment]
And I tried to rewrite the code to lower case, but the compiler gives an error. requires "Namespace 'cat' must be in camelized-form"
And all in a circle.

```
In file included from /home/rigin/D/YandexDisk/lighttpd/htdocs/dev/zephir/cat/ext/cat/basetaskbaze.zep.c:14:0:
/home/rigin/D/YandexDisk/lighttpd/htdocs/dev/zephir/cat/ext/cat/basetaskbaze.zep.c: In function ‘zephir_Cat_basetaskbaze_init’:
/home/rigin/D/YandexDisk/lighttpd/htdocs/dev/zephir/cat/ext/cat/basetaskbaze.zep.c:26:46: error: ‘Cat_cat_basetaskbaze_ce’ undeclared (first use in this function); did you mean ‘cat_basetaskbaze_ce’?
```
https://yadi.sk/d/SiBwJzFzx64prw

**Comment by AlexNDRmac** [comment]
Ok, I'll try to sort out with it.

**Comment by Jeckerson** [comment]
@rigin Could you provide simple and minimal example of code?

**Comment by rigin** [comment]
This project was a year ago.
Everything has changed since then. And I decided to have nothing more to do with either Zephir or Phalcon.
