### ISSUE TITLE
[ERROR] File not found at path: 0.12.19-4345593/gcc-version

### ISSUE THREAD

**Issue by zubin999** [zephir-lang/zephir#2112]
when i run `zephir build`, i got this error:
`[ERROR] File not found at path: 0.12.19-4345593/gcc-version`

i installed  zephir the latest version on centos 8.

**Comment by zubin999** [comment]
> [root@localhost utils]# lsb_release -a
LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: CentOS
Description:    CentOS Linux release 8.2.2004 (Core)
Release:        8.2.2004
Codename:       Core

**Comment by zubin999** [comment]
> [root@localhost utils]# gcc --version
gcc (GCC) 8.3.1 20191121 (Red Hat 8.3.1-5)
Copyright (C) 2018 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

**Comment by zubin999** [comment]
[root@localhost utils]# make --version
GNU Make 4.2.1
Built for x86_64-redhat-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

**Comment by ty840320** [comment]
和你一样的错误,你用centos7就可以了.8会报这个错误,我也没找到解决办法

The same mistake as you, you can use CentOS 7

**Comment by Jeckerson** [comment]
```
yum install php-devel gcc make re2c autoconf automake
```
