### ISSUE TITLE
Use variable inside a cblock

### ISSUE THREAD

**Issue by churiart** [zephir-lang/zephir#2117]
Suppose following zep file `db.zep`:

```
namespace Pwdb;
%{
#include "whitedb/dbapi.h"
}%
class Db
{
    public function __construct(dbname, int size)
    {
        %{
        void *db;
        db = wg_attach_database(dbname, size);
        void *rec = wg_create_record(db, 10);
        wg_int enc = wg_encode_str(db, "Hello", NULL);
        wg_set_field(db, rec, 7, enc);
        }%
    }
}
```

and this definition of `wg_attach_database`:

```
void* wg_attach_database(const char* dbasename, gint size){
  void* shm = wg_attach_memsegment(dbasename, size, size, 1, 0, 0);
  CHECK_SEGMENT(shm)
  return shm;
}
```

first of all I can't type hint `dbname` in constructor otherwise I'll get these compile time errors:

```
/data/projects/pwdb/ext/pwdb/db.zep.c: In function ‘zim_Pwdb_Db___construct’:
/data/projects/pwdb/ext/pwdb/db.zep.c:50:33: error: incompatible type for argument 1 of ‘wg_attach_database’
   50 |         db = wg_attach_database(dbname, sizze);
      |                                 ^~~~~~
      |                                 |
      |                                 zval {aka struct _zval_struct}
In file included from /data/projects/pwdb/ext/pwdb/db.zep.c:19:
/usr/local/include/whitedb/dbapi.h:128:7: note: expected ‘const char *’ but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
  128 | void* wg_attach_database(const char* dbasename, wg_int size); // returns a pointer to the database, NULL if failure
      |       ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:234: pwdb/db.lo] Error 1
/data/projects/pwdb/ext/pwdb/db.zep.c: In function ‘zim_Pwdb_Db___construct’:
/data/projects/pwdb/ext/pwdb/db.zep.c:50:33: error: incompatible type for argument 1 of ‘wg_attach_database’
   50 |         db = wg_attach_database(dbname, sizze);
      |                                 ^~~~~~
      |                                 |
      |                                 zval {aka struct _zval_struct}
In file included from /data/projects/pwdb/ext/pwdb/db.zep.c:19:
/usr/local/include/whitedb/dbapi.h:128:7: note: expected ‘const char *’ but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
  128 | void* wg_attach_database(const char* dbasename, wg_int size); // returns a pointer to the database, NULL if failure
      |       ^~~~~~~~~~~~~~~~~~
make: *** [Makefile:234: pwdb/db.lo] Error 1
```

second, if I don't do type hinting build is successful and following PHP code runs with exiting code `0`:

```
<?php

new Pwdb\Db("4000", 200000);
```

but `wg_attach_database` which is responsible for creating a db named `4000` seems to ignore it since it won't get created.

So my question is what is the workaround here to inject zephir variables into cblocks correctly?

**Comment by ghost** [comment]
Simply create file db.zep with this content 
```
namespace Pwdb;
%{
#include "whitedb/dbapi.h"
}%
class Db
{
    public function __construct(dbname, int size)
    {

    }
}
```
Then run command **zephir generate**. zephir will generate file ./ext/pwdb/db.c. Open it. Now you can see C code of class **db** and all it methods, find method **__construct** and see all variables that you can use in C block code. Advice: do not use variables generated by zephir directly in your C code, better create your own copies, it will save you from incomprehensible problems and undefined behavior, don't forget to clear your variables.

**Comment by churiart** [comment]
> Simply create file db.zep with this content
> 
> ```
> namespace Pwdb;
> %{
> #include "whitedb/dbapi.h"
> }%
> class Db
> {
>     public function __construct(dbname, int size)
>     {
> 
>     }
> }
> ```
> 
> Then run command **zephir generate**. zephir will generate file ./ext/pwdb/db.c. Open it. Now you can see C code of class **db** and all it methods, find method **__construct** and see all variables that you can use in C block code. Advice: do not use variables generated by zephir directly in your C code, better create your own copies, it will save you from incomprehensible problems and undefined behavior, don't forget to clear your variables.

Thank you, but then how can I compile that `zep.c` file solely? Because running `zephir compile` rewrites all my changes to aforementioned `zep.c` file.

**Comment by ghost** [comment]
> > Simply create file db.zep with this content
> > ```
> > namespace Pwdb;
> > %{
> > #include "whitedb/dbapi.h"
> > }%
> > class Db
> > {
> >     public function __construct(dbname, int size)
> >     {
> > 
> >     }
> > }
> > ```
> > 
> > 
> > Then run command **zephir generate**. zephir will generate file ./ext/pwdb/db.c. Open it. Now you can see C code of class **db** and all it methods, find method **__construct** and see all variables that you can use in C block code. Advice: do not use variables generated by zephir directly in your C code, better create your own copies, it will save you from incomprehensible problems and undefined behavior, don't forget to clear your variables.
> 
> Thank you, but then how can I compile that `zep.c` file solely? Because running `zephir compile` rewrites all my changes to aforementioned `zep.c` file.

You must add c blocks of code to db.zep, not to db.c, then run **zephir build**. It generate new db.c with your changes and then compile it. You can read about zephir commands by run **zephir help**.
