### ISSUE TITLE
Error in Zephir build: [ERROR] Internal extension compilation failed. Check compile-errors.log for more information.

### ISSUE THREAD

**Issue by vssir** [zephir-lang/zephir#2131]
**Error in Zephir build:**

![zephir_err](https://user-images.githubusercontent.com/10388068/105167719-0689b280-5b54-11eb-947c-478fe6713e32.png)

 **compile-errors.log:**
`In file included from /opt/php/include/php/Zend/zend.h:27,
                 from /opt/php/include/php/main/php.h:33,
                 from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:6:
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c: In function ‘zim_Hxcrypt_hxcrypt_encode’:
/opt/php/include/php/Zend/zend_types.h:451:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:451:28: note: in expansion of macro ‘Z_TYPE’
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:31: note: in expansion of macro ‘Z_TYPE_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                               ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:678:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:678:28: note: in expansion of macro ‘Z_LVAL’
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:56: note: in expansion of macro ‘Z_LVAL_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                                                        ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:42: error: incompatible type for argument 1 of ‘zephir_get_intval_ex’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                                          ^~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
In file included from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:15:
./kernel/operators.h:108:39: note: expected ‘const zval *’ {aka ‘const struct _zval_struct *’} but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
 long zephir_get_intval_ex(const zval *op);
                           ~~~~~~~~~~~~^~
In file included from /opt/php/include/php/Zend/zend.h:27,
                 from /opt/php/include/php/main/php.h:33,
                 from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:6:
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c: In function ‘zim_Hxcrypt_hxcrypt_decode’:
/opt/php/include/php/Zend/zend_types.h:451:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:451:28: note: in expansion of macro ‘Z_TYPE’
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:31: note: in expansion of macro ‘Z_TYPE_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                               ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:678:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:678:28: note: in expansion of macro ‘Z_LVAL’
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:56: note: in expansion of macro ‘Z_LVAL_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                                                        ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:42: error: incompatible type for argument 1 of ‘zephir_get_intval_ex’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                                          ^~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
In file included from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:15:
./kernel/operators.h:108:39: note: expected ‘const zval *’ {aka ‘const struct _zval_struct *’} but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
 long zephir_get_intval_ex(const zval *op);
                           ~~~~~~~~~~~~^~
make: *** [Makefile:232: hxcrypt/hxcrypt.lo] Error 1
In file included from /opt/php/include/php/Zend/zend.h:27,
                 from /opt/php/include/php/main/php.h:33,
                 from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:6:
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c: In function ‘zim_Hxcrypt_hxcrypt_encode’:
/opt/php/include/php/Zend/zend_types.h:451:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:451:28: note: in expansion of macro ‘Z_TYPE’
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:31: note: in expansion of macro ‘Z_TYPE_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                               ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:678:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:678:28: note: in expansion of macro ‘Z_LVAL’
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:56: note: in expansion of macro ‘Z_LVAL_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                                                        ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:42: error: incompatible type for argument 1 of ‘zephir_get_intval_ex’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                                          ^~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:156:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_21$$7, ~zephir_get_intval(_20$$7));
                        ^~~~~~~~~~~~~~~~~
In file included from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:15:
./kernel/operators.h:108:39: note: expected ‘const zval *’ {aka ‘const struct _zval_struct *’} but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
 long zephir_get_intval_ex(const zval *op);
                           ~~~~~~~~~~~~^~
In file included from /opt/php/include/php/Zend/zend.h:27,
                 from /opt/php/include/php/main/php.h:33,
                 from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:6:
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c: In function ‘zim_Hxcrypt_hxcrypt_decode’:
/opt/php/include/php/Zend/zend_types.h:451:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:451:28: note: in expansion of macro ‘Z_TYPE’
 #define Z_TYPE_P(zval_p)   Z_TYPE(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:31: note: in expansion of macro ‘Z_TYPE_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                               ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:678:35: error: invalid type argument of unary ‘*’ (have ‘zval’ {aka ‘struct _zval_struct’})
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                                   ^~~~~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/opt/php/include/php/Zend/zend_types.h:678:28: note: in expansion of macro ‘Z_LVAL’
 #define Z_LVAL_P(zval_p)   Z_LVAL(*(zval_p))
                            ^~~~~~
./kernel/operators.h:151:56: note: in expansion of macro ‘Z_LVAL_P’
 #define zephir_get_intval(z) (Z_TYPE_P(z) == IS_LONG ? Z_LVAL_P(z) : zephir_get_intval_ex(z))
                                                        ^~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:42: error: incompatible type for argument 1 of ‘zephir_get_intval_ex’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                                          ^~~~~~
/opt/php/include/php/Zend/zend_types.h:780:19: note: in definition of macro ‘ZVAL_LONG’
   Z_LVAL_P(__z) = l;    \
                   ^
/root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:292:24: note: in expansion of macro ‘zephir_get_intval’
    ZVAL_LONG(&_20$$7, ~zephir_get_intval(_19$$7));
                        ^~~~~~~~~~~~~~~~~
In file included from /root/work/hxcrypt/ext/hxcrypt/hxcrypt.zep.c:15:
./kernel/operators.h:108:39: note: expected ‘const zval *’ {aka ‘const struct _zval_struct *’} but argument is of type ‘zval’ {aka ‘struct _zval_struct’}
 long zephir_get_intval_ex(const zval *op);
                           ~~~~~~~~~~~~^~
make: *** [Makefile:232: hxcrypt/hxcrypt.lo] Error 1`

How to solve this problem? thanks!

**Comment by vssir** [comment]
image
![zephir_err](https://user-images.githubusercontent.com/10388068/105168491-29689680-5b55-11eb-899d-dd2f686b6466.png)

**Comment by vssir** [comment]
**My PHP version:**

`PHP 7.4.13 (cli) (built: Dec  3 2020 14:43:37) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
`

thanks!

**Comment by AlexNDRmac** [comment]
@vssir could you provide steps to reproduce?

**Comment by vssir** [comment]
@AlexNDRmac 
**1. zephir init hxcrypt
2. Write hxcrypt.zep（vim content /root/work/hxcrypt/hxcrypt/hxcrypt.zep）
3. The file directory structure is as follows:**
[root@centos-dev hxcrypt]# tree
.
├── config.json
├── ext
│   └── kernel
│       ├── array.c
│       ├── array.h
│       ├── backtrace.c
│       ├── backtrace.h
│       ├── debug.c
│       ├── debug.h
│       ├── exception.c
│       ├── exception.h
│       ├── exit.c
│       ├── exit.h
│       ├── fcall.c
│       ├── fcall.h
│       ├── file.c
│       ├── file.h
│       ├── filter.c
│       ├── filter.h
│       ├── globals.h
│       ├── iterator.c
│       ├── iterator.h
│       ├── main.c
│       ├── main.h
│       ├── math.c
│       ├── math.h
│       ├── memory.c
│       ├── memory.h
│       ├── object.c
│       ├── object.h
│       ├── operators.c
│       ├── operators.h
│       ├── README.md
│       ├── require.c
│       ├── require.h
│       ├── string.c
│       ├── string.h
│       ├── time.c
│       ├── time.h
│       ├── variables.c
│       └── variables.h
└── hxcrypt
    └── hxcrypt.zep

**hxcrypt.zep code:**

namespace Hxcrypt;

class hxcrypt {

    public static function encode(string source, string key = "") {
        if empty(source) {
            return "";
        }

        if empty(key) {
            let key = "4297f44b13955235245b2497399d7a93";
        }

        var b = [];
        var b_key = [];
        var b_dest = [];
        int i = 0;

        for i in range(0, strlen(source)) {
            let b[] = ord(source[i]);
        }

        for i in range(0, strlen(key)) {
            let b_key[] = ord(key[i]);
        }

        for i in range(0, count(b)) {
            int k = i % 8;
            var cc = 0;
            if k < count(b_key) {
                let cc = b_key[k];
            }
            let b_dest[i] = bin2hex(~(chr(b[i]) ^ chr(cc)));
        }

        return implode("", b_dest);
    }

    public static function decode(string value, string key = "") {
        if empty(value) {
            return "";
        }

        if empty(key) {
            let key = "4297f44b13955235245b2497399d7a93";
        }

        var b = [];
        var b_dest = [];
        var b_key = [];
        int i = 0;

        float len = strlen(value) / 2;
        for i in range(0, len) {
            let b[i] = hexdec(substr(value, i * 2, 2));
        }

        for i in range(0, strlen(key)) {
            let b_key[i] = ord(key[i]);
        }

        for i in range(0, count(b)) {
            int k = i % 8;
            var cc = 0;
            if k < count(b_key) {
                let cc = b_key[k];
            }
            let b_dest[i] = chr(~( b[i] ^ cc ));
        }

        return implode("", b_dest);
    }

}


By the way, the build system is CentOS 8

thanks!

**Comment by vssir** [comment]
I just deleted the "~" build succeed. But my code must be "~", how to solve?
![image](https://user-images.githubusercontent.com/10388068/105273947-33cb7480-5bd7-11eb-8f43-5c53a3a80476.png)
thanks!

**Comment by Jeckerson** [comment]
You have syntax error in this line:
```
let b_dest[i] = bin2hex(~(chr(b[i]) ^ chr(cc)));
```

**Comment by vssir** [comment]
@Jeckerson  thank you!

**Comment by alirayaneh** [comment]
> You have syntax error in this line:
> 
> ```
> let b_dest[i] = bin2hex(~(chr(b[i]) ^ chr(cc)));
> ```

hi .
Where is his error?
And is it possible to correct it?
I'm looking for an open source ready to encrypt the code and PHP files of my project. Please help me.
