### ISSUE TITLE
Odd Issue With Closures And DI

### ISSUE THREAD

**Issue by Fenikkusu** [zephir-lang/zephir#2142]
I came across an odd issue in the extension I'm building. In it, I have a Service Provider where I'm calling `setShared` using a closure (`assets` in this case). When running the code, I got the error `Service 'assets' couldn't be resolved`. I tried commenting out the whole set, thinking it might be with the code, where I then got `Service 'config' couldn't be resolved'`. This made no sense to me as I knew the config service was working with assets defined. After re-adding assets and debugging it through the php entry file, I found that the `assets` service was defined, but the definition element was null. I realized while reviewing the C files that the `assets` element was closure 0. When I removed assets, now `config` was closure 0. As a simple test, I went to the first file in the system and added a dummy `doNothing` private method that just returned a closure. This allowed the system to start working correctly as expected.

**Comment by Jeckerson** [comment]
Please add script to reproduce.

**Comment by Jeckerson** [comment]
Feel free to reopen with code example.
