### ISSUE TITLE
Enable PHP8.0 for Windows in CI

### ISSUE THREAD

**Issue by Jeckerson** [zephir-lang/zephir#2173]
Figure out why latest PHP version isn't found and can't be downloaded.

**Comment by mruz** [comment]
> Run Import-Module .\.ci\win-ci-tools.psm1
Install PHP Dev pack: 8.0.1
Downloading PHP Dev pack: http://windows.php.net/downloads/releases/php-devel-pack-8.0.1-nts-Win32-vc15-x64.zip ...
WARNING: Error downloading http://windows.php.net/downloads/releases/php-devel-pack-8.0.1-nts-Win32-vc15-x64.zip: The remote server returned an error: (404) Not Found.

https://github.com/zephir-lang/zephir/blob/b69d27ee907665e7aaf317cd249b19be30d3f5c3/.ci/win-ci-tools.psm1#L65

php-devel-pack-7.4.16-nts-Win32-v**c15**-x64.zip
vs
php-devel-pack-8.0.3-nts-Win32-v**s16**-x64.zip
