### ISSUE TITLE
zephir init do not work

### ISSUE THREAD

**Issue by brucelin** [zephir-lang/zephir#2208]
Enviroment: 
- Ubuntu 20.04 
- php 7.4 
- zephir 0.13.2

I use ```zephir init``` to init an project, but when I compile the extension using ```zephir compile```, it shows me that ```php_ext.h``` was not found. I also notice that some other files (like ```configure,php_phalcon.h```) which are needed to comiple the project are also missing. I wonder whether the skeleton to init an project is wrong

**Comment by Jeckerson** [comment]
Try to use `zephir generate` before `compile`.

**Comment by brucelin** [comment]
> Try to use `zephir generate` before `compile`.

It solves the problem
