### ISSUE TITLE
Tutorial does not work for version 0.13

### ISSUE THREAD

**Issue by roukmoute** [zephir-lang/zephir#2238]
Hi,

The current documentation is out of date for 0.13.
Installation talk about php 7.3 but it is not supported anymore.
It talks about zephir-lang/zephir but it does not exist anymore.

I follow the first page on https://docs.zephir-lang.com/0.12/en/tutorial and when I do `zephir build` I've got an error : 

compile-errors.log:
```log
make: *** Pas de cible spécifiée et aucun makefile n'a été trouvé. Arrêt.
```

```
➜  zephir --version
Zephir 0.13.4 by Andres Gutierrez and Serghei Iakovlev (source)
➜  php --version
PHP 8.0.3 (cli) (built: Mar  4 2021 05:33:14) ( NTS )
Copyright (c) The PHP Group
Zend Engine v4.0.3, Copyright (c) Zend Technologies
    with Xdebug v3.0.2, Copyright (c) 2002-2021, by Derick Rethans
    with blackfire v1.55.0~linux-x64-non_zts80, https://blackfire.io, by Blackfire
➜  phpize --version
Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930
➜  make --version
GNU Make 4.3
Construit pour x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
Licence GPLv3+ : GNU GPL version 3 ou ultérieure <http://gnu.org/licenses/gpl.html>
Ceci est un logiciel libre : vous êtes autorisé à le modifier et à la redistribuer.
Il ne comporte AUCUNE GARANTIE, dans la mesure de ce que permet la loi.
```

**Comment by Jeckerson** [comment]
Hello

Try to execute `zephir generate` first.

**Comment by roukmoute** [comment]
Ok thanks.

I've tried here: https://asciinema.org/a/SBVtZyRoIOHgtv4ucYGV8geXc
And the latest command that I don't record:
```
➜  php -m | grep Zephir
Zephir Parser
```

So currently I've this error:
```
[ERROR] Extension namespace cannot be loaded
```

**Comment by Jeckerson** [comment]
> I've tried here: https://asciinema.org/a/SBVtZyRoIOHgtv4ucYGV8geXc

@roukmoute Go back to folder where you created your project. As you trying to compile your extension inside cloned repository `zephir-parser`.

**Comment by roukmoute** [comment]
We are moving forward!  
But I have always the same error from the beginning.

https://asciinema.org/a/U7farIfwGquIR2LHDNXdhrUnq

**Comment by Jeckerson** [comment]
Yes, this is problem of docs, which need to be updated, use:

```
zephir generate
zephir compile
```

**Comment by roukmoute** [comment]
Ok it finally works!
https://asciinema.org/a/UYM4rV5J5kUUaOAvnETwNbFFP

Thanks a lot
