### ISSUE TITLE
Calling static method yields `zephir_call_class_method_aparams: *return_value must be IS_NULL or IS_UNDEF`

### ISSUE THREAD

**Issue by andrewdalpino** [zephir-lang/zephir#2247]
Hello Zephir Team,

The issue our users are experiencing with the AdaMax Optimizer in Rubix ML are still persisting. Have you had a chance to investigate the root cause of it? It seems likely due to the static call to `maximum()`.

Here's a link to the thread https://github.com/RubixML/Sentiment/issues/4

**Comment by Jeckerson** [comment]
Closing, as original issue was fixed.
