### ISSUE TITLE
How can I explain this one?

### ISSUE THREAD

**Issue by navisoft** [zephir-lang/zephir#2257]
I have two extensions, the core and app.
The core extension has some classes:

```
class Core {
    public static app;
    public child;
    public function __construct() {
        let self::app = this;
    }
}

class Core_A {
    public function test() {
        var child;

        let child = Core::app->child; // this works
    }
}

class Core_B {
    public static function test() {

    }
}
```

The app extension has same class:
```
class App_A {
    public function test() {
        var child;

        let child = Core::app->child; // this doesn't works
        
        Core_B::test(); // this works (it means the core extension has been loaded)
    }
}
```
Of course, the Core will be called on the PHP application runtime and called before anything else.
But the problem is the compiler shows errors that the Core is undeclared during compiling.

Now, the workaround is, I define a new class inside the core extension:
```
class Core_Core {
    public function core() {
        return Core::app;
    }
}
```
Then inside the App_A of the app extension:
```
class App_A {
    public function test() {
        var child;

        let child = (new Core_Core)->core()->child; // this will works
    }
}
```

It's fine, but we need to create new class (might increase the memory) for the same thing.
Anything can explain why "Core::app->child" works inside the core extension and not for app extension?
Do we have any better way for it?

**Comment by Jeckerson** [comment]
Good chance that this is blocked by #2213

**Comment by Jeckerson** [comment]
@navisoft Try to use latest beta version of Zephir.
