### ISSUE TITLE
*_ce   undeclared (first use in this function)

### ISSUE THREAD

**Issue by bravoGor** [zephir-lang/zephir#2277]
I got this error:
ZEPHIR_VERSION=0.11.1
ZEPHIR_PARSER_VERSION=1.1.2

In file included from /zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:14:0:
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c: In function 'zephir_Poly_Hotel_Service_Poly_Hotel_Main_init':
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:29:62: error: 'poly_hotel_service_hotel_main_ce' undeclared (first use in this function)
  ZEPHIR_REGISTER_CLASS(Poly\\Hotel, Service_Poly_Hotel_Main, poly, hotel_service_hotel_main, poly_hotel_service_poly_hotel_main_method_entry, 0);
                                                              ^
./kernel/main.h:68:3: note: in definition of macro 'ZEPHIR_REGISTER_CLASS'
   lower_ns## _ ##name## _ce = zend_register_internal_class(&ce); \
   ^~~~~~~~
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:29:62: note: each undeclared identifier is reported only once for each function it appears in
  ZEPHIR_REGISTER_CLASS(Poly\\Hotel, Service_Poly_Hotel_Main, poly, hotel_service_hotel_main, poly_hotel_service_poly_hotel_main_method_entry, 0);
                                                              ^
./kernel/main.h:68:3: note: in definition of macro 'ZEPHIR_REGISTER_CLASS'
   lower_ns## _ ##name## _ce = zend_register_internal_class(&ce); \
   ^~~~~~~~
make: *** [poly/hotel/service_poly_hotel_main.lo] Error 1
make: *** Waiting for unfinished jobs....
In file included from /zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:14:0:
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c: In function 'zephir_Poly_Hotel_Service_Poly_Hotel_Main_init':
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:29:62: error: 'poly_hotel_service_hotel_main_ce' undeclared (first use in this function)
  ZEPHIR_REGISTER_CLASS(Poly\\Hotel, Service_Poly_Hotel_Main, poly, hotel_service_hotel_main, poly_hotel_service_poly_hotel_main_method_entry, 0);
                                                              ^
./kernel/main.h:68:3: note: in definition of macro 'ZEPHIR_REGISTER_CLASS'
   lower_ns## _ ##name## _ce = zend_register_internal_class(&ce); \
   ^~~~~~~~
/zephir/poly/poly/ext/poly/hotel/service_poly_hotel_main.zep.c:29:62: note: each undeclared identifier is reported only once for each function it appears in
  ZEPHIR_REGISTER_CLASS(Poly\\Hotel, Service_Poly_Hotel_Main, poly, hotel_service_hotel_main, poly_hotel_service_poly_hotel_main_method_entry, 0);
                                                              ^
./kernel/main.h:68:3: note: in definition of macro 'ZEPHIR_REGISTER_CLASS'
   lower_ns## _ ##name## _ce = zend_register_internal_class(&ce); \
   ^~~~~~~~
make: *** [poly/hotel/service_poly_hotel_main.lo] Error 1

**Comment by Jeckerson** [comment]
> ZEPHIR_VERSION=0.11.1
> ZEPHIR_PARSER_VERSION=1.1.2

Try with latest versions of both

**Comment by Jeckerson** [comment]
Closing, feel free to re-open in case problems with latest version of Zephir and Zephir parser.

**Comment by andrewdalpino** [comment]
> > ZEPHIR_VERSION=0.11.1
> > ZEPHIR_PARSER_VERSION=1.1.2
> 
> Try with latest versions of both

Hi @Jeckerson, I have Parser 1.6.0 and Zephir lib 0.17 installed and I'm getting this error as well

**Comment by Jeckerson** [comment]
@andrewdalpino Try development branch
