### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by hablema** [zephir-lang/zephir#2281]
The stub.so file was created successfully. But when adding to php.ini , any PHP commands returns this error

Eg: php -v 

PHP Fatal error:  Class 'psr\http\message\messageinterface' not found in Unknown on line 0
Segmentation fault (core dumped)

PHP version 8.0

**Comment by hablema** [comment]
{
    "stubs": {
        "path": "ide\/%version%\/%namespace%\/",
        "stubs-run-after-generate": false,
        "banner": "\/**\n * This file is part of the Zephir.\n *\n * (c) Phalcon Team <team@zephir-lang.com>\n *\n * For the full copyright and license information, please view\n * the LICENSE file that was distributed with this source code.\n *\/"
    },
    "api": {
        "path": "doc\/%version%",
        "theme": {
            "name": "zephir",
            "options": {
                "github": "https:\/\/github.com\/user\/repo",
                "analytics": null,
                "main_color": "#3E6496",
                "link_color": "#3E6496",
                "link_hover_color": "#5F9AE7"
            }
        }
    },
    "warnings": {
        "unused-variable": true,
        "unused-variable-external": false,
        "possible-wrong-parameter": true,
        "possible-wrong-parameter-undefined": false,
        "nonexistent-function": true,
        "nonexistent-class": true,
        "non-valid-isset": true,
        "non-array-update": true,
        "non-valid-objectupdate": true,
        "non-valid-fetch": true,
        "invalid-array-index": true,
        "non-array-append": true,
        "invalid-return-type": true,
        "unreachable-code": true,
        "nonexistent-constant": true,
        "not-supported-magic-constant": true,
        "non-valid-decrement": true,
        "non-valid-increment": true,
        "non-valid-clone": true,
        "non-valid-new": true,
        "non-array-access": true,
        "invalid-reference": true,
        "invalid-typeof-comparison": true,
        "conditional-initialization": true
    },
    "optimizations": {
        "static-type-inference": true,
        "static-type-inference-second-pass": true,
        "local-context-pass": true,
        "constant-folding": true,
        "static-constant-class-folding": true,
        "call-gatherer-pass": true,
        "check-invalid-reads": false,
        "private-internal-methods": false,
        "public-internal-methods": false,
        "public-internal-functions": true
    },
    "extra": {
        "indent": "spaces",
        "export-classes": false
    },
    "namespace": "utils",
    "name": "utils",
    "description": "Description <b>test<\/b> for<br\/>Test Extension.",
    "author": "Phalcon Team and contributors",
    "version": "1.0.0",
    "verbose": true,
    "requires": {
        "extensions": [
            "PDO",
            "SPL",
            "standard",
            "hash",
            "json"
        ]
    },
    "globals": {
        "my_setting_1": {
            "type": "bool",
            "default": true,
            "ini-entry": {
                "name": "ini-entry.my_setting_1",
                "scope": "PHP_INI_ALL"
            }
        },
        "test_setting_1": {
            "type": "bool",
            "default": true
        },
        "my_setting_2": {
            "type": "int",
            "default": 10
        },
        "my_setting_3": {
            "type": "double",
            "default": 15.2
        },
        "my_setting_4": {
            "type": "char",
            "default": "A"
        },
        "db.my_setting_1": {
            "type": "bool",
            "default": false
        },
        "db.my_setting_2": {
            "type": "int",
            "default": 100
        },
        "db.my_setting_3": {
            "type": "double",
            "default": 7.5
        },
        "orm.cache_level": {
            "type": "int",
            "default": 3
        },
        "orm.cache_enable": {
            "type": "bool",
            "default": true
        },
        "extension.test_ini_variable": {
            "type": "bool",
            "default": true,
            "ini-entry": {
                "name": "extension.test_ini_variable",
                "scope": "PHP_INI_ALL"
            }
        }
    },
    "info": [
        {
            "header": [
                "Test Extension support",
                "Value"
            ],
            "rows": [
                [
                    "Lifecycle hooks",
                    "PHP provides several lifecycle events, which extensions can use to perform common initialization or shutdown tasks."
                ],
                [
                    "Static Analysis",
                    "Test extensions' compiler provides static analysis of the compiled code."
                ]
            ]
        },
        {
            "header": [
                "Test variable",
                "Value"
            ],
            "rows": [
                [
                    "Extension",
                    "Installed"
                ],
                [
                    "NFR",
                    "Contributions are welcome!"
                ]
            ]
        }
    ]
}

**Comment by Jeckerson** [comment]
Hello

With what version of Zephir it was compiled?

**Comment by hablema** [comment]
PHP 8.0.10 (cli) (built: Aug 26 2021 15:50:07) ( NTS )
Zephir Version 0.14.0
PHP Zephir Parser 1.3.8

PHPIZE Returns this :-

Configuring for:
PHP Api Version:         20200930
Zend Module Api No:      20200930
Zend Extension Api No:   420200930

**Comment by Jeckerson** [comment]
Make sure that you are using latest `beta.3` of Zephir `0.14.0`. Also make sure that `psr` extension is installed.

**Comment by hablema** [comment]
Zephir verision : Zephir 0.14.0 by Andres Gutierrez and Serghei Iakovlev (beta.3)

PSR was installed by : sudo apt-get install php8.0-psr

**Comment by Jeckerson** [comment]
What are steps that you execute?

**Comment by hablema** [comment]
1. Cloned Zephir from GIT
2. Composer Update
3. Cloned Zephir Parser from GIT
4. Generated the default Binary extension method
5. Added extsntion to PHP.ini
6. Zephir Init and added the default greeting class
7. Zephir Build
8. Added the generated stub.so to PHP.ini
9. Restarted apache
10 any php command after this give me this error

**Comment by Jeckerson** [comment]
Could you provide Zephir code example where you are using `psr\http\message\messageinterface` this interface?
And also generated `.zep.c` code of this specific file/class.

**Comment by hablema** [comment]
**greetings.zep**

```
namespace utils;
class Greeting
{
    public static function say()
    {
        echo "hello world!";
    }
}
```

**Comment by Jeckerson** [comment]
You mentioned `stub.so` at the beginning. According to your namespace, the generated file must be `utils.so`. It might be that you are building and compiling wrong project or folder.

**Comment by Jeckerson** [comment]
Try this tutorial and see if it works
https://docs.zephir-lang.com/0.12/en/tutorial#tutorial
