### ISSUE TITLE
Get rid of `symfony/*` dependencies

### ISSUE THREAD

**Issue by Jeckerson** [zephir-lang/zephir#2295]
Every release we are blocked due some external packages that are on their own mind when to support next version of PHP. Same occurred with PHP8.0, in which we needed to shift minimal support of Zephir to PHP7.4.

Implement own simple solutions for CLI, DI and logs in Zephir and get rid of next packages:
* symfony/console
* symfony/framework-bundle
* symfony/monolog-bridge
* symfony/monolog-bundle
* symfony/yaml

**Comment by StudioMaX** [comment]
Symfony has been supporting PHP 8.1 in their CI since version 5.3.7 which was released in August, isn't it? Symfony 5.2 is already [EOL](https://symfony.com/releases/5.2) since July 2021.

**Comment by Jeckerson** [comment]
@StudioMaX tl;dr: It doesn't matter, "writing for PHP **in** PHP is utopia", especially when there alot of external dependencies in your composer.json. Zephir itself must be maximum abstract in that terms, in what it really might and can depend are PHP extensions.

Long description about PHP8.1 support:
![image](https://user-images.githubusercontent.com/3289702/135706966-34010ad8-c0a4-40e2-8d96-cf1d82f51a37.png)
```
"name": "symfony/framework-bundle",
"version": "v5.3.8",
```

This occur because symfony removes comments about deprecation notice (`#[ReturnTypeWillChange]`) when it _caches_ PHP files...

I tried to configure the configuration file from yaml to PHP, but their logic seem to differ...
https://github.com/zephir-lang/zephir/blob/1bc9d92db414ea33227189642d743bfe91e993a7/config/symfony/services.php#L16
So also no luck.

P.S. Packages mentioned above are last peace for little bit more liberty in terms of faster support of new version of PHP in Zephir, because Zephir Parser is already ready to go in both: PHP8.1 and PHP8.2 versions.

P.P.S. Zephir does not need any complex libraries to make its job: read AST array from parser and generate correct C code, then execute compilation commands to create PHP compatible extension.
