### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by cayolblake** [zephir-lang/zephir#2362]
Hello,

Is this project dead or alive?

**Comment by Arhell** [comment]
No

**Comment by ruudboon** [comment]
Last commit 14 days ago...
https://github.com/zephir-lang/zephir/commit/cc7ecd35745594710913edab1afe5c6d82f52932

**Comment by Jeckerson** [comment]
Project is alive, but if you want to help - we are open for it.

**Comment by cayolblake** [comment]
Thanks all. Kinda seemed like it but now, it's a relief.
