### ISSUE TITLE
The Zephir Parser extension is outdated.

### ISSUE THREAD

**Issue by cline-pk** [zephir-lang/zephir#2369]
Hi, i'm getting this error even i'm using latest Zephir Parser extension 1.5.0

[ERROR]

     ─────────────────────────────────────
     ───────────────────────
       The Zephir Parser extension is outdated.
       Note: Zephir no longer distributed with internal parser.
       Minimum required Zephir Parser version: 1.3.0

       To install latest stable Zephir Parser please refer to:
       https://github.com/phalcon/php-zephir-parser
     ─────────────────────────────────────
     ───────────────────────

**Comment by Jeckerson** [comment]
Update Zephir itself until latest version.

**Comment by zubin999** [comment]
my php version is 7.2.34

`
PHP 7.2.34 (cli) (built: Jun  7 2022 16:03:23) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v11.0.1, Copyright (c) 2002-2022, by ionCube Ltd.
`

and use the zephir 0.12.21

`
root@ubuntu-focal:~/FreqFunc# zephir --version
Zephir 0.12.21 by Andres Gutierrez and Serghei Iakovlev (8a412a1)
`

I got the same problem

**Comment by BennyXZY** [comment]
Not sure if this helps anyone, had the same issue and figured it out.
The issue is Zephir Parser extension. 
In version 1.4.1, extension was renamed from Zephir Parser to zephir_parser.
Zephir 0.12.21 can't detect Parser version.

Use Zephir Parser 1.4.0 with Zephir 0.12.21.
