### ISSUE TITLE
Zephir no longer supports versions below 7.4?

### ISSUE THREAD

**Issue by woddp** [zephir-lang/zephir#2377]
php7.4 8.0 normal compilation

However, I lowered the Zephir version and prompted to upgrade the Zephir parser version

![image](https://user-images.githubusercontent.com/19522809/184295673-d96961f1-91d2-471a-98c1-9629757c0783.png)

![image](https://user-images.githubusercontent.com/19522809/184295736-df6f5c0d-0cbc-4187-b81c-ca3dd600b119.png)

**Comment by rcmcdonald91** [comment]
Correct. You need to use a newer version of PHP.

**Comment by Jeckerson** [comment]
Please use previous versions that supports `<= 7.4`.
