### ISSUE TITLE
Grammar suggestion for tag line

### ISSUE THREAD

**Issue by brandonzylstra** [zephir-lang/zephir#2378]
> Zephir is a compiled high level language aimed to the creation of C-extensions for PHP.

It is possible that this is standard in some other dialect of English I'm unfamiliar with, but I've never heard "aim to _**noun**_" in my native American English, nor do I recall hearing it when I lived in Nigeria and was exposed to English from all over the world.

If I may make a recommendation, it would be one of the following 

1. Zephir is a compiled high-level language aimed to _ease_ the creation of C-extensions for PHP
2. Zephir is a compiled high-level language aimed _at_ the creation of C-extensions for PHP
3. Zephir is a compiled high-level language _designed for_ the creation of C-extensions for PHP

Number 1 uses the common "aim to _**verb**_".  That's a relatively small change but it feels much more natural to me.  Number 2 goes for the smallest possible change, and I don't love it, but it feels more natural than "aim at _**noun**_".  Number 3 is the one I feel is best, but it's a bigger change (in case that matters to you).

**Comment by niden** [comment]
This has been addressed. Thank you @brandondrew
