### ISSUE TITLE
0.16.3 Compilation speed is very slow

### ISSUE THREAD

**Issue by xqkeji** [zephir-lang/zephir#2395]
Every time I compile, I feel like I have to empty before compiling. What's the matter?

for Example:
 zephir build
 Zephir version has changed, use "zephir fullclean" to perform a full clean of the project
 Zephir version has changed, use "zephir fullclean" to perform a full clean of the project
 Preparing for PHP compilation...
 Preparing configuration file...
 Compiling...
 Zephir version has changed, use "zephir fullclean" to perform a full clean of the project
 Installing...

 Extension installed.

 ! [NOTE] Don't forget to restart your web server

**Comment by Jeckerson** [comment]
Use `-j` flag to run all in parallel all your cores.
Example with x32 threads (x16 CPU cores):
```
zephir build -j32
```
