### ISSUE TITLE
Discord link compromised

### ISSUE THREAD

**Issue by vicenterusso** [zephir-lang/zephir#2425]
Tried to click and redirect me to a porn website.

**Comment by niden** [comment]
The link works just fine. It is 

https://phalcon.io/discord which resolves to https://discord.com/invite/kRc2N2M

**Comment by niden** [comment]
Any more information you can provide will be useful

**Comment by vicenterusso** [comment]
That's not the link on the README

![image](https://github.com/zephir-lang/zephir/assets/80538/5183d7a6-56e9-48d4-9942-6d9259ea53ff)

**Comment by niden** [comment]
@vicenterusso Thank you. I addressed this.

**Comment by niden** [comment]
This was our old URL shortener. We have since moved everything to the phalcon.io domain.
