### ISSUE TITLE
file_get_contents() and http_response_header

### ISSUE THREAD

**Issue by lukaszwit** [zephir-lang/zephir#325]
In php there is a local scope variable "http_response_header" ( http://pl1.php.net/manual/en/reserved.variables.httpresponseheader.php ) that is creatied by php i.e. when calling file_get_contents() with URL. 
Is there any way to get to this variable in zephir when calling file_get_contents ?
##

**Comment by serg-deep** [comment]
@lukaszwit y can use simple hack in zephir:
```php
var
  content, http_response_header;

let
  content = file_get_contents('http://google.com/'),
  http_response_header = eval('$http_response_header');
```
It's ugly, but it work.
