### ISSUE TITLE
Adaptive behavior of parser checking method signature.

### ISSUE THREAD

**Issue by wapmorgan** [zephir-lang/zephir#507]
For now, we can not use convenient null for make argument optional.
Test code:

``` php
    static public function test(resource stdin = null)
```

Expected result:
_no errors_

Actual result:

```
Zephir\CompilerException: Default parameter type: resource in /home/wapmorgan/php-shell/shell/Subprocess.zep on line 18
```

Note: 
using runtime-calculated value like `fopen("php://memory", "r")` can help avoid null value, but that's unneeded.
##

**Comment by Jeckerson** [comment]
Already fixed in latest versions.
