### ISSUE TITLE
Late State Binding properties

### ISSUE THREAD

**Issue by pgaultier** [zephir-lang/zephir#606]
I saw that late state binding is working for methods ( #513 and #565 ) thanks a lot for that one ;-) but not for properties.

The keyword static is not recognized when used with properties and raise a 
- Zephir\ParseException: Syntax error ....
  exception

any plan about implementing  it ?

``` php
class A {
        public static $property = 'A property';
        public static function aStatic() {
                return static::$property;
        }
        public static function aSelf() {
                return self::$property;
        }
}

class B extends A {
        public static $property = 'B property';
        public static function bStatic() {
                return static::$property;
        }
        public static function bSelf() {
                return self::$property;
        }
}
```

calling `B::aStatic()` should return `"B property"` while `B.aSelf()` should return `"A property"`
##

**Comment by jimthunderbird** [comment]
Or you could use my tool, it will flatten the class hierarchy and as a by-product, solved the late static binding problem.
https://github.com/jimthunderbird/php-to-c-extension#example-11

**Comment by mruz** [comment]
Also to const access by `static::` https://github.com/phalcon/zephir/issues/1011

``` zep
class Version
{
    const BUILD = 1;

    public static function getBuild() {
        return static::BUILD;
    }
}
```

``` php
<?php

class MyVersion extends Version
{
    const BUILD = 2;
}
```

``` php
var_dump(MyVersion::getBuild()); //2
```

**Comment by mruz** [comment]
@steffengy can I use `static::` for constant/property? There is https://github.com/phalcon/zephir/pull/565 but I'm getting:

```
Zephir\ParseException: Syntax error in /home/mruz/Dropbox/git/ice/framework/ice/version.zep on line 30

                return static::BUILD;
        ---------------------------^
```

**Comment by steffengy** [comment]
that just was implemented for functions/methods afaik.

**Comment by Jeckerson** [comment]
Already implemented.
