### ISSUE TITLE
Link error, INTERNED_LEN & str_efree is not defined in PHP5.3 build on Windows

### ISSUE THREAD

**Issue by hylent** [zephir-lang/zephir#616]
When building with PHP5.3 on Windows, `INTERNED_LEN` and `str_efree` is not defined, then a link error occures.

`INTERNED_LEN` & `str_efree` is in the Zend api `<Zend/zend_string.h>` which is since PHP5.4, but the Zephir kernel micros seems not quite the same as Zend api.

See:
- https://github.com/phalcon/zephir/blob/master/ext/kernel/main.h#L341
- https://github.com/phalcon/zephir/blob/master/ext/kernel/string.h#L116
- https://github.com/php/php-src/blob/PHP-5.4.34/Zend/zend_string.h
##

**Comment by Jeckerson** [comment]
Already fixed.
