### ISSUE TITLE
Persistent extension global with lifespan until extension unload

### ISSUE THREAD

**Issue by h3ph4est7s** [zephir-lang/zephir#648]
Does zephir support extension globals which last from extension load to extension unload?
i found something relevant but it doesn't work.
Warning: Function "global_set" does not exist at compile time in /root/zephir/license/license/authorise.zep on 9 [nonexistent-function]
global_set("my_setting_1",false);
##

**Comment by Jeckerson** [comment]
As mentioned above, use `globals`

Docs - https://docs.zephir-lang.com/0.12/en/globals#extension-globals
