### ISSUE TITLE
Appending to array property misbehaves when called from an inherited class

### ISSUE THREAD

**Issue by rvanvelzen** [zephir-lang/zephir#700]
``` php
namespace Es;

class Test
{
    private entries = [] { get };

    public function addItem(item)
    {
        let this->entries[] = item;
        return this;
    }
}
```

Calling code:

``` php
<?php
class MyTest extends Es\Test { }

$original = new Es\Test();
$original->addItem(1);
var_dump($original->getEntries());

$inherited = new MyTest();
$inherited->addItem(1);
var_dump($inherited->getEntries());
```

Expected result:

```
array (size=1)
  0 => int 1
array (size=1)
  0 => int 1
```

Actual result:

```
array (size=1)
  0 => int 1
array (size=0)
  empty
```

As you can see, the calls to the original class work properly. However, the call to the inherited class fails to update the `entries` list. This does seem strange to me?

When the property is `protected` or `public` there is no issue.
##

**Comment by mruz** [comment]
Similar to my issue https://github.com/phalcon/zephir/issues/537

**Comment by rvanvelzen** [comment]
Just grabbed the latest release, and this issue still exists.

**Comment by Jeckerson** [comment]
Already fixed here https://github.com/zephir-lang/zephir/issues/2089
Closing.
