### ISSUE TITLE
Incorrect cast object to array, get empty array.

### ISSUE THREAD

**Issue by kse300489** [zephir-lang/zephir#774]
When cast object to array, get empty array. 
Php exmaple:

``` php
$std = new stdClass();
$std->prop0 = 0;
$std->prop1 = 1;

$std = (array)$std;

var_dump($std);
```

Output:

``` text
array(2) {
  'prop0' =>
  int(0)
  'prop1' =>
  int(1)
}
```

Zephir:

``` php
var
    obj;

let
    obj = new \stdClass(),
    obj->prop0 = 0,
    obj->prop1 = 1,
    obj = (array)obj;

var_dump(obj);
```

``` text
array(0) {
}
```
##

**Comment by hylent** [comment]
Feature `var` type casting to `array` type
 +1

**Comment by Jurigag** [comment]
@steffengy

Could this be fixed/implemented ?

I actually need this feature to add some new feature to phalcon.

**Comment by steffengy** [comment]
theoretically sure. 
It's currently unlikely that somebody has enough time to actually implement this though. 
I guess you'll have to use `get_object_vars` for now.

**Comment by Jurigag** [comment]
Well get_object_vars don't work in my case :P But i used ArrayObject.

**Comment by steffengy** [comment]
@Jurigag for ArrayObject `$arrobj->getArrayCopy()` might work as a workaround.

**Comment by sergeyklay** [comment]
@dreamsxin Could you please take a look
