### ISSUE TITLE
Bugs with constructors

### ISSUE THREAD

**Issue by artknyazev** [zephir-lang/zephir#914]
php.net/manual says:

> For backwards compatibility, if PHP 5 cannot find a __construct() function for a given class, and the
> class did not inherit one from a parent class, it will search for the old-style constructor function, by the 
> name of the class. 

There are 2 problems in Zephir I found when I worked with classes which haven't method defined as "__construct()", but have method "className()" (for example: mysqli extension - try `ReflectionClass::export('mysqli');`):

``` php
namespace Test;

class TestClass extends \mysqli {

    public function __construct(){
        parent::__construct();
    }
}
```

Zephir compilator fails with exception:

```
Zephir\CompilerException: Class '\mysqli' does not implement static method: '__construct' in /var/www/test/test/testclass.zep on line 6

            parent::__construct();
    -----------------------------^
```

It can be fixed in https://github.com/phalcon/zephir/blob/master/Library/ClassDefinition.php#L607  (getMethod() must returns `$this->methods[$this->name]` (if it's set)  when __constructor not found).

Also, when I try call this

``` php
namespace Test;

class TestClass {

    public function getDb(){
        return new \mysqli();
    }
}
```

in  

``` php
<?php (new \Test\TestClass())->getDb(); ?>
```

script fails on:

> Fatal error: Uncaught exception 'RuntimeException' with message 'Call to undefined method mysqli::__construct()' in ...
##

**Comment by wartodolin** [comment]
no answer till now ?

**Comment by Jeckerson** [comment]
`mysqli` extension must be installed before compilation.
