### ISSUE TITLE
Cannot Call Static Methods of External Classes [$10]

### ISSUE THREAD

**Issue by AKermodeBear** [zephir-lang/zephir#916]
Hello,

Zephir allows us to create objects that are not currently defined in the project like so:

``` zephir
let someObject = new \Class_From_Elsewhere();
```

However we cannot call static methods as might be expected:

``` zephir
let someResult = \Class_From_Elsewhere::someMethod("foo");
```

I'm currently using this as a workaround:

``` zephir
let someResult = call_user_func_array(
   ["\Class_From_Elsewhere", "someMethod"], ["foo"]);
```

Thank you, Zephir people!

Using Zephir at commit 416c98943db845112825eebafa5ad13acda4ce26 (Wed Apr 22).

**Comment by steffengy** [comment]
Alternatively: ``\Class_From_Elsewhere::{"someMethod"}("foo");`` should work

**Comment by ovr** [comment]
I think warning was caused by `\Class_From_Elsewhere` does not exist
You need to use prototype with autoload for it class

Can you show full compiler exception?

**Comment by ovr** [comment]
ping @Stormwing

**Comment by Stormwing** [comment]
Howdy,

The compiler will produce an error like this:
```
Zephir\CompilerException: Class name: MyClass does not exist in /home/bear/repos/zephir-sandbox/test/test/Test.zep on line 6

          return \MyClass::method();
        ---------------------------^
```

**Comment by valVk** [comment]
ping @Stormwing

Maybe this one will help you.

```php
namespace Utils;

class SomeClass {
     public function getClassName()
     {
     	var className = "NotExists";
     	return {className}::method();
     }
}
```

```php
#!/usr/bin/env php
<?php

class NotExists
{
	public static function method()
	{
		return "Hello from big Hangout";
	}
}


$a = new \Utils\SomeClass(); 
var_dump($a->getClassName());
```

**Comment by fabiante** [comment]
I am having the same problem. Neither of the workarounds work for me.

`\Class_From_Elsewhere::{"someMethod"}("foo");` throws a compiler error and the `call_user_func_array` workaround just throws a `class ... not found` error during runtime.

**Comment by sergeyklay** [comment]
@FabianTe To achieve better performance consider use [create_instance_params](https://github.com/phalcon/cphalcon/pull/14419 ) and avoid call_user_func_array as long as you can.

**Comment by fabiante** [comment]
We figured out, that this works, as long as double backslashes are used:

```
let someResult = call_user_func_array(
   ["\\MyNamespace\\Subnamespace\\MyNormalClass", "someMethod"], ["foo"]);
```

@sergeyklay Thanks
