### ISSUE TITLE
Error code 139, when try to create \DOMDocument object inside class

### ISSUE THREAD

**Issue by kse300489** [zephir-lang/zephir#923]
On the latest zephir master this code produce error code 139.

Zephir code:

``` php
namesapce Ns;

class Test{
    public function __construct(){
        var
            domNode;

        let
            domNode = new \DOMDocument();
    }
}
```

Php code:

``` php
$test = new \Ns\Test();
```

Output:

``` text
Process finished with exit code 139
```

OS: Linux web 3.2.0-4-686-pae #1 SMP Debian 3.2.60-1+deb7u3 i686 GNU/Linux
GCC: gcc (Debian 4.7.2-5) 4.7.2
Copyright (C) 2012 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
##

**Comment by maxgalbu** [comment]
Works for me, what happens if you run `php -i | grep dom`?

Linux developer3 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by steffengy** [comment]
Also what PHP versions are you using?

**Comment by coollider** [comment]
@maxgalbu of course DOM extension installed.

@steffengy my php version PHP 5.4.36-0+deb7u3.

Very strange this code successful work on:
Linux nettop 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) x86_64 GNU/Linux
gcc version 4.9.2 (Debian 4.9.2-10)
PHP 5.6.7-1
