### ISSUE TITLE
Method name same with class name should not be treated as ctor in namespace

### ISSUE THREAD

**Issue by hylent** [zephir-lang/zephir#934]
Method name same with class name should not be treated as ctor in namespace

Evironment:

```
Zephir latest master 79eac35ee759e8025b02c41c2446bbd8d305d982
CentOS 6.6 gcc 4.4.7
PHP 5.5.22 TS DEBUG build
```

foo/baz.zep

```
namespace Foo;

class Baz
{
    public function baz()
    {
        echo "I am not supposed to output when constructing object!", PHP_EOL;
    }
}
```

Test:

```
php -r 'new foo\baz;'
```

Outputs:

```
I am not supposed to output when constructing object!
```
##

**Comment by andresgutierrez** [comment]
Yes, it should be treated as constructor: http://php.net/manual/en/oop4.constructor.php

**Comment by hylent** [comment]
As of PHP 5.3.3, methods with the same name as the last element of a namespaced class name will no longer be treated as constructor. This change doesn't affect non-namespaced classes. 

http://php.net/manual/en/language.oop5.decon.php

**Comment by sergeyklay** [comment]
@hylent Hmm.. `public function $baz()` has the same effect?

**Comment by hylent** [comment]
@sergeyklay the same effect..

**Comment by steffengy** [comment]
The question is if you want to use php's inconsistent behavior or only treat __construct as constructor - which I would prefer.

**Comment by sergeyklay** [comment]
Closed in favor of https://github.com/phalcon/zephir/issues/1803
