### ISSUE TITLE
self::var problem

### ISSUE THREAD

**Issue by ivyhjk** [zephir-lang/zephir#988]
I have the following piece of code in PHP:

``` php
foreach ($values as $key => $value) {
    self::${$key} = $value;
}
```

and it works, but in Zephir, i have the following piece code:

``` zephir
var key;
var value;

for key, value in values {
    let self::{"key"} = value;
}
```

and zephir compiler throws this error:

```
Zephir\ParseException: Syntax error .....
let self::{"key"} = val;
----------^
```

and i try with these lines and the same problem:

``` zephir
let self::{'key'} = val;
let self::"key" = val;
let self::'key' = val;
let self::"{key}" = val;
```

Is this a bug, or i'm doing something bad?

ps: sorry for my bad english :dancers:
##

**Comment by fezfez** [comment]
Zephir version ?

**Comment by ivyhjk** [comment]
Hi, Zephir version 0.6.3a
